In [1]:
import pandas as pd

df = pd.read_csv("ag_news_en_500.csv")
print(df.columns)
print(df["label"].value_counts().sort_index())
df.head()

Index(['text', 'label'], dtype='object')
0    121
1    116
2    124
3    139
Name: label, dtype: int64

                                                text  label
0  Fan v Fan: Manchester City-Tottenham Hotspur T...      1
1  Paris Tourists Search for Key to 'Da Vinci Cod...      0
2  Net firms: Don't tax VoIP The Spanish-American...      3
3  Dependent species risk extinction The global e...      3
4  EDS Is Charter Member of Siebel BPO Alliance (...      3

In [2]:
label_map = {
    0: "World",
    1: "Sports",
    2: "Business",
    3: "Sci/Tech"
}

df["label_name"] = df["label"].map(label_map)
df.head()

                                                text  label label_name
0  Fan v Fan: Manchester City-Tottenham Hotspur T...      1     Sports
1  Paris Tourists Search for Key to 'Da Vinci Cod...      0      World
2  Net firms: Don't tax VoIP The Spanish-American...      3   Sci/Tech
3  Dependent species risk extinction The global e...      3   Sci/Tech
4  EDS Is Charter Member of Siebel BPO Alliance (...      3   Sci/Tech

In [4]:
import re
import time
from openai import OpenAI

client = OpenAI(api_key=" ")

def classify_agnews_en_basic(text: str) -> str:
    prompt = f"""You are a news topic classifier.

Classify the following news text into one of these 4 categories:
World, Sports, Business, Sci/Tech

Respond with only one category name.
Do not explain your answer.

News text:
{text}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    output = response.choices[0].message.content.strip()

    # normalize output
    output_lower = output.lower()

    if "world" in output_lower:
        return "World"
    elif "sports" in output_lower:
        return "Sports"
    elif "business" in output_lower:
        return "Business"
    elif "sci" in output_lower or "tech" in output_lower:
        return "Sci/Tech"
    else:
        return output

In [5]:
for i in range(5):
    pred = classify_agnews_en_basic(df.loc[i, "text"])
    print(i, "pred:", pred, "| true:", df.loc[i, "label_name"])
    time.sleep(0.3)

0 pred: Sports | true: Sports
1 pred: World | true: World
2 pred: Business | true: Sci/Tech
3 pred: Sci/Tech | true: Sci/Tech
4 pred: Business | true: Sci/Tech

In [6]:
if "pred_en_basic" not in df.columns:
    df["pred_en_basic"] = ""

for i in range(len(df)):
    if isinstance(df.loc[i, "pred_en_basic"], str) and df.loc[i, "pred_en_basic"].strip():
        continue

    print(f"AGNews En-Basic {i+1}/{len(df)}")

    df.loc[i, "pred_en_basic"] = classify_agnews_en_basic(df.loc[i, "text"])

    if (i + 1) % 25 == 0:
        df.to_csv("agnews_en_basic_progress.csv", index=False)

    time.sleep(0.3)

df.to_csv("agnews_en_basic_final.csv", index=False)
print("English En-Basic finished")

AGNews En-Basic 1/500
AGNews En-Basic 2/500
AGNews En-Basic 3/500
AGNews En-Basic 4/500
AGNews En-Basic 5/500
AGNews En-Basic 6/500
AGNews En-Basic 7/500
AGNews En-Basic 8/500
AGNews En-Basic 9/500
AGNews En-Basic 10/500
AGNews En-Basic 11/500
AGNews En-Basic 12/500
AGNews En-Basic 13/500
AGNews En-Basic 14/500
AGNews En-Basic 15/500
AGNews En-Basic 16/500
AGNews En-Basic 17/500
AGNews En-Basic 18/500
AGNews En-Basic 19/500
AGNews En-Basic 20/500
AGNews En-Basic 21/500
AGNews En-Basic 22/500
AGNews En-Basic 23/500
AGNews En-Basic 24/500
AGNews En-Basic 25/500
AGNews En-Basic 26/500
AGNews En-Basic 27/500
AGNews En-Basic 28/500
AGNews En-Basic 29/500
AGNews En-Basic 30/500
AGNews En-Basic 31/500
AGNews En-Basic 32/500
AGNews En-Basic 33/500
AGNews En-Basic 34/500
AGNews En-Basic 35/500
AGNews En-Basic 36/500
AGNews En-Basic 37/500
AGNews En-Basic 38/500
AGNews En-Basic 39/500
AGNews En-Basic 40/500
AGNews En-Basic 41/500
AGNews En-Basic 42/500
AGNews En-Basic 43/500
AGNews En-Basic 44/500
AGNews En-Basic 45/500
AGNews En-Basic 46/500
AGNews En-Basic 47/500
AGNews En-Basic 48/500
AGNews En-Basic 49/500
AGNews En-Basic 50/500
AGNews En-Basic 51/500
AGNews En-Basic 52/500
AGNews En-Basic 53/500
AGNews En-Basic 54/500
AGNews En-Basic 55/500
AGNews En-Basic 56/500
AGNews En-Basic 57/500
AGNews En-Basic 58/500
AGNews En-Basic 59/500
AGNews En-Basic 60/500
AGNews En-Basic 61/500
AGNews En-Basic 62/500
AGNews En-Basic 63/500
AGNews En-Basic 64/500
AGNews En-Basic 65/500
AGNews En-Basic 66/500
AGNews En-Basic 67/500
AGNews En-Basic 68/500
AGNews En-Basic 69/500
AGNews En-Basic 70/500
AGNews En-Basic 71/500
AGNews En-Basic 72/500
AGNews En-Basic 73/500
AGNews En-Basic 74/500
AGNews En-Basic 75/500
AGNews En-Basic 76/500
AGNews En-Basic 77/500
AGNews En-Basic 78/500
AGNews En-Basic 79/500
AGNews En-Basic 80/500
AGNews En-Basic 81/500
AGNews En-Basic 82/500
AGNews En-Basic 83/500
AGNews En-Basic 84/500
AGNews En-Basic 85/500
AGNews En-Basic 86/500
AGNews En-Basic 87/500
AGNews En-Basic 88/500
AGNews En-Basic 89/500
AGNews En-Basic 90/500
AGNews En-Basic 91/500
AGNews En-Basic 92/500
AGNews En-Basic 93/500
AGNews En-Basic 94/500
AGNews En-Basic 95/500
AGNews En-Basic 96/500
AGNews En-Basic 97/500
AGNews En-Basic 98/500
AGNews En-Basic 99/500
AGNews En-Basic 100/500
AGNews En-Basic 101/500
AGNews En-Basic 102/500
AGNews En-Basic 103/500
AGNews En-Basic 104/500
AGNews En-Basic 105/500
AGNews En-Basic 106/500
AGNews En-Basic 107/500
AGNews En-Basic 108/500
AGNews En-Basic 109/500
AGNews En-Basic 110/500
AGNews En-Basic 111/500
AGNews En-Basic 112/500
AGNews En-Basic 113/500
AGNews En-Basic 114/500
AGNews En-Basic 115/500
AGNews En-Basic 116/500
AGNews En-Basic 117/500
AGNews En-Basic 118/500
AGNews En-Basic 119/500
AGNews En-Basic 120/500
AGNews En-Basic 121/500
AGNews En-Basic 122/500
AGNews En-Basic 123/500
AGNews En-Basic 124/500
AGNews En-Basic 125/500
AGNews En-Basic 126/500
AGNews En-Basic 127/500
AGNews En-Basic 128/500
AGNews En-Basic 129/500
AGNews En-Basic 130/500
AGNews En-Basic 131/500
AGNews En-Basic 132/500
AGNews En-Basic 133/500
AGNews En-Basic 134/500
AGNews En-Basic 135/500
AGNews En-Basic 136/500
AGNews En-Basic 137/500
AGNews En-Basic 138/500
AGNews En-Basic 139/500
AGNews En-Basic 140/500
AGNews En-Basic 141/500
AGNews En-Basic 142/500
AGNews En-Basic 143/500
AGNews En-Basic 144/500
AGNews En-Basic 145/500
AGNews En-Basic 146/500
AGNews En-Basic 147/500
AGNews En-Basic 148/500
AGNews En-Basic 149/500
AGNews En-Basic 150/500
AGNews En-Basic 151/500
AGNews En-Basic 152/500
AGNews En-Basic 153/500
AGNews En-Basic 154/500
AGNews En-Basic 155/500
AGNews En-Basic 156/500
AGNews En-Basic 157/500
AGNews En-Basic 158/500
AGNews En-Basic 159/500
AGNews En-Basic 160/500
AGNews En-Basic 161/500
AGNews En-Basic 162/500
AGNews En-Basic 163/500
AGNews En-Basic 164/500
AGNews En-Basic 165/500
AGNews En-Basic 166/500
AGNews En-Basic 167/500
AGNews En-Basic 168/500
AGNews En-Basic 169/500
AGNews En-Basic 170/500
AGNews En-Basic 171/500
AGNews En-Basic 172/500
AGNews En-Basic 173/500
AGNews En-Basic 174/500
AGNews En-Basic 175/500
AGNews En-Basic 176/500
AGNews En-Basic 177/500
AGNews En-Basic 178/500
AGNews En-Basic 179/500
AGNews En-Basic 180/500
AGNews En-Basic 181/500
AGNews En-Basic 182/500
AGNews En-Basic 183/500
AGNews En-Basic 184/500
AGNews En-Basic 185/500
AGNews En-Basic 186/500
AGNews En-Basic 187/500
AGNews En-Basic 188/500
AGNews En-Basic 189/500
AGNews En-Basic 190/500
AGNews En-Basic 191/500
AGNews En-Basic 192/500
AGNews En-Basic 193/500
AGNews En-Basic 194/500
AGNews En-Basic 195/500
AGNews En-Basic 196/500
AGNews En-Basic 197/500
AGNews En-Basic 198/500
AGNews En-Basic 199/500
AGNews En-Basic 200/500
AGNews En-Basic 201/500
AGNews En-Basic 202/500
AGNews En-Basic 203/500
AGNews En-Basic 204/500
AGNews En-Basic 205/500
AGNews En-Basic 206/500
AGNews En-Basic 207/500
AGNews En-Basic 208/500
AGNews En-Basic 209/500
AGNews En-Basic 210/500
AGNews En-Basic 211/500
AGNews En-Basic 212/500
AGNews En-Basic 213/500
AGNews En-Basic 214/500
AGNews En-Basic 215/500
AGNews En-Basic 216/500
AGNews En-Basic 217/500
AGNews En-Basic 218/500
AGNews En-Basic 219/500
AGNews En-Basic 220/500
AGNews En-Basic 221/500
AGNews En-Basic 222/500
AGNews En-Basic 223/500
AGNews En-Basic 224/500
AGNews En-Basic 225/500
AGNews En-Basic 226/500
AGNews En-Basic 227/500
AGNews En-Basic 228/500
AGNews En-Basic 229/500
AGNews En-Basic 230/500
AGNews En-Basic 231/500
AGNews En-Basic 232/500
AGNews En-Basic 233/500
AGNews En-Basic 234/500
AGNews En-Basic 235/500
AGNews En-Basic 236/500
AGNews En-Basic 237/500
AGNews En-Basic 238/500
AGNews En-Basic 239/500
AGNews En-Basic 240/500
AGNews En-Basic 241/500
AGNews En-Basic 242/500
AGNews En-Basic 243/500
AGNews En-Basic 244/500
AGNews En-Basic 245/500
AGNews En-Basic 246/500
AGNews En-Basic 247/500
AGNews En-Basic 248/500
AGNews En-Basic 249/500
AGNews En-Basic 250/500
AGNews En-Basic 251/500
AGNews En-Basic 252/500
AGNews En-Basic 253/500
AGNews En-Basic 254/500
AGNews En-Basic 255/500
AGNews En-Basic 256/500
AGNews En-Basic 257/500
AGNews En-Basic 258/500
AGNews En-Basic 259/500
AGNews En-Basic 260/500
AGNews En-Basic 261/500
AGNews En-Basic 262/500
AGNews En-Basic 263/500
AGNews En-Basic 264/500
AGNews En-Basic 265/500
AGNews En-Basic 266/500
AGNews En-Basic 267/500
AGNews En-Basic 268/500
AGNews En-Basic 269/500
AGNews En-Basic 270/500
AGNews En-Basic 271/500
AGNews En-Basic 272/500
AGNews En-Basic 273/500
AGNews En-Basic 274/500
AGNews En-Basic 275/500
AGNews En-Basic 276/500
AGNews En-Basic 277/500
AGNews En-Basic 278/500
AGNews En-Basic 279/500
AGNews En-Basic 280/500
AGNews En-Basic 281/500
AGNews En-Basic 282/500
AGNews En-Basic 283/500
AGNews En-Basic 284/500
AGNews En-Basic 285/500
AGNews En-Basic 286/500
AGNews En-Basic 287/500
AGNews En-Basic 288/500
AGNews En-Basic 289/500
AGNews En-Basic 290/500
AGNews En-Basic 291/500
AGNews En-Basic 292/500
AGNews En-Basic 293/500
AGNews En-Basic 294/500
AGNews En-Basic 295/500
AGNews En-Basic 296/500
AGNews En-Basic 297/500
AGNews En-Basic 298/500
AGNews En-Basic 299/500
AGNews En-Basic 300/500
AGNews En-Basic 301/500
AGNews En-Basic 302/500
AGNews En-Basic 303/500
AGNews En-Basic 304/500
AGNews En-Basic 305/500
AGNews En-Basic 306/500
AGNews En-Basic 307/500
AGNews En-Basic 308/500
AGNews En-Basic 309/500
AGNews En-Basic 310/500
AGNews En-Basic 311/500
AGNews En-Basic 312/500
AGNews En-Basic 313/500
AGNews En-Basic 314/500
AGNews En-Basic 315/500
AGNews En-Basic 316/500
AGNews En-Basic 317/500
AGNews En-Basic 318/500
AGNews En-Basic 319/500
AGNews En-Basic 320/500
AGNews En-Basic 321/500
AGNews En-Basic 322/500
AGNews En-Basic 323/500
AGNews En-Basic 324/500
AGNews En-Basic 325/500
AGNews En-Basic 326/500
AGNews En-Basic 327/500
AGNews En-Basic 328/500
AGNews En-Basic 329/500
AGNews En-Basic 330/500
AGNews En-Basic 331/500
AGNews En-Basic 332/500
AGNews En-Basic 333/500
AGNews En-Basic 334/500
AGNews En-Basic 335/500
AGNews En-Basic 336/500
AGNews En-Basic 337/500
AGNews En-Basic 338/500
AGNews En-Basic 339/500
AGNews En-Basic 340/500
AGNews En-Basic 341/500
AGNews En-Basic 342/500
AGNews En-Basic 343/500
AGNews En-Basic 344/500
AGNews En-Basic 345/500
AGNews En-Basic 346/500

AGNews En-Basic 347/500
AGNews En-Basic 348/500
AGNews En-Basic 349/500
AGNews En-Basic 350/500
AGNews En-Basic 351/500
AGNews En-Basic 352/500
AGNews En-Basic 353/500
AGNews En-Basic 354/500
AGNews En-Basic 355/500
AGNews En-Basic 356/500
AGNews En-Basic 357/500
AGNews En-Basic 358/500
AGNews En-Basic 359/500
AGNews En-Basic 360/500
AGNews En-Basic 361/500
AGNews En-Basic 362/500
AGNews En-Basic 363/500
AGNews En-Basic 364/500
AGNews En-Basic 365/500
AGNews En-Basic 366/500
AGNews En-Basic 367/500
AGNews En-Basic 368/500
AGNews En-Basic 369/500
AGNews En-Basic 370/500
AGNews En-Basic 371/500
AGNews En-Basic 372/500
AGNews En-Basic 373/500
AGNews En-Basic 374/500
AGNews En-Basic 375/500
AGNews En-Basic 376/500
AGNews En-Basic 377/500
AGNews En-Basic 378/500
AGNews En-Basic 379/500
AGNews En-Basic 380/500
AGNews En-Basic 381/500
AGNews En-Basic 382/500
AGNews En-Basic 383/500
AGNews En-Basic 384/500
AGNews En-Basic 385/500
AGNews En-Basic 386/500
AGNews En-Basic 387/500
AGNews En-Basic 388/500
AGNews En-Basic 389/500
AGNews En-Basic 390/500
AGNews En-Basic 391/500
AGNews En-Basic 392/500
AGNews En-Basic 393/500
AGNews En-Basic 394/500
AGNews En-Basic 395/500
AGNews En-Basic 396/500
AGNews En-Basic 397/500
AGNews En-Basic 398/500
AGNews En-Basic 399/500
AGNews En-Basic 400/500
AGNews En-Basic 401/500
AGNews En-Basic 402/500
AGNews En-Basic 403/500
AGNews En-Basic 404/500
AGNews En-Basic 405/500
AGNews En-Basic 406/500
AGNews En-Basic 407/500
AGNews En-Basic 408/500
AGNews En-Basic 409/500
AGNews En-Basic 410/500
AGNews En-Basic 411/500
AGNews En-Basic 412/500
AGNews En-Basic 413/500
AGNews En-Basic 414/500
AGNews En-Basic 415/500
AGNews En-Basic 416/500
AGNews En-Basic 417/500
AGNews En-Basic 418/500
AGNews En-Basic 419/500
AGNews En-Basic 420/500
AGNews En-Basic 421/500
AGNews En-Basic 422/500
AGNews En-Basic 423/500
AGNews En-Basic 424/500
AGNews En-Basic 425/500
AGNews En-Basic 426/500
AGNews En-Basic 427/500
AGNews En-Basic 428/500
AGNews En-Basic 429/500
AGNews En-Basic 430/500
AGNews En-Basic 431/500
AGNews En-Basic 432/500
AGNews En-Basic 433/500
AGNews En-Basic 434/500
AGNews En-Basic 435/500
AGNews En-Basic 436/500
AGNews En-Basic 437/500
AGNews En-Basic 438/500
AGNews En-Basic 439/500
AGNews En-Basic 440/500
AGNews En-Basic 441/500
AGNews En-Basic 442/500
AGNews En-Basic 443/500
AGNews En-Basic 444/500
AGNews En-Basic 445/500
AGNews En-Basic 446/500
AGNews En-Basic 447/500
AGNews En-Basic 448/500
AGNews En-Basic 449/500
AGNews En-Basic 450/500
AGNews En-Basic 451/500
AGNews En-Basic 452/500
AGNews En-Basic 453/500
AGNews En-Basic 454/500
AGNews En-Basic 455/500
AGNews En-Basic 456/500
AGNews En-Basic 457/500
AGNews En-Basic 458/500
AGNews En-Basic 459/500
AGNews En-Basic 460/500
AGNews En-Basic 461/500
AGNews En-Basic 462/500
AGNews En-Basic 463/500
AGNews En-Basic 464/500
AGNews En-Basic 465/500
AGNews En-Basic 466/500
AGNews En-Basic 467/500
AGNews En-Basic 468/500
AGNews En-Basic 469/500
AGNews En-Basic 470/500
AGNews En-Basic 471/500
AGNews En-Basic 472/500
AGNews En-Basic 473/500
AGNews En-Basic 474/500
AGNews En-Basic 475/500
AGNews En-Basic 476/500
AGNews En-Basic 477/500
AGNews En-Basic 478/500
AGNews En-Basic 479/500
AGNews En-Basic 480/500
AGNews En-Basic 481/500
AGNews En-Basic 482/500
AGNews En-Basic 483/500
AGNews En-Basic 484/500
AGNews En-Basic 485/500
AGNews En-Basic 486/500
AGNews En-Basic 487/500
AGNews En-Basic 488/500
AGNews En-Basic 489/500
AGNews En-Basic 490/500
AGNews En-Basic 491/500
AGNews En-Basic 492/500
AGNews En-Basic 493/500
AGNews En-Basic 494/500
AGNews En-Basic 495/500
AGNews En-Basic 496/500
AGNews En-Basic 497/500
AGNews En-Basic 498/500
AGNews En-Basic 499/500
AGNews En-Basic 500/500
English En-Basic finished

In [7]:
from sklearn.metrics import accuracy_score, classification_report

df_eval = pd.read_csv("agnews_en_basic_final.csv")

print("Accuracy:", accuracy_score(df_eval["label_name"], df_eval["pred_en_basic"]))
print(classification_report(df_eval["label_name"], df_eval["pred_en_basic"]))

Accuracy: 0.886
              precision    recall  f1-score   support

    Business       0.76      0.93      0.83       124
    Sci/Tech       0.95      0.76      0.84       139
      Sports       0.97      0.99      0.98       116
       World       0.91      0.88      0.90       121

    accuracy                           0.89       500
   macro avg       0.90      0.89      0.89       500
weighted avg       0.90      0.89      0.89       500

In [8]:
import pandas as pd

df = pd.read_csv("ag_news_kz_500.csv")
print(df.columns)

Index(['text', 'label', 'text_kz'], dtype='object')

In [9]:
label_map = {
    0: "World",
    1: "Sports",
    2: "Business",
    3: "Sci/Tech"
}

df["label_name"] = df["label"].map(label_map)

In [10]:
def classify_agnews_native_basic(text_kz: str) -> str:
    prompt = f"""Сен жаңалық мәтінінің тақырыбын анықтайтын сарапшысың.

Төмендегі жаңалық мәтінін 4 санаттың біріне жатқыз:
World, Sports, Business, Sci/Tech

Тек бір санат атауымен жауап бер.
Жауапқа түсіндірме қоспа.

Жаңалық мәтіні:
{text_kz}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    output = response.choices[0].message.content.strip()
    output_lower = output.lower()

    if "world" in output_lower:
        return "World"
    elif "sports" in output_lower:
        return "Sports"
    elif "business" in output_lower:
        return "Business"
    elif "sci" in output_lower or "tech" in output_lower:
        return "Sci/Tech"
    else:
        return output

In [11]:
for i in range(5):
    pred = classify_agnews_native_basic(df.loc[i, "text_kz"])
    print(i, "pred:", pred, "| true:", df.loc[i, "label_name"])
    time.sleep(0.3)

0 pred: Sports | true: Sports
1 pred: World | true: World
2 pred: Business | true: Sci/Tech
3 pred: Sci/Tech | true: Sci/Tech
4 pred: Business | true: Sci/Tech

In [12]:
if "pred_native_basic" not in df.columns:
    df["pred_native_basic"] = ""

for i in range(len(df)):
    if isinstance(df.loc[i, "pred_native_basic"], str) and df.loc[i, "pred_native_basic"].strip():
        continue

    print(f"AGNews Native-Basic {i+1}/{len(df)}")

    df.loc[i, "pred_native_basic"] = classify_agnews_native_basic(df.loc[i, "text_kz"])

    if (i + 1) % 25 == 0:
        df.to_csv("agnews_native_basic_progress.csv", index=False)

    time.sleep(0.3)

df.to_csv("agnews_native_basic_final.csv", index=False)
print("Kazakh Native-Basic finished")

AGNews Native-Basic 1/500
AGNews Native-Basic 2/500
AGNews Native-Basic 3/500
AGNews Native-Basic 4/500
AGNews Native-Basic 5/500
AGNews Native-Basic 6/500
AGNews Native-Basic 7/500
AGNews Native-Basic 8/500
AGNews Native-Basic 9/500
AGNews Native-Basic 10/500
AGNews Native-Basic 11/500
AGNews Native-Basic 12/500
AGNews Native-Basic 13/500
AGNews Native-Basic 14/500
AGNews Native-Basic 15/500
AGNews Native-Basic 16/500
AGNews Native-Basic 17/500
AGNews Native-Basic 18/500
AGNews Native-Basic 19/500
AGNews Native-Basic 20/500
AGNews Native-Basic 21/500
AGNews Native-Basic 22/500
AGNews Native-Basic 23/500
AGNews Native-Basic 24/500
AGNews Native-Basic 25/500
AGNews Native-Basic 26/500
AGNews Native-Basic 27/500
AGNews Native-Basic 28/500
AGNews Native-Basic 29/500
AGNews Native-Basic 30/500
AGNews Native-Basic 31/500
AGNews Native-Basic 32/500
AGNews Native-Basic 33/500
AGNews Native-Basic 34/500
AGNews Native-Basic 35/500
AGNews Native-Basic 36/500
AGNews Native-Basic 37/500
AGNews Native-Basic 38/500
AGNews Native-Basic 39/500
AGNews Native-Basic 40/500
AGNews Native-Basic 41/500
AGNews Native-Basic 42/500
AGNews Native-Basic 43/500
AGNews Native-Basic 44/500
AGNews Native-Basic 45/500
AGNews Native-Basic 46/500
AGNews Native-Basic 47/500
AGNews Native-Basic 48/500
AGNews Native-Basic 49/500
AGNews Native-Basic 50/500
AGNews Native-Basic 51/500
AGNews Native-Basic 52/500
AGNews Native-Basic 53/500
AGNews Native-Basic 54/500
AGNews Native-Basic 55/500
AGNews Native-Basic 56/500
AGNews Native-Basic 57/500
AGNews Native-Basic 58/500
AGNews Native-Basic 59/500
AGNews Native-Basic 60/500
AGNews Native-Basic 61/500
AGNews Native-Basic 62/500
AGNews Native-Basic 63/500
AGNews Native-Basic 64/500
AGNews Native-Basic 65/500
AGNews Native-Basic 66/500
AGNews Native-Basic 67/500
AGNews Native-Basic 68/500
AGNews Native-Basic 69/500
AGNews Native-Basic 70/500
AGNews Native-Basic 71/500
AGNews Native-Basic 72/500
AGNews Native-Basic 73/500
AGNews Native-Basic 74/500
AGNews Native-Basic 75/500
AGNews Native-Basic 76/500
AGNews Native-Basic 77/500
AGNews Native-Basic 78/500
AGNews Native-Basic 79/500
AGNews Native-Basic 80/500
AGNews Native-Basic 81/500
AGNews Native-Basic 82/500
AGNews Native-Basic 83/500
AGNews Native-Basic 84/500
AGNews Native-Basic 85/500
AGNews Native-Basic 86/500
AGNews Native-Basic 87/500
AGNews Native-Basic 88/500
AGNews Native-Basic 89/500
AGNews Native-Basic 90/500
AGNews Native-Basic 91/500
AGNews Native-Basic 92/500
AGNews Native-Basic 93/500
AGNews Native-Basic 94/500
AGNews Native-Basic 95/500
AGNews Native-Basic 96/500
AGNews Native-Basic 97/500
AGNews Native-Basic 98/500
AGNews Native-Basic 99/500
AGNews Native-Basic 100/500
AGNews Native-Basic 101/500
AGNews Native-Basic 102/500
AGNews Native-Basic 103/500
AGNews Native-Basic 104/500
AGNews Native-Basic 105/500
AGNews Native-Basic 106/500
AGNews Native-Basic 107/500
AGNews Native-Basic 108/500
AGNews Native-Basic 109/500
AGNews Native-Basic 110/500
AGNews Native-Basic 111/500
AGNews Native-Basic 112/500
AGNews Native-Basic 113/500
AGNews Native-Basic 114/500
AGNews Native-Basic 115/500
AGNews Native-Basic 116/500
AGNews Native-Basic 117/500
AGNews Native-Basic 118/500
AGNews Native-Basic 119/500
AGNews Native-Basic 120/500
AGNews Native-Basic 121/500
AGNews Native-Basic 122/500
AGNews Native-Basic 123/500
AGNews Native-Basic 124/500
AGNews Native-Basic 125/500
AGNews Native-Basic 126/500
AGNews Native-Basic 127/500
AGNews Native-Basic 128/500
AGNews Native-Basic 129/500
AGNews Native-Basic 130/500
AGNews Native-Basic 131/500
AGNews Native-Basic 132/500
AGNews Native-Basic 133/500
AGNews Native-Basic 134/500
AGNews Native-Basic 135/500
AGNews Native-Basic 136/500
AGNews Native-Basic 137/500
AGNews Native-Basic 138/500
AGNews Native-Basic 139/500
AGNews Native-Basic 140/500
AGNews Native-Basic 141/500
AGNews Native-Basic 142/500
AGNews Native-Basic 143/500
AGNews Native-Basic 144/500
AGNews Native-Basic 145/500
AGNews Native-Basic 146/500
AGNews Native-Basic 147/500
AGNews Native-Basic 148/500
AGNews Native-Basic 149/500
AGNews Native-Basic 150/500
AGNews Native-Basic 151/500
AGNews Native-Basic 152/500
AGNews Native-Basic 153/500
AGNews Native-Basic 154/500
AGNews Native-Basic 155/500
AGNews Native-Basic 156/500
AGNews Native-Basic 157/500
AGNews Native-Basic 158/500
AGNews Native-Basic 159/500
AGNews Native-Basic 160/500
AGNews Native-Basic 161/500
AGNews Native-Basic 162/500
AGNews Native-Basic 163/500
AGNews Native-Basic 164/500
AGNews Native-Basic 165/500
AGNews Native-Basic 166/500
AGNews Native-Basic 167/500
AGNews Native-Basic 168/500
AGNews Native-Basic 169/500
AGNews Native-Basic 170/500
AGNews Native-Basic 171/500
AGNews Native-Basic 172/500
AGNews Native-Basic 173/500
AGNews Native-Basic 174/500
AGNews Native-Basic 175/500
AGNews Native-Basic 176/500
AGNews Native-Basic 177/500
AGNews Native-Basic 178/500
AGNews Native-Basic 179/500
AGNews Native-Basic 180/500
AGNews Native-Basic 181/500
AGNews Native-Basic 182/500
AGNews Native-Basic 183/500
AGNews Native-Basic 184/500
AGNews Native-Basic 185/500
AGNews Native-Basic 186/500
AGNews Native-Basic 187/500
AGNews Native-Basic 188/500
AGNews Native-Basic 189/500
AGNews Native-Basic 190/500
AGNews Native-Basic 191/500
AGNews Native-Basic 192/500
AGNews Native-Basic 193/500
AGNews Native-Basic 194/500
AGNews Native-Basic 195/500
AGNews Native-Basic 196/500
AGNews Native-Basic 197/500
AGNews Native-Basic 198/500
AGNews Native-Basic 199/500
AGNews Native-Basic 200/500
AGNews Native-Basic 201/500
AGNews Native-Basic 202/500
AGNews Native-Basic 203/500
AGNews Native-Basic 204/500
AGNews Native-Basic 205/500
AGNews Native-Basic 206/500
AGNews Native-Basic 207/500
AGNews Native-Basic 208/500
AGNews Native-Basic 209/500
AGNews Native-Basic 210/500
AGNews Native-Basic 211/500
AGNews Native-Basic 212/500
AGNews Native-Basic 213/500
AGNews Native-Basic 214/500
AGNews Native-Basic 215/500
AGNews Native-Basic 216/500
AGNews Native-Basic 217/500
AGNews Native-Basic 218/500
AGNews Native-Basic 219/500
AGNews Native-Basic 220/500
AGNews Native-Basic 221/500
AGNews Native-Basic 222/500
AGNews Native-Basic 223/500
AGNews Native-Basic 224/500
AGNews Native-Basic 225/500
AGNews Native-Basic 226/500
AGNews Native-Basic 227/500
AGNews Native-Basic 228/500
AGNews Native-Basic 229/500
AGNews Native-Basic 230/500
AGNews Native-Basic 231/500
AGNews Native-Basic 232/500
AGNews Native-Basic 233/500
AGNews Native-Basic 234/500
AGNews Native-Basic 235/500
AGNews Native-Basic 236/500
AGNews Native-Basic 237/500
AGNews Native-Basic 238/500
AGNews Native-Basic 239/500
AGNews Native-Basic 240/500
AGNews Native-Basic 241/500
AGNews Native-Basic 242/500
AGNews Native-Basic 243/500
AGNews Native-Basic 244/500
AGNews Native-Basic 245/500
AGNews Native-Basic 246/500
AGNews Native-Basic 247/500
AGNews Native-Basic 248/500
AGNews Native-Basic 249/500
AGNews Native-Basic 250/500
AGNews Native-Basic 251/500
AGNews Native-Basic 252/500
AGNews Native-Basic 253/500
AGNews Native-Basic 254/500
AGNews Native-Basic 255/500
AGNews Native-Basic 256/500
AGNews Native-Basic 257/500
AGNews Native-Basic 258/500
AGNews Native-Basic 259/500
AGNews Native-Basic 260/500
AGNews Native-Basic 261/500
AGNews Native-Basic 262/500
AGNews Native-Basic 263/500
AGNews Native-Basic 264/500
AGNews Native-Basic 265/500
AGNews Native-Basic 266/500
AGNews Native-Basic 267/500
AGNews Native-Basic 268/500
AGNews Native-Basic 269/500
AGNews Native-Basic 270/500
AGNews Native-Basic 271/500
AGNews Native-Basic 272/500
AGNews Native-Basic 273/500
AGNews Native-Basic 274/500
AGNews Native-Basic 275/500
AGNews Native-Basic 276/500
AGNews Native-Basic 277/500
AGNews Native-Basic 278/500
AGNews Native-Basic 279/500
AGNews Native-Basic 280/500
AGNews Native-Basic 281/500
AGNews Native-Basic 282/500
AGNews Native-Basic 283/500
AGNews Native-Basic 284/500
AGNews Native-Basic 285/500
AGNews Native-Basic 286/500
AGNews Native-Basic 287/500
AGNews Native-Basic 288/500
AGNews Native-Basic 289/500
AGNews Native-Basic 290/500
AGNews Native-Basic 291/500
AGNews Native-Basic 292/500
AGNews Native-Basic 293/500
AGNews Native-Basic 294/500
AGNews Native-Basic 295/500
AGNews Native-Basic 296/500
AGNews Native-Basic 297/500

AGNews Native-Basic 298/500
AGNews Native-Basic 299/500
AGNews Native-Basic 300/500
AGNews Native-Basic 301/500
AGNews Native-Basic 302/500
AGNews Native-Basic 303/500
AGNews Native-Basic 304/500
AGNews Native-Basic 305/500
AGNews Native-Basic 306/500
AGNews Native-Basic 307/500
AGNews Native-Basic 308/500
AGNews Native-Basic 309/500
AGNews Native-Basic 310/500
AGNews Native-Basic 311/500
AGNews Native-Basic 312/500
AGNews Native-Basic 313/500
AGNews Native-Basic 314/500
AGNews Native-Basic 315/500
AGNews Native-Basic 316/500
AGNews Native-Basic 317/500
AGNews Native-Basic 318/500
AGNews Native-Basic 319/500
AGNews Native-Basic 320/500
AGNews Native-Basic 321/500
AGNews Native-Basic 322/500
AGNews Native-Basic 323/500
AGNews Native-Basic 324/500
AGNews Native-Basic 325/500
AGNews Native-Basic 326/500
AGNews Native-Basic 327/500
AGNews Native-Basic 328/500
AGNews Native-Basic 329/500
AGNews Native-Basic 330/500
AGNews Native-Basic 331/500
AGNews Native-Basic 332/500
AGNews Native-Basic 333/500
AGNews Native-Basic 334/500
AGNews Native-Basic 335/500
AGNews Native-Basic 336/500
AGNews Native-Basic 337/500
AGNews Native-Basic 338/500
AGNews Native-Basic 339/500
AGNews Native-Basic 340/500
AGNews Native-Basic 341/500
AGNews Native-Basic 342/500
AGNews Native-Basic 343/500
AGNews Native-Basic 344/500
AGNews Native-Basic 345/500
AGNews Native-Basic 346/500
AGNews Native-Basic 347/500
AGNews Native-Basic 348/500
AGNews Native-Basic 349/500
AGNews Native-Basic 350/500
AGNews Native-Basic 351/500
AGNews Native-Basic 352/500
AGNews Native-Basic 353/500
AGNews Native-Basic 354/500
AGNews Native-Basic 355/500
AGNews Native-Basic 356/500
AGNews Native-Basic 357/500
AGNews Native-Basic 358/500
AGNews Native-Basic 359/500
AGNews Native-Basic 360/500
AGNews Native-Basic 361/500
AGNews Native-Basic 362/500
AGNews Native-Basic 363/500
AGNews Native-Basic 364/500
AGNews Native-Basic 365/500
AGNews Native-Basic 366/500
AGNews Native-Basic 367/500
AGNews Native-Basic 368/500
AGNews Native-Basic 369/500
AGNews Native-Basic 370/500
AGNews Native-Basic 371/500
AGNews Native-Basic 372/500
AGNews Native-Basic 373/500
AGNews Native-Basic 374/500
AGNews Native-Basic 375/500
AGNews Native-Basic 376/500
AGNews Native-Basic 377/500
AGNews Native-Basic 378/500
AGNews Native-Basic 379/500
AGNews Native-Basic 380/500
AGNews Native-Basic 381/500
AGNews Native-Basic 382/500
AGNews Native-Basic 383/500
AGNews Native-Basic 384/500
AGNews Native-Basic 385/500
AGNews Native-Basic 386/500
AGNews Native-Basic 387/500
AGNews Native-Basic 388/500
AGNews Native-Basic 389/500
AGNews Native-Basic 390/500
AGNews Native-Basic 391/500
AGNews Native-Basic 392/500
AGNews Native-Basic 393/500
AGNews Native-Basic 394/500
AGNews Native-Basic 395/500
AGNews Native-Basic 396/500
AGNews Native-Basic 397/500
AGNews Native-Basic 398/500
AGNews Native-Basic 399/500
AGNews Native-Basic 400/500
AGNews Native-Basic 401/500
AGNews Native-Basic 402/500
AGNews Native-Basic 403/500
AGNews Native-Basic 404/500
AGNews Native-Basic 405/500
AGNews Native-Basic 406/500
AGNews Native-Basic 407/500
AGNews Native-Basic 408/500
AGNews Native-Basic 409/500
AGNews Native-Basic 410/500
AGNews Native-Basic 411/500
AGNews Native-Basic 412/500
AGNews Native-Basic 413/500
AGNews Native-Basic 414/500
AGNews Native-Basic 415/500
AGNews Native-Basic 416/500
AGNews Native-Basic 417/500
AGNews Native-Basic 418/500
AGNews Native-Basic 419/500
AGNews Native-Basic 420/500
AGNews Native-Basic 421/500
AGNews Native-Basic 422/500
AGNews Native-Basic 423/500
AGNews Native-Basic 424/500
AGNews Native-Basic 425/500
AGNews Native-Basic 426/500
AGNews Native-Basic 427/500
AGNews Native-Basic 428/500
AGNews Native-Basic 429/500
AGNews Native-Basic 430/500
AGNews Native-Basic 431/500
AGNews Native-Basic 432/500
AGNews Native-Basic 433/500
AGNews Native-Basic 434/500
AGNews Native-Basic 435/500
AGNews Native-Basic 436/500
AGNews Native-Basic 437/500
AGNews Native-Basic 438/500
AGNews Native-Basic 439/500
AGNews Native-Basic 440/500
AGNews Native-Basic 441/500
AGNews Native-Basic 442/500
AGNews Native-Basic 443/500
AGNews Native-Basic 444/500
AGNews Native-Basic 445/500
AGNews Native-Basic 446/500
AGNews Native-Basic 447/500
AGNews Native-Basic 448/500
AGNews Native-Basic 449/500
AGNews Native-Basic 450/500
AGNews Native-Basic 451/500
AGNews Native-Basic 452/500
AGNews Native-Basic 453/500
AGNews Native-Basic 454/500
AGNews Native-Basic 455/500
AGNews Native-Basic 456/500
AGNews Native-Basic 457/500
AGNews Native-Basic 458/500
AGNews Native-Basic 459/500
AGNews Native-Basic 460/500
AGNews Native-Basic 461/500
AGNews Native-Basic 462/500
AGNews Native-Basic 463/500
AGNews Native-Basic 464/500
AGNews Native-Basic 465/500
AGNews Native-Basic 466/500
AGNews Native-Basic 467/500
AGNews Native-Basic 468/500
AGNews Native-Basic 469/500
AGNews Native-Basic 470/500
AGNews Native-Basic 471/500
AGNews Native-Basic 472/500
AGNews Native-Basic 473/500
AGNews Native-Basic 474/500
AGNews Native-Basic 475/500
AGNews Native-Basic 476/500
AGNews Native-Basic 477/500
AGNews Native-Basic 478/500
AGNews Native-Basic 479/500
AGNews Native-Basic 480/500
AGNews Native-Basic 481/500
AGNews Native-Basic 482/500
AGNews Native-Basic 483/500
AGNews Native-Basic 484/500
AGNews Native-Basic 485/500
AGNews Native-Basic 486/500
AGNews Native-Basic 487/500
AGNews Native-Basic 488/500
AGNews Native-Basic 489/500
AGNews Native-Basic 490/500
AGNews Native-Basic 491/500
AGNews Native-Basic 492/500
AGNews Native-Basic 493/500
AGNews Native-Basic 494/500
AGNews Native-Basic 495/500
AGNews Native-Basic 496/500
AGNews Native-Basic 497/500
AGNews Native-Basic 498/500
AGNews Native-Basic 499/500
AGNews Native-Basic 500/500
Kazakh Native-Basic finished

In [13]:
from sklearn.metrics import accuracy_score, classification_report

df_eval = pd.read_csv("agnews_native_basic_final.csv")

print("Accuracy:", accuracy_score(df_eval["label_name"], df_eval["pred_native_basic"]))
print(classification_report(df_eval["label_name"], df_eval["pred_native_basic"]))

Accuracy: 0.87
              precision    recall  f1-score   support

    Business       0.72      0.93      0.81       124
    Sci/Tech       0.94      0.71      0.81       139
      Sports       0.97      0.99      0.98       116
       World       0.91      0.88      0.89       121

    accuracy                           0.87       500
   macro avg       0.88      0.88      0.87       500
weighted avg       0.88      0.87      0.87       500

In [14]:
def classify_agnews_en_kz(text_kz: str) -> str:
    prompt = f"""You are a news topic classifier.

Classify the following news text into one of these categories:
World, Sports, Business, Sci/Tech

Respond with only one category name.
Do not explain your answer.

News text:
{text_kz}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    output = response.choices[0].message.content.strip().lower()

    if "world" in output:
        return "World"
    elif "sports" in output:
        return "Sports"
    elif "business" in output:
        return "Business"
    elif "sci" in output or "tech" in output:
        return "Sci/Tech"
    else:
        return output

In [15]:
for i in range(5):
    pred = classify_agnews_en_kz(df.loc[i, "text_kz"])
    print(i, "pred:", pred, "| true:", df.loc[i, "label_name"])
    time.sleep(0.3)

0 pred: Sports | true: Sports
1 pred: World | true: World
2 pred: Business | true: Sci/Tech
3 pred: Sci/Tech | true: Sci/Tech
4 pred: Business | true: Sci/Tech

In [16]:
if "pred_en_kz" not in df.columns:
    df["pred_en_kz"] = ""

for i in range(len(df)):
    if isinstance(df.loc[i, "pred_en_kz"], str) and df.loc[i, "pred_en_kz"].strip():
        continue

    print(f"AGNews EN prompt + KZ input {i+1}/{len(df)}")

    df.loc[i, "pred_en_kz"] = classify_agnews_en_kz(df.loc[i, "text_kz"])

    if (i + 1) % 25 == 0:
        df.to_csv("agnews_en_kz_progress.csv", index=False)

    time.sleep(0.3)

df.to_csv("agnews_en_kz_final.csv", index=False)
print("Finished EN prompt + KZ input")

AGNews EN prompt + KZ input 1/500
AGNews EN prompt + KZ input 2/500
AGNews EN prompt + KZ input 3/500
AGNews EN prompt + KZ input 4/500
AGNews EN prompt + KZ input 5/500
AGNews EN prompt + KZ input 6/500
AGNews EN prompt + KZ input 7/500
AGNews EN prompt + KZ input 8/500
AGNews EN prompt + KZ input 9/500
AGNews EN prompt + KZ input 10/500
AGNews EN prompt + KZ input 11/500
AGNews EN prompt + KZ input 12/500
AGNews EN prompt + KZ input 13/500
AGNews EN prompt + KZ input 14/500
AGNews EN prompt + KZ input 15/500
AGNews EN prompt + KZ input 16/500
AGNews EN prompt + KZ input 17/500
AGNews EN prompt + KZ input 18/500
AGNews EN prompt + KZ input 19/500
AGNews EN prompt + KZ input 20/500
AGNews EN prompt + KZ input 21/500
AGNews EN prompt + KZ input 22/500
AGNews EN prompt + KZ input 23/500
AGNews EN prompt + KZ input 24/500
AGNews EN prompt + KZ input 25/500
AGNews EN prompt + KZ input 26/500
AGNews EN prompt + KZ input 27/500
AGNews EN prompt + KZ input 28/500
AGNews EN prompt + KZ input 29/500
AGNews EN prompt + KZ input 30/500
AGNews EN prompt + KZ input 31/500
AGNews EN prompt + KZ input 32/500
AGNews EN prompt + KZ input 33/500
AGNews EN prompt + KZ input 34/500
AGNews EN prompt + KZ input 35/500
AGNews EN prompt + KZ input 36/500
AGNews EN prompt + KZ input 37/500
AGNews EN prompt + KZ input 38/500
AGNews EN prompt + KZ input 39/500
AGNews EN prompt + KZ input 40/500
AGNews EN prompt + KZ input 41/500
AGNews EN prompt + KZ input 42/500
AGNews EN prompt + KZ input 43/500
AGNews EN prompt + KZ input 44/500
AGNews EN prompt + KZ input 45/500
AGNews EN prompt + KZ input 46/500
AGNews EN prompt + KZ input 47/500
AGNews EN prompt + KZ input 48/500
AGNews EN prompt + KZ input 49/500
AGNews EN prompt + KZ input 50/500
AGNews EN prompt + KZ input 51/500
AGNews EN prompt + KZ input 52/500
AGNews EN prompt + KZ input 53/500
AGNews EN prompt + KZ input 54/500
AGNews EN prompt + KZ input 55/500
AGNews EN prompt + KZ input 56/500
AGNews EN prompt + KZ input 57/500
AGNews EN prompt + KZ input 58/500
AGNews EN prompt + KZ input 59/500
AGNews EN prompt + KZ input 60/500
AGNews EN prompt + KZ input 61/500
AGNews EN prompt + KZ input 62/500
AGNews EN prompt + KZ input 63/500
AGNews EN prompt + KZ input 64/500
AGNews EN prompt + KZ input 65/500
AGNews EN prompt + KZ input 66/500
AGNews EN prompt + KZ input 67/500
AGNews EN prompt + KZ input 68/500
AGNews EN prompt + KZ input 69/500
AGNews EN prompt + KZ input 70/500
AGNews EN prompt + KZ input 71/500
AGNews EN prompt + KZ input 72/500
AGNews EN prompt + KZ input 73/500
AGNews EN prompt + KZ input 74/500
AGNews EN prompt + KZ input 75/500
AGNews EN prompt + KZ input 76/500
AGNews EN prompt + KZ input 77/500
AGNews EN prompt + KZ input 78/500
AGNews EN prompt + KZ input 79/500
AGNews EN prompt + KZ input 80/500
AGNews EN prompt + KZ input 81/500
AGNews EN prompt + KZ input 82/500
AGNews EN prompt + KZ input 83/500
AGNews EN prompt + KZ input 84/500
AGNews EN prompt + KZ input 85/500
AGNews EN prompt + KZ input 86/500
AGNews EN prompt + KZ input 87/500
AGNews EN prompt + KZ input 88/500
AGNews EN prompt + KZ input 89/500
AGNews EN prompt + KZ input 90/500
AGNews EN prompt + KZ input 91/500
AGNews EN prompt + KZ input 92/500
AGNews EN prompt + KZ input 93/500
AGNews EN prompt + KZ input 94/500
AGNews EN prompt + KZ input 95/500
AGNews EN prompt + KZ input 96/500
AGNews EN prompt + KZ input 97/500
AGNews EN prompt + KZ input 98/500
AGNews EN prompt + KZ input 99/500
AGNews EN prompt + KZ input 100/500
AGNews EN prompt + KZ input 101/500
AGNews EN prompt + KZ input 102/500
AGNews EN prompt + KZ input 103/500
AGNews EN prompt + KZ input 104/500
AGNews EN prompt + KZ input 105/500
AGNews EN prompt + KZ input 106/500
AGNews EN prompt + KZ input 107/500
AGNews EN prompt + KZ input 108/500
AGNews EN prompt + KZ input 109/500
AGNews EN prompt + KZ input 110/500
AGNews EN prompt + KZ input 111/500
AGNews EN prompt + KZ input 112/500
AGNews EN prompt + KZ input 113/500
AGNews EN prompt + KZ input 114/500
AGNews EN prompt + KZ input 115/500
AGNews EN prompt + KZ input 116/500
AGNews EN prompt + KZ input 117/500
AGNews EN prompt + KZ input 118/500
AGNews EN prompt + KZ input 119/500
AGNews EN prompt + KZ input 120/500
AGNews EN prompt + KZ input 121/500
AGNews EN prompt + KZ input 122/500
AGNews EN prompt + KZ input 123/500
AGNews EN prompt + KZ input 124/500
AGNews EN prompt + KZ input 125/500
AGNews EN prompt + KZ input 126/500
AGNews EN prompt + KZ input 127/500
AGNews EN prompt + KZ input 128/500
AGNews EN prompt + KZ input 129/500
AGNews EN prompt + KZ input 130/500
AGNews EN prompt + KZ input 131/500
AGNews EN prompt + KZ input 132/500
AGNews EN prompt + KZ input 133/500
AGNews EN prompt + KZ input 134/500
AGNews EN prompt + KZ input 135/500
AGNews EN prompt + KZ input 136/500
AGNews EN prompt + KZ input 137/500
AGNews EN prompt + KZ input 138/500
AGNews EN prompt + KZ input 139/500
AGNews EN prompt + KZ input 140/500
AGNews EN prompt + KZ input 141/500
AGNews EN prompt + KZ input 142/500
AGNews EN prompt + KZ input 143/500
AGNews EN prompt + KZ input 144/500
AGNews EN prompt + KZ input 145/500
AGNews EN prompt + KZ input 146/500
AGNews EN prompt + KZ input 147/500
AGNews EN prompt + KZ input 148/500
AGNews EN prompt + KZ input 149/500
AGNews EN prompt + KZ input 150/500
AGNews EN prompt + KZ input 151/500
AGNews EN prompt + KZ input 152/500
AGNews EN prompt + KZ input 153/500
AGNews EN prompt + KZ input 154/500
AGNews EN prompt + KZ input 155/500
AGNews EN prompt + KZ input 156/500
AGNews EN prompt + KZ input 157/500
AGNews EN prompt + KZ input 158/500
AGNews EN prompt + KZ input 159/500
AGNews EN prompt + KZ input 160/500
AGNews EN prompt + KZ input 161/500
AGNews EN prompt + KZ input 162/500
AGNews EN prompt + KZ input 163/500
AGNews EN prompt + KZ input 164/500
AGNews EN prompt + KZ input 165/500
AGNews EN prompt + KZ input 166/500
AGNews EN prompt + KZ input 167/500
AGNews EN prompt + KZ input 168/500
AGNews EN prompt + KZ input 169/500
AGNews EN prompt + KZ input 170/500
AGNews EN prompt + KZ input 171/500
AGNews EN prompt + KZ input 172/500
AGNews EN prompt + KZ input 173/500
AGNews EN prompt + KZ input 174/500
AGNews EN prompt + KZ input 175/500
AGNews EN prompt + KZ input 176/500
AGNews EN prompt + KZ input 177/500
AGNews EN prompt + KZ input 178/500
AGNews EN prompt + KZ input 179/500
AGNews EN prompt + KZ input 180/500
AGNews EN prompt + KZ input 181/500
AGNews EN prompt + KZ input 182/500
AGNews EN prompt + KZ input 183/500
AGNews EN prompt + KZ input 184/500
AGNews EN prompt + KZ input 185/500
AGNews EN prompt + KZ input 186/500
AGNews EN prompt + KZ input 187/500
AGNews EN prompt + KZ input 188/500
AGNews EN prompt + KZ input 189/500
AGNews EN prompt + KZ input 190/500
AGNews EN prompt + KZ input 191/500
AGNews EN prompt + KZ input 192/500
AGNews EN prompt + KZ input 193/500
AGNews EN prompt + KZ input 194/500
AGNews EN prompt + KZ input 195/500
AGNews EN prompt + KZ input 196/500
AGNews EN prompt + KZ input 197/500
AGNews EN prompt + KZ input 198/500
AGNews EN prompt + KZ input 199/500
AGNews EN prompt + KZ input 200/500
AGNews EN prompt + KZ input 201/500
AGNews EN prompt + KZ input 202/500
AGNews EN prompt + KZ input 203/500
AGNews EN prompt + KZ input 204/500
AGNews EN prompt + KZ input 205/500
AGNews EN prompt + KZ input 206/500
AGNews EN prompt + KZ input 207/500
AGNews EN prompt + KZ input 208/500
AGNews EN prompt + KZ input 209/500
AGNews EN prompt + KZ input 210/500
AGNews EN prompt + KZ input 211/500
AGNews EN prompt + KZ input 212/500
AGNews EN prompt + KZ input 213/500
AGNews EN prompt + KZ input 214/500
AGNews EN prompt + KZ input 215/500
AGNews EN prompt + KZ input 216/500
AGNews EN prompt + KZ input 217/500
AGNews EN prompt + KZ input 218/500
AGNews EN prompt + KZ input 219/500
AGNews EN prompt + KZ input 220/500
AGNews EN prompt + KZ input 221/500
AGNews EN prompt + KZ input 222/500
AGNews EN prompt + KZ input 223/500
AGNews EN prompt + KZ input 224/500
AGNews EN prompt + KZ input 225/500
AGNews EN prompt + KZ input 226/500
AGNews EN prompt + KZ input 227/500
AGNews EN prompt + KZ input 228/500
AGNews EN prompt + KZ input 229/500
AGNews EN prompt + KZ input 230/500
AGNews EN prompt + KZ input 231/500

AGNews EN prompt + KZ input 232/500
AGNews EN prompt + KZ input 233/500
AGNews EN prompt + KZ input 234/500
AGNews EN prompt + KZ input 235/500
AGNews EN prompt + KZ input 236/500
AGNews EN prompt + KZ input 237/500
AGNews EN prompt + KZ input 238/500
AGNews EN prompt + KZ input 239/500
AGNews EN prompt + KZ input 240/500
AGNews EN prompt + KZ input 241/500
AGNews EN prompt + KZ input 242/500
AGNews EN prompt + KZ input 243/500
AGNews EN prompt + KZ input 244/500
AGNews EN prompt + KZ input 245/500
AGNews EN prompt + KZ input 246/500
AGNews EN prompt + KZ input 247/500
AGNews EN prompt + KZ input 248/500
AGNews EN prompt + KZ input 249/500
AGNews EN prompt + KZ input 250/500
AGNews EN prompt + KZ input 251/500
AGNews EN prompt + KZ input 252/500
AGNews EN prompt + KZ input 253/500
AGNews EN prompt + KZ input 254/500
AGNews EN prompt + KZ input 255/500
AGNews EN prompt + KZ input 256/500
AGNews EN prompt + KZ input 257/500
AGNews EN prompt + KZ input 258/500
AGNews EN prompt + KZ input 259/500
AGNews EN prompt + KZ input 260/500
AGNews EN prompt + KZ input 261/500
AGNews EN prompt + KZ input 262/500
AGNews EN prompt + KZ input 263/500
AGNews EN prompt + KZ input 264/500
AGNews EN prompt + KZ input 265/500
AGNews EN prompt + KZ input 266/500
AGNews EN prompt + KZ input 267/500
AGNews EN prompt + KZ input 268/500
AGNews EN prompt + KZ input 269/500
AGNews EN prompt + KZ input 270/500
AGNews EN prompt + KZ input 271/500
AGNews EN prompt + KZ input 272/500
AGNews EN prompt + KZ input 273/500
AGNews EN prompt + KZ input 274/500
AGNews EN prompt + KZ input 275/500
AGNews EN prompt + KZ input 276/500
AGNews EN prompt + KZ input 277/500
AGNews EN prompt + KZ input 278/500
AGNews EN prompt + KZ input 279/500
AGNews EN prompt + KZ input 280/500
AGNews EN prompt + KZ input 281/500
AGNews EN prompt + KZ input 282/500
AGNews EN prompt + KZ input 283/500
AGNews EN prompt + KZ input 284/500
AGNews EN prompt + KZ input 285/500
AGNews EN prompt + KZ input 286/500
AGNews EN prompt + KZ input 287/500
AGNews EN prompt + KZ input 288/500
AGNews EN prompt + KZ input 289/500
AGNews EN prompt + KZ input 290/500
AGNews EN prompt + KZ input 291/500
AGNews EN prompt + KZ input 292/500
AGNews EN prompt + KZ input 293/500
AGNews EN prompt + KZ input 294/500
AGNews EN prompt + KZ input 295/500
AGNews EN prompt + KZ input 296/500
AGNews EN prompt + KZ input 297/500
AGNews EN prompt + KZ input 298/500
AGNews EN prompt + KZ input 299/500
AGNews EN prompt + KZ input 300/500
AGNews EN prompt + KZ input 301/500
AGNews EN prompt + KZ input 302/500
AGNews EN prompt + KZ input 303/500
AGNews EN prompt + KZ input 304/500
AGNews EN prompt + KZ input 305/500
AGNews EN prompt + KZ input 306/500
AGNews EN prompt + KZ input 307/500
AGNews EN prompt + KZ input 308/500
AGNews EN prompt + KZ input 309/500
AGNews EN prompt + KZ input 310/500
AGNews EN prompt + KZ input 311/500
AGNews EN prompt + KZ input 312/500
AGNews EN prompt + KZ input 313/500
AGNews EN prompt + KZ input 314/500
AGNews EN prompt + KZ input 315/500
AGNews EN prompt + KZ input 316/500
AGNews EN prompt + KZ input 317/500
AGNews EN prompt + KZ input 318/500
AGNews EN prompt + KZ input 319/500
AGNews EN prompt + KZ input 320/500
AGNews EN prompt + KZ input 321/500
AGNews EN prompt + KZ input 322/500
AGNews EN prompt + KZ input 323/500
AGNews EN prompt + KZ input 324/500
AGNews EN prompt + KZ input 325/500
AGNews EN prompt + KZ input 326/500
AGNews EN prompt + KZ input 327/500
AGNews EN prompt + KZ input 328/500
AGNews EN prompt + KZ input 329/500
AGNews EN prompt + KZ input 330/500
AGNews EN prompt + KZ input 331/500
AGNews EN prompt + KZ input 332/500
AGNews EN prompt + KZ input 333/500
AGNews EN prompt + KZ input 334/500
AGNews EN prompt + KZ input 335/500
AGNews EN prompt + KZ input 336/500
AGNews EN prompt + KZ input 337/500
AGNews EN prompt + KZ input 338/500
AGNews EN prompt + KZ input 339/500
AGNews EN prompt + KZ input 340/500
AGNews EN prompt + KZ input 341/500
AGNews EN prompt + KZ input 342/500
AGNews EN prompt + KZ input 343/500
AGNews EN prompt + KZ input 344/500
AGNews EN prompt + KZ input 345/500
AGNews EN prompt + KZ input 346/500
AGNews EN prompt + KZ input 347/500
AGNews EN prompt + KZ input 348/500
AGNews EN prompt + KZ input 349/500
AGNews EN prompt + KZ input 350/500
AGNews EN prompt + KZ input 351/500
AGNews EN prompt + KZ input 352/500
AGNews EN prompt + KZ input 353/500
AGNews EN prompt + KZ input 354/500
AGNews EN prompt + KZ input 355/500
AGNews EN prompt + KZ input 356/500
AGNews EN prompt + KZ input 357/500
AGNews EN prompt + KZ input 358/500
AGNews EN prompt + KZ input 359/500
AGNews EN prompt + KZ input 360/500
AGNews EN prompt + KZ input 361/500
AGNews EN prompt + KZ input 362/500
AGNews EN prompt + KZ input 363/500
AGNews EN prompt + KZ input 364/500
AGNews EN prompt + KZ input 365/500
AGNews EN prompt + KZ input 366/500
AGNews EN prompt + KZ input 367/500
AGNews EN prompt + KZ input 368/500
AGNews EN prompt + KZ input 369/500
AGNews EN prompt + KZ input 370/500
AGNews EN prompt + KZ input 371/500
AGNews EN prompt + KZ input 372/500
AGNews EN prompt + KZ input 373/500
AGNews EN prompt + KZ input 374/500
AGNews EN prompt + KZ input 375/500
AGNews EN prompt + KZ input 376/500
AGNews EN prompt + KZ input 377/500
AGNews EN prompt + KZ input 378/500
AGNews EN prompt + KZ input 379/500
AGNews EN prompt + KZ input 380/500
AGNews EN prompt + KZ input 381/500
AGNews EN prompt + KZ input 382/500
AGNews EN prompt + KZ input 383/500
AGNews EN prompt + KZ input 384/500
AGNews EN prompt + KZ input 385/500
AGNews EN prompt + KZ input 386/500
AGNews EN prompt + KZ input 387/500
AGNews EN prompt + KZ input 388/500
AGNews EN prompt + KZ input 389/500
AGNews EN prompt + KZ input 390/500
AGNews EN prompt + KZ input 391/500
AGNews EN prompt + KZ input 392/500
AGNews EN prompt + KZ input 393/500
AGNews EN prompt + KZ input 394/500
AGNews EN prompt + KZ input 395/500
AGNews EN prompt + KZ input 396/500
AGNews EN prompt + KZ input 397/500
AGNews EN prompt + KZ input 398/500
AGNews EN prompt + KZ input 399/500
AGNews EN prompt + KZ input 400/500
AGNews EN prompt + KZ input 401/500
AGNews EN prompt + KZ input 402/500
AGNews EN prompt + KZ input 403/500
AGNews EN prompt + KZ input 404/500
AGNews EN prompt + KZ input 405/500
AGNews EN prompt + KZ input 406/500
AGNews EN prompt + KZ input 407/500
AGNews EN prompt + KZ input 408/500
AGNews EN prompt + KZ input 409/500
AGNews EN prompt + KZ input 410/500
AGNews EN prompt + KZ input 411/500
AGNews EN prompt + KZ input 412/500
AGNews EN prompt + KZ input 413/500
AGNews EN prompt + KZ input 414/500
AGNews EN prompt + KZ input 415/500
AGNews EN prompt + KZ input 416/500
AGNews EN prompt + KZ input 417/500
AGNews EN prompt + KZ input 418/500
AGNews EN prompt + KZ input 419/500
AGNews EN prompt + KZ input 420/500
AGNews EN prompt + KZ input 421/500
AGNews EN prompt + KZ input 422/500
AGNews EN prompt + KZ input 423/500
AGNews EN prompt + KZ input 424/500
AGNews EN prompt + KZ input 425/500
AGNews EN prompt + KZ input 426/500
AGNews EN prompt + KZ input 427/500
AGNews EN prompt + KZ input 428/500
AGNews EN prompt + KZ input 429/500
AGNews EN prompt + KZ input 430/500
AGNews EN prompt + KZ input 431/500
AGNews EN prompt + KZ input 432/500
AGNews EN prompt + KZ input 433/500
AGNews EN prompt + KZ input 434/500
AGNews EN prompt + KZ input 435/500
AGNews EN prompt + KZ input 436/500
AGNews EN prompt + KZ input 437/500
AGNews EN prompt + KZ input 438/500
AGNews EN prompt + KZ input 439/500
AGNews EN prompt + KZ input 440/500
AGNews EN prompt + KZ input 441/500
AGNews EN prompt + KZ input 442/500
AGNews EN prompt + KZ input 443/500
AGNews EN prompt + KZ input 444/500
AGNews EN prompt + KZ input 445/500
AGNews EN prompt + KZ input 446/500
AGNews EN prompt + KZ input 447/500
AGNews EN prompt + KZ input 448/500
AGNews EN prompt + KZ input 449/500
AGNews EN prompt + KZ input 450/500
AGNews EN prompt + KZ input 451/500
AGNews EN prompt + KZ input 452/500
AGNews EN prompt + KZ input 453/500
AGNews EN prompt + KZ input 454/500
AGNews EN prompt + KZ input 455/500
AGNews EN prompt + KZ input 456/500
AGNews EN prompt + KZ input 457/500
AGNews EN prompt + KZ input 458/500
AGNews EN prompt + KZ input 459/500

AGNews EN prompt + KZ input 460/500
AGNews EN prompt + KZ input 461/500
AGNews EN prompt + KZ input 462/500
AGNews EN prompt + KZ input 463/500
AGNews EN prompt + KZ input 464/500
AGNews EN prompt + KZ input 465/500
AGNews EN prompt + KZ input 466/500
AGNews EN prompt + KZ input 467/500
AGNews EN prompt + KZ input 468/500
AGNews EN prompt + KZ input 469/500
AGNews EN prompt + KZ input 470/500
AGNews EN prompt + KZ input 471/500
AGNews EN prompt + KZ input 472/500
AGNews EN prompt + KZ input 473/500
AGNews EN prompt + KZ input 474/500
AGNews EN prompt + KZ input 475/500
AGNews EN prompt + KZ input 476/500
AGNews EN prompt + KZ input 477/500
AGNews EN prompt + KZ input 478/500
AGNews EN prompt + KZ input 479/500
AGNews EN prompt + KZ input 480/500
AGNews EN prompt + KZ input 481/500
AGNews EN prompt + KZ input 482/500
AGNews EN prompt + KZ input 483/500
AGNews EN prompt + KZ input 484/500
AGNews EN prompt + KZ input 485/500
AGNews EN prompt + KZ input 486/500
AGNews EN prompt + KZ input 487/500
AGNews EN prompt + KZ input 488/500
AGNews EN prompt + KZ input 489/500
AGNews EN prompt + KZ input 490/500
AGNews EN prompt + KZ input 491/500
AGNews EN prompt + KZ input 492/500
AGNews EN prompt + KZ input 493/500
AGNews EN prompt + KZ input 494/500
AGNews EN prompt + KZ input 495/500
AGNews EN prompt + KZ input 496/500
AGNews EN prompt + KZ input 497/500
AGNews EN prompt + KZ input 498/500
AGNews EN prompt + KZ input 499/500
AGNews EN prompt + KZ input 500/500
Finished EN prompt + KZ input

In [17]:
df_eval = pd.read_csv("agnews_en_kz_final.csv")

print("Accuracy:", accuracy_score(df_eval["label_name"], df_eval["pred_en_kz"]))
print(classification_report(df_eval["label_name"], df_eval["pred_en_kz"]))

Accuracy: 0.874
              precision    recall  f1-score   support

    Business       0.75      0.92      0.83       124
    Sci/Tech       0.94      0.72      0.82       139
      Sports       0.97      0.99      0.98       116
       World       0.88      0.89      0.89       121

    accuracy                           0.87       500
   macro avg       0.88      0.88      0.88       500
weighted avg       0.88      0.87      0.87       500

In [1]:
import pandas as pd

df = pd.read_csv("ag_news_kz_500.csv")
print(df.columns)

Index(['text', 'label', 'text_kz'], dtype='object')

In [2]:
df_small = df.sample(n=100, random_state=42).reset_index(drop=True)
df_small["pred_translate_en"] = ""

In [3]:
def classify_agnews_translate_en(text_kz: str) -> str:

    prompt = f"""You are a news topic classifier.

Step 1: Translate the following news text into English.
Step 2: Classify it into one of these categories:
World, Sports, Business, Sci/Tech

Respond with ONLY the final category name.
Do not show the translation.

Text:
{text_kz}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    output = response.choices[0].message.content.strip().lower()

    if "world" in output:
        return "World"
    elif "sports" in output:
        return "Sports"
    elif "business" in output:
        return "Business"
    elif "sci" in output or "tech" in output:
        return "Sci/Tech"
    else:
        return output

In [6]:
label_map = {
    0: "World",
    1: "Sports",
    2: "Business",
    3: "Sci/Tech"
}

df_small["label_name"] = df_small["label"].map(label_map)

In [7]:
for i in range(5):
    pred = classify_agnews_translate_en(df_small.loc[i, "text_kz"])
    print(i, pred, "|", df_small.loc[i, "label_name"])

0 Sports | Sports
1 Sci/Tech | Sci/Tech
2 Business | Business
3 Sports | Sports
4 World | World

In [8]:
import time

for i in range(len(df_small)):

    print(f"Translate-En {i+1}/100")

    df_small.loc[i, "pred_translate_en"] = classify_agnews_translate_en(
        df_small.loc[i, "text_kz"]
    )

    if (i+1) % 20 == 0:
        df_small.to_csv("agnews_translate_en_100_progress.csv", index=False)

    time.sleep(0.3)

df_small.to_csv("agnews_translate_en_100_final.csv", index=False)

print("Translate-En finished")

Translate-En 1/100
Translate-En 2/100
Translate-En 3/100
Translate-En 4/100
Translate-En 5/100
Translate-En 6/100
Translate-En 7/100
Translate-En 8/100
Translate-En 9/100
Translate-En 10/100
Translate-En 11/100
Translate-En 12/100
Translate-En 13/100
Translate-En 14/100
Translate-En 15/100
Translate-En 16/100
Translate-En 17/100
Translate-En 18/100
Translate-En 19/100
Translate-En 20/100
Translate-En 21/100
Translate-En 22/100
Translate-En 23/100
Translate-En 24/100
Translate-En 25/100
Translate-En 26/100
Translate-En 27/100
Translate-En 28/100
Translate-En 29/100
Translate-En 30/100
Translate-En 31/100
Translate-En 32/100
Translate-En 33/100
Translate-En 34/100
Translate-En 35/100
Translate-En 36/100
Translate-En 37/100
Translate-En 38/100
Translate-En 39/100
Translate-En 40/100
Translate-En 41/100
Translate-En 42/100
Translate-En 43/100
Translate-En 44/100
Translate-En 45/100
Translate-En 46/100
Translate-En 47/100
Translate-En 48/100
Translate-En 49/100
Translate-En 50/100
Translate-En 51/100
Translate-En 52/100
Translate-En 53/100
Translate-En 54/100
Translate-En 55/100
Translate-En 56/100
Translate-En 57/100
Translate-En 58/100
Translate-En 59/100
Translate-En 60/100
Translate-En 61/100
Translate-En 62/100
Translate-En 63/100
Translate-En 64/100
Translate-En 65/100
Translate-En 66/100
Translate-En 67/100
Translate-En 68/100
Translate-En 69/100
Translate-En 70/100
Translate-En 71/100
Translate-En 72/100
Translate-En 73/100
Translate-En 74/100
Translate-En 75/100
Translate-En 76/100
Translate-En 77/100
Translate-En 78/100
Translate-En 79/100
Translate-En 80/100
Translate-En 81/100
Translate-En 82/100
Translate-En 83/100
Translate-En 84/100
Translate-En 85/100
Translate-En 86/100
Translate-En 87/100
Translate-En 88/100
Translate-En 89/100
Translate-En 90/100
Translate-En 91/100
Translate-En 92/100
Translate-En 93/100
Translate-En 94/100
Translate-En 95/100
Translate-En 96/100
Translate-En 97/100
Translate-En 98/100
Translate-En 99/100
Translate-En 100/100
Translate-En finished

In [9]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(df_small["label_name"], df_small["pred_translate_en"]))
print(classification_report(df_small["label_name"], df_small["pred_translate_en"]))

Accuracy: 0.85
              precision    recall  f1-score   support

    Business       0.70      0.84      0.76        25
    Sci/Tech       0.95      0.70      0.81        30
      Sports       1.00      1.00      1.00        29
       World       0.74      0.88      0.80        16

    accuracy                           0.85       100
   macro avg       0.85      0.85      0.84       100
weighted avg       0.87      0.85      0.85       100