In [2]:
import pandas as pd
df = pd.read_csv("commonsenseqa_val_en_500.csv")
print(df.shape)
print(df.columns)
df.head(3)

(500, 4)
Index(['id', 'question', 'options', 'answer_key'], dtype='object')

,id,question,options,answer_key
0,c0d75f9fbf30aa3a612f16edb20d6b8d,The man took paperwork to other people to cons...,A) desk\nB) meeting\nC) office\nD) table\nE) work,B
1,c21ec5b367f409a0288d616f626555ae,"If a person is working a lot, what are they li...",A) much money\nB) own house\nC) creativity\nD)...,A
2,e6586bba9fe96d38792e6e6d4f2703dc,Where can you put a picture frame when it's no...,A) art show\nB) wall\nC) newspaper\nD) car\nE)...,E

In [3]:
import re

def parse_options(options_str: str) -> dict:
   
    opts = {}
    
    matches = re.findall(r"([ABCDE])\)\s*(.*?)(?=\n[ABCDE]\)|\Z)", options_str.strip(), flags=re.S)
    for letter, text in matches:
        opts[letter] = text.strip()
   
    if set(opts.keys()) != set(list("ABCDE")):
        raise ValueError(f"Options parsing failed. Got keys={opts.keys()} from:\n{options_str}")
    return opts

In [4]:
from openai import OpenAI

client = OpenAI(api_key=" ")

def csqa_en_basic_predict(question: str, options_str: str) -> str:
    choices = parse_options(options_str)

    prompt = f"""You are a commonsense reasoning expert.

Answer the following multiple-choice question.
Respond with only ONE letter: A, B, C, D, or E.

Question:
{question}

Choices:
A) {choices['A']}
B) {choices['B']}
C) {choices['C']}
D) {choices['D']}
E) {choices['E']}
"""
    resp = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role": "user", "content": prompt}],
    )
    out = resp.choices[0].message.content.strip().upper()
    m = re.search(r"\b([ABCDE])\b", out)
    return m.group(1) if m else out

In [5]:
for i in range(5):
    pred = csqa_en_basic_predict(df.loc[i, "question"], df.loc[i, "options"])
    print(i, "pred:", pred, "gold:", df.loc[i, "answer_key"])

0 pred: B gold: B
1 pred: A gold: A
2 pred: E gold: E
3 pred: A gold: A
4 pred: E gold: E

In [6]:
import time

if "pred_en_basic" not in df.columns:
    df["pred_en_basic"] = ""

save_path = "csqa_en_basic_progress.csv"

for i in range(len(df)):
    if str(df.loc[i, "pred_en_basic"]).strip() in list("ABCDE"):
        continue  

    print(f"CSQA EN-Basic {i+1}/{len(df)}")
    df.loc[i, "pred_en_basic"] = csqa_en_basic_predict(df.loc[i, "question"], df.loc[i, "options"])

    if (i + 1) % 25 == 0:
        df.to_csv(save_path, index=False)
        print("Saved:", save_path, "at", i+1)

    time.sleep(0.25)  

df.to_csv("csqa_en_basic_final.csv", index=False)
print("Saved: csqa_en_basic_final.csv")

CSQA EN-Basic 1/500
CSQA EN-Basic 2/500
CSQA EN-Basic 3/500
CSQA EN-Basic 4/500
CSQA EN-Basic 5/500
CSQA EN-Basic 6/500
CSQA EN-Basic 7/500
CSQA EN-Basic 8/500
CSQA EN-Basic 9/500
CSQA EN-Basic 10/500
CSQA EN-Basic 11/500
CSQA EN-Basic 12/500
CSQA EN-Basic 13/500
CSQA EN-Basic 14/500
CSQA EN-Basic 15/500
CSQA EN-Basic 16/500
CSQA EN-Basic 17/500
CSQA EN-Basic 18/500
CSQA EN-Basic 19/500
CSQA EN-Basic 20/500
CSQA EN-Basic 21/500
CSQA EN-Basic 22/500
CSQA EN-Basic 23/500
CSQA EN-Basic 24/500
CSQA EN-Basic 25/500
Saved: csqa_en_basic_progress.csv at 25
CSQA EN-Basic 26/500
CSQA EN-Basic 27/500
CSQA EN-Basic 28/500
CSQA EN-Basic 29/500
CSQA EN-Basic 30/500
CSQA EN-Basic 31/500
CSQA EN-Basic 32/500
CSQA EN-Basic 33/500
CSQA EN-Basic 34/500
CSQA EN-Basic 35/500
CSQA EN-Basic 36/500
CSQA EN-Basic 37/500
CSQA EN-Basic 38/500
CSQA EN-Basic 39/500
CSQA EN-Basic 40/500
CSQA EN-Basic 41/500
CSQA EN-Basic 42/500
CSQA EN-Basic 43/500
CSQA EN-Basic 44/500
CSQA EN-Basic 45/500
CSQA EN-Basic 46/500
CSQA EN-Basic 47/500
CSQA EN-Basic 48/500
CSQA EN-Basic 49/500
CSQA EN-Basic 50/500
Saved: csqa_en_basic_progress.csv at 50
CSQA EN-Basic 51/500
CSQA EN-Basic 52/500
CSQA EN-Basic 53/500
CSQA EN-Basic 54/500
CSQA EN-Basic 55/500
CSQA EN-Basic 56/500
CSQA EN-Basic 57/500
CSQA EN-Basic 58/500
CSQA EN-Basic 59/500
CSQA EN-Basic 60/500
CSQA EN-Basic 61/500
CSQA EN-Basic 62/500
CSQA EN-Basic 63/500
CSQA EN-Basic 64/500
CSQA EN-Basic 65/500
CSQA EN-Basic 66/500
CSQA EN-Basic 67/500
CSQA EN-Basic 68/500
CSQA EN-Basic 69/500
CSQA EN-Basic 70/500
CSQA EN-Basic 71/500
CSQA EN-Basic 72/500
CSQA EN-Basic 73/500
CSQA EN-Basic 74/500
CSQA EN-Basic 75/500
Saved: csqa_en_basic_progress.csv at 75
CSQA EN-Basic 76/500
CSQA EN-Basic 77/500
CSQA EN-Basic 78/500
CSQA EN-Basic 79/500
CSQA EN-Basic 80/500
CSQA EN-Basic 81/500
CSQA EN-Basic 82/500
CSQA EN-Basic 83/500
CSQA EN-Basic 84/500
CSQA EN-Basic 85/500
CSQA EN-Basic 86/500
CSQA EN-Basic 87/500
CSQA EN-Basic 88/500
CSQA EN-Basic 89/500
CSQA EN-Basic 90/500
CSQA EN-Basic 91/500
CSQA EN-Basic 92/500
CSQA EN-Basic 93/500
CSQA EN-Basic 94/500
CSQA EN-Basic 95/500
CSQA EN-Basic 96/500
CSQA EN-Basic 97/500
CSQA EN-Basic 98/500
CSQA EN-Basic 99/500
CSQA EN-Basic 100/500
Saved: csqa_en_basic_progress.csv at 100
CSQA EN-Basic 101/500
CSQA EN-Basic 102/500
CSQA EN-Basic 103/500
CSQA EN-Basic 104/500
CSQA EN-Basic 105/500
CSQA EN-Basic 106/500
CSQA EN-Basic 107/500
CSQA EN-Basic 108/500
CSQA EN-Basic 109/500
CSQA EN-Basic 110/500
CSQA EN-Basic 111/500
CSQA EN-Basic 112/500
CSQA EN-Basic 113/500
CSQA EN-Basic 114/500
CSQA EN-Basic 115/500
CSQA EN-Basic 116/500
CSQA EN-Basic 117/500
CSQA EN-Basic 118/500
CSQA EN-Basic 119/500
CSQA EN-Basic 120/500
CSQA EN-Basic 121/500
CSQA EN-Basic 122/500
CSQA EN-Basic 123/500
CSQA EN-Basic 124/500
CSQA EN-Basic 125/500
Saved: csqa_en_basic_progress.csv at 125
CSQA EN-Basic 126/500
CSQA EN-Basic 127/500
CSQA EN-Basic 128/500
CSQA EN-Basic 129/500
CSQA EN-Basic 130/500
CSQA EN-Basic 131/500
CSQA EN-Basic 132/500
CSQA EN-Basic 133/500
CSQA EN-Basic 134/500
CSQA EN-Basic 135/500
CSQA EN-Basic 136/500
CSQA EN-Basic 137/500
CSQA EN-Basic 138/500
CSQA EN-Basic 139/500
CSQA EN-Basic 140/500
CSQA EN-Basic 141/500
CSQA EN-Basic 142/500
CSQA EN-Basic 143/500
CSQA EN-Basic 144/500
CSQA EN-Basic 145/500
CSQA EN-Basic 146/500
CSQA EN-Basic 147/500
CSQA EN-Basic 148/500
CSQA EN-Basic 149/500
CSQA EN-Basic 150/500
Saved: csqa_en_basic_progress.csv at 150
CSQA EN-Basic 151/500
CSQA EN-Basic 152/500
CSQA EN-Basic 153/500
CSQA EN-Basic 154/500
CSQA EN-Basic 155/500
CSQA EN-Basic 156/500
CSQA EN-Basic 157/500
CSQA EN-Basic 158/500
CSQA EN-Basic 159/500
CSQA EN-Basic 160/500
CSQA EN-Basic 161/500
CSQA EN-Basic 162/500
CSQA EN-Basic 163/500
CSQA EN-Basic 164/500
CSQA EN-Basic 165/500
CSQA EN-Basic 166/500
CSQA EN-Basic 167/500
CSQA EN-Basic 168/500
CSQA EN-Basic 169/500
CSQA EN-Basic 170/500
CSQA EN-Basic 171/500
CSQA EN-Basic 172/500
CSQA EN-Basic 173/500
CSQA EN-Basic 174/500
CSQA EN-Basic 175/500
Saved: csqa_en_basic_progress.csv at 175
CSQA EN-Basic 176/500
CSQA EN-Basic 177/500
CSQA EN-Basic 178/500
CSQA EN-Basic 179/500
CSQA EN-Basic 180/500
CSQA EN-Basic 181/500
CSQA EN-Basic 182/500
CSQA EN-Basic 183/500
CSQA EN-Basic 184/500
CSQA EN-Basic 185/500
CSQA EN-Basic 186/500
CSQA EN-Basic 187/500
CSQA EN-Basic 188/500
CSQA EN-Basic 189/500
CSQA EN-Basic 190/500
CSQA EN-Basic 191/500
CSQA EN-Basic 192/500
CSQA EN-Basic 193/500
CSQA EN-Basic 194/500
CSQA EN-Basic 195/500
CSQA EN-Basic 196/500
CSQA EN-Basic 197/500
CSQA EN-Basic 198/500
CSQA EN-Basic 199/500
CSQA EN-Basic 200/500
Saved: csqa_en_basic_progress.csv at 200
CSQA EN-Basic 201/500
CSQA EN-Basic 202/500
CSQA EN-Basic 203/500
CSQA EN-Basic 204/500
CSQA EN-Basic 205/500
CSQA EN-Basic 206/500
CSQA EN-Basic 207/500
CSQA EN-Basic 208/500
CSQA EN-Basic 209/500
CSQA EN-Basic 210/500
CSQA EN-Basic 211/500
CSQA EN-Basic 212/500
CSQA EN-Basic 213/500
CSQA EN-Basic 214/500
CSQA EN-Basic 215/500
CSQA EN-Basic 216/500
CSQA EN-Basic 217/500
CSQA EN-Basic 218/500
CSQA EN-Basic 219/500
CSQA EN-Basic 220/500
CSQA EN-Basic 221/500
CSQA EN-Basic 222/500
CSQA EN-Basic 223/500
CSQA EN-Basic 224/500
CSQA EN-Basic 225/500
Saved: csqa_en_basic_progress.csv at 225
CSQA EN-Basic 226/500
CSQA EN-Basic 227/500
CSQA EN-Basic 228/500
CSQA EN-Basic 229/500
CSQA EN-Basic 230/500
CSQA EN-Basic 231/500
CSQA EN-Basic 232/500
CSQA EN-Basic 233/500
CSQA EN-Basic 234/500
CSQA EN-Basic 235/500
CSQA EN-Basic 236/500
CSQA EN-Basic 237/500
CSQA EN-Basic 238/500
CSQA EN-Basic 239/500
CSQA EN-Basic 240/500
CSQA EN-Basic 241/500
CSQA EN-Basic 242/500
CSQA EN-Basic 243/500
CSQA EN-Basic 244/500
CSQA EN-Basic 245/500
CSQA EN-Basic 246/500
CSQA EN-Basic 247/500
CSQA EN-Basic 248/500
CSQA EN-Basic 249/500
CSQA EN-Basic 250/500
Saved: csqa_en_basic_progress.csv at 250
CSQA EN-Basic 251/500
CSQA EN-Basic 252/500
CSQA EN-Basic 253/500
CSQA EN-Basic 254/500
CSQA EN-Basic 255/500
CSQA EN-Basic 256/500
CSQA EN-Basic 257/500
CSQA EN-Basic 258/500
CSQA EN-Basic 259/500
CSQA EN-Basic 260/500
CSQA EN-Basic 261/500
CSQA EN-Basic 262/500
CSQA EN-Basic 263/500
CSQA EN-Basic 264/500
CSQA EN-Basic 265/500
CSQA EN-Basic 266/500
CSQA EN-Basic 267/500
CSQA EN-Basic 268/500
CSQA EN-Basic 269/500
CSQA EN-Basic 270/500
CSQA EN-Basic 271/500
CSQA EN-Basic 272/500
CSQA EN-Basic 273/500
CSQA EN-Basic 274/500
CSQA EN-Basic 275/500
Saved: csqa_en_basic_progress.csv at 275
CSQA EN-Basic 276/500
CSQA EN-Basic 277/500
CSQA EN-Basic 278/500
CSQA EN-Basic 279/500
CSQA EN-Basic 280/500
CSQA EN-Basic 281/500
CSQA EN-Basic 282/500
CSQA EN-Basic 283/500
CSQA EN-Basic 284/500
CSQA EN-Basic 285/500
CSQA EN-Basic 286/500
CSQA EN-Basic 287/500
CSQA EN-Basic 288/500
CSQA EN-Basic 289/500
CSQA EN-Basic 290/500
CSQA EN-Basic 291/500
CSQA EN-Basic 292/500
CSQA EN-Basic 293/500
CSQA EN-Basic 294/500
CSQA EN-Basic 295/500
CSQA EN-Basic 296/500
CSQA EN-Basic 297/500
CSQA EN-Basic 298/500
CSQA EN-Basic 299/500
CSQA EN-Basic 300/500
Saved: csqa_en_basic_progress.csv at 300
CSQA EN-Basic 301/500
CSQA EN-Basic 302/500
CSQA EN-Basic 303/500
CSQA EN-Basic 304/500
CSQA EN-Basic 305/500
CSQA EN-Basic 306/500
CSQA EN-Basic 307/500
CSQA EN-Basic 308/500
CSQA EN-Basic 309/500
CSQA EN-Basic 310/500
CSQA EN-Basic 311/500
CSQA EN-Basic 312/500
CSQA EN-Basic 313/500
CSQA EN-Basic 314/500
CSQA EN-Basic 315/500
CSQA EN-Basic 316/500
CSQA EN-Basic 317/500
CSQA EN-Basic 318/500
CSQA EN-Basic 319/500
CSQA EN-Basic 320/500
CSQA EN-Basic 321/500
CSQA EN-Basic 322/500
CSQA EN-Basic 323/500
CSQA EN-Basic 324/500
CSQA EN-Basic 325/500
Saved: csqa_en_basic_progress.csv at 325
CSQA EN-Basic 326/500
CSQA EN-Basic 327/500
CSQA EN-Basic 328/500
CSQA EN-Basic 329/500
CSQA EN-Basic 330/500
CSQA EN-Basic 331/500
CSQA EN-Basic 332/500
CSQA EN-Basic 333/500
CSQA EN-Basic 334/500
CSQA EN-Basic 335/500
CSQA EN-Basic 336/500
CSQA EN-Basic 337/500
CSQA EN-Basic 338/500
CSQA EN-Basic 339/500
CSQA EN-Basic 340/500
CSQA EN-Basic 341/500
CSQA EN-Basic 342/500
CSQA EN-Basic 343/500
CSQA EN-Basic 344/500
CSQA EN-Basic 345/500
CSQA EN-Basic 346/500
CSQA EN-Basic 347/500
CSQA EN-Basic 348/500
CSQA EN-Basic 349/500
CSQA EN-Basic 350/500
Saved: csqa_en_basic_progress.csv at 350
CSQA EN-Basic 351/500
CSQA EN-Basic 352/500

CSQA EN-Basic 353/500
CSQA EN-Basic 354/500
CSQA EN-Basic 355/500
CSQA EN-Basic 356/500
CSQA EN-Basic 357/500
CSQA EN-Basic 358/500
CSQA EN-Basic 359/500
CSQA EN-Basic 360/500
CSQA EN-Basic 361/500
CSQA EN-Basic 362/500
CSQA EN-Basic 363/500
CSQA EN-Basic 364/500
CSQA EN-Basic 365/500
CSQA EN-Basic 366/500
CSQA EN-Basic 367/500
CSQA EN-Basic 368/500
CSQA EN-Basic 369/500
CSQA EN-Basic 370/500
CSQA EN-Basic 371/500
CSQA EN-Basic 372/500
CSQA EN-Basic 373/500
CSQA EN-Basic 374/500
CSQA EN-Basic 375/500
Saved: csqa_en_basic_progress.csv at 375
CSQA EN-Basic 376/500
CSQA EN-Basic 377/500
CSQA EN-Basic 378/500
CSQA EN-Basic 379/500
CSQA EN-Basic 380/500
CSQA EN-Basic 381/500
CSQA EN-Basic 382/500
CSQA EN-Basic 383/500
CSQA EN-Basic 384/500
CSQA EN-Basic 385/500
CSQA EN-Basic 386/500
CSQA EN-Basic 387/500
CSQA EN-Basic 388/500
CSQA EN-Basic 389/500
CSQA EN-Basic 390/500
CSQA EN-Basic 391/500
CSQA EN-Basic 392/500
CSQA EN-Basic 393/500
CSQA EN-Basic 394/500
CSQA EN-Basic 395/500
CSQA EN-Basic 396/500
CSQA EN-Basic 397/500
CSQA EN-Basic 398/500
CSQA EN-Basic 399/500
CSQA EN-Basic 400/500
Saved: csqa_en_basic_progress.csv at 400
CSQA EN-Basic 401/500
CSQA EN-Basic 402/500
CSQA EN-Basic 403/500
CSQA EN-Basic 404/500
CSQA EN-Basic 405/500
CSQA EN-Basic 406/500
CSQA EN-Basic 407/500
CSQA EN-Basic 408/500
CSQA EN-Basic 409/500
CSQA EN-Basic 410/500
CSQA EN-Basic 411/500
CSQA EN-Basic 412/500
CSQA EN-Basic 413/500
CSQA EN-Basic 414/500
CSQA EN-Basic 415/500
CSQA EN-Basic 416/500
CSQA EN-Basic 417/500
CSQA EN-Basic 418/500
CSQA EN-Basic 419/500
CSQA EN-Basic 420/500
CSQA EN-Basic 421/500
CSQA EN-Basic 422/500
CSQA EN-Basic 423/500
CSQA EN-Basic 424/500
CSQA EN-Basic 425/500
Saved: csqa_en_basic_progress.csv at 425
CSQA EN-Basic 426/500
CSQA EN-Basic 427/500
CSQA EN-Basic 428/500
CSQA EN-Basic 429/500
CSQA EN-Basic 430/500
CSQA EN-Basic 431/500
CSQA EN-Basic 432/500
CSQA EN-Basic 433/500
CSQA EN-Basic 434/500
CSQA EN-Basic 435/500
CSQA EN-Basic 436/500
CSQA EN-Basic 437/500
CSQA EN-Basic 438/500
CSQA EN-Basic 439/500
CSQA EN-Basic 440/500
CSQA EN-Basic 441/500
CSQA EN-Basic 442/500
CSQA EN-Basic 443/500
CSQA EN-Basic 444/500
CSQA EN-Basic 445/500
CSQA EN-Basic 446/500
CSQA EN-Basic 447/500
CSQA EN-Basic 448/500
CSQA EN-Basic 449/500
CSQA EN-Basic 450/500
Saved: csqa_en_basic_progress.csv at 450
CSQA EN-Basic 451/500
CSQA EN-Basic 452/500
CSQA EN-Basic 453/500
CSQA EN-Basic 454/500
CSQA EN-Basic 455/500
CSQA EN-Basic 456/500
CSQA EN-Basic 457/500
CSQA EN-Basic 458/500
CSQA EN-Basic 459/500
CSQA EN-Basic 460/500
CSQA EN-Basic 461/500
CSQA EN-Basic 462/500
CSQA EN-Basic 463/500
CSQA EN-Basic 464/500
CSQA EN-Basic 465/500
CSQA EN-Basic 466/500
CSQA EN-Basic 467/500
CSQA EN-Basic 468/500
CSQA EN-Basic 469/500
CSQA EN-Basic 470/500
CSQA EN-Basic 471/500
CSQA EN-Basic 472/500
CSQA EN-Basic 473/500
CSQA EN-Basic 474/500
CSQA EN-Basic 475/500
Saved: csqa_en_basic_progress.csv at 475
CSQA EN-Basic 476/500
CSQA EN-Basic 477/500
CSQA EN-Basic 478/500
CSQA EN-Basic 479/500
CSQA EN-Basic 480/500
CSQA EN-Basic 481/500
CSQA EN-Basic 482/500
CSQA EN-Basic 483/500
CSQA EN-Basic 484/500
CSQA EN-Basic 485/500
CSQA EN-Basic 486/500
CSQA EN-Basic 487/500
CSQA EN-Basic 488/500
CSQA EN-Basic 489/500
CSQA EN-Basic 490/500
CSQA EN-Basic 491/500
CSQA EN-Basic 492/500
CSQA EN-Basic 493/500
CSQA EN-Basic 494/500
CSQA EN-Basic 495/500
CSQA EN-Basic 496/500
CSQA EN-Basic 497/500
CSQA EN-Basic 498/500
CSQA EN-Basic 499/500
CSQA EN-Basic 500/500
Saved: csqa_en_basic_progress.csv at 500
Saved: csqa_en_basic_final.csv

In [7]:
from sklearn.metrics import accuracy_score, classification_report

y_true = df["answer_key"].astype(str).str.strip().str.upper()
y_pred = df["pred_en_basic"].astype(str).str.strip().str.upper()

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred, labels=list("ABCDE")))

Accuracy: 0.884
              precision    recall  f1-score   support

           A       0.89      0.92      0.91       100
           B       0.91      0.91      0.91       118
           C       0.88      0.91      0.89        87
           D       0.87      0.85      0.86       102
           E       0.87      0.83      0.85        93

    accuracy                           0.88       500
   macro avg       0.88      0.88      0.88       500
weighted avg       0.88      0.88      0.88       500

In [8]:
import pandas as pd

df = pd.read_csv("commonsenseqa_kz_500.csv")  
print(df.columns)
df.head(2)

Index(['id', 'question', 'options', 'answer_key', 'question_kz', 'options_kz'], dtype='object')

,id,question,options,answer_key,question_kz,options_kz
0,c0d75f9fbf30aa3a612f16edb20d6b8d,The man took paperwork to other people to cons...,A) desk\nB) meeting\nC) office\nD) table\nE) work,B,Ер адам құжаттарды басқа адамдармен кеңесу үші...,A) үстел\nB) жиналыс\nC) кеңсе\nD) үстел\nE) ж...
1,c21ec5b367f409a0288d616f626555ae,"If a person is working a lot, what are they li...",A) much money\nB) own house\nC) creativity\nD)...,A,"Егер адам көп жұмыс істесе, олар нені табуға т...",A) көп ақша\nB) өз үйі\nC) шығармашылық\nD) жа...

In [9]:
def csqa_native_basic_kz_predict(question_kz: str, options_kz: str) -> str:
    prompt = f"""Сен күнделікті өмірге қатысты логикалық (commonsense) сұрақтарды жақсы түсінетін сарапшысың.

Төмендегі көп таңдаулы сұраққа дұрыс жауапты таңда.
Тек бір әріппен жауап бер: A, B, C, D немесе E.
Ешқандай түсіндірме қоспа.

СҰРАҚ:
{question_kz}

ЖАУАП НҰСҚАЛАРЫ:
{options_kz}
"""
    resp = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role": "user", "content": prompt}],
    )
    out = resp.choices[0].message.content.strip().upper()
    m = re.search(r"\b([ABCDE])\b", out)
    return m.group(1) if m else out

In [10]:
for i in range(5):
    pred = csqa_native_basic_kz_predict(df.loc[i, "question_kz"], df.loc[i, "options_kz"])
    print(i, "pred:", pred, "gold:", df.loc[i, "answer_key"])
    time.sleep(0.25)

0 pred: B gold: B
1 pred: A gold: A
2 pred: B gold: E
3 pred: A gold: A
4 pred: E gold: E

In [11]:
if "pred_native_kz" not in df.columns:
    df["pred_native_kz"] = ""

progress_path = "csqa_pred_native_kz_progress.csv"
final_path = "csqa_pred_native_kz_final.csv"

for i in range(len(df)):
    if str(df.loc[i, "pred_native_kz"]).strip() in list("ABCDE"):
        continue  # resume-safe

    print(f"CSQA Native-Basic KZ {i+1}/{len(df)}")
    df.loc[i, "pred_native_kz"] = csqa_native_basic_kz_predict(
        df.loc[i, "question_kz"],
        df.loc[i, "options_kz"],
    )

    if (i + 1) % 25 == 0:
        df.to_csv(progress_path, index=False)
        print("Saved:", progress_path)

    time.sleep(0.25)

df.to_csv(final_path, index=False)
print("Saved:", final_path)

CSQA Native-Basic KZ 1/500
CSQA Native-Basic KZ 2/500
CSQA Native-Basic KZ 3/500
CSQA Native-Basic KZ 4/500
CSQA Native-Basic KZ 5/500
CSQA Native-Basic KZ 6/500
CSQA Native-Basic KZ 7/500
CSQA Native-Basic KZ 8/500
CSQA Native-Basic KZ 9/500
CSQA Native-Basic KZ 10/500
CSQA Native-Basic KZ 11/500
CSQA Native-Basic KZ 12/500
CSQA Native-Basic KZ 13/500
CSQA Native-Basic KZ 14/500
CSQA Native-Basic KZ 15/500
CSQA Native-Basic KZ 16/500
CSQA Native-Basic KZ 17/500
CSQA Native-Basic KZ 18/500
CSQA Native-Basic KZ 19/500
CSQA Native-Basic KZ 20/500
CSQA Native-Basic KZ 21/500
CSQA Native-Basic KZ 22/500
CSQA Native-Basic KZ 23/500
CSQA Native-Basic KZ 24/500
CSQA Native-Basic KZ 25/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 26/500
CSQA Native-Basic KZ 27/500
CSQA Native-Basic KZ 28/500
CSQA Native-Basic KZ 29/500
CSQA Native-Basic KZ 30/500
CSQA Native-Basic KZ 31/500
CSQA Native-Basic KZ 32/500
CSQA Native-Basic KZ 33/500
CSQA Native-Basic KZ 34/500
CSQA Native-Basic KZ 35/500
CSQA Native-Basic KZ 36/500
CSQA Native-Basic KZ 37/500
CSQA Native-Basic KZ 38/500
CSQA Native-Basic KZ 39/500
CSQA Native-Basic KZ 40/500
CSQA Native-Basic KZ 41/500
CSQA Native-Basic KZ 42/500
CSQA Native-Basic KZ 43/500
CSQA Native-Basic KZ 44/500
CSQA Native-Basic KZ 45/500
CSQA Native-Basic KZ 46/500
CSQA Native-Basic KZ 47/500
CSQA Native-Basic KZ 48/500
CSQA Native-Basic KZ 49/500
CSQA Native-Basic KZ 50/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 51/500
CSQA Native-Basic KZ 52/500
CSQA Native-Basic KZ 53/500
CSQA Native-Basic KZ 54/500
CSQA Native-Basic KZ 55/500
CSQA Native-Basic KZ 56/500
CSQA Native-Basic KZ 57/500
CSQA Native-Basic KZ 58/500
CSQA Native-Basic KZ 59/500
CSQA Native-Basic KZ 60/500
CSQA Native-Basic KZ 61/500
CSQA Native-Basic KZ 62/500
CSQA Native-Basic KZ 63/500
CSQA Native-Basic KZ 64/500
CSQA Native-Basic KZ 65/500
CSQA Native-Basic KZ 66/500
CSQA Native-Basic KZ 67/500
CSQA Native-Basic KZ 68/500
CSQA Native-Basic KZ 69/500
CSQA Native-Basic KZ 70/500
CSQA Native-Basic KZ 71/500
CSQA Native-Basic KZ 72/500
CSQA Native-Basic KZ 73/500
CSQA Native-Basic KZ 74/500
CSQA Native-Basic KZ 75/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 76/500
CSQA Native-Basic KZ 77/500
CSQA Native-Basic KZ 78/500
CSQA Native-Basic KZ 79/500
CSQA Native-Basic KZ 80/500
CSQA Native-Basic KZ 81/500
CSQA Native-Basic KZ 82/500
CSQA Native-Basic KZ 83/500
CSQA Native-Basic KZ 84/500
CSQA Native-Basic KZ 85/500
CSQA Native-Basic KZ 86/500
CSQA Native-Basic KZ 87/500
CSQA Native-Basic KZ 88/500
CSQA Native-Basic KZ 89/500
CSQA Native-Basic KZ 90/500
CSQA Native-Basic KZ 91/500
CSQA Native-Basic KZ 92/500
CSQA Native-Basic KZ 93/500
CSQA Native-Basic KZ 94/500
CSQA Native-Basic KZ 95/500
CSQA Native-Basic KZ 96/500
CSQA Native-Basic KZ 97/500
CSQA Native-Basic KZ 98/500
CSQA Native-Basic KZ 99/500
CSQA Native-Basic KZ 100/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 101/500
CSQA Native-Basic KZ 102/500
CSQA Native-Basic KZ 103/500
CSQA Native-Basic KZ 104/500
CSQA Native-Basic KZ 105/500
CSQA Native-Basic KZ 106/500
CSQA Native-Basic KZ 107/500
CSQA Native-Basic KZ 108/500
CSQA Native-Basic KZ 109/500
CSQA Native-Basic KZ 110/500
CSQA Native-Basic KZ 111/500
CSQA Native-Basic KZ 112/500
CSQA Native-Basic KZ 113/500
CSQA Native-Basic KZ 114/500
CSQA Native-Basic KZ 115/500
CSQA Native-Basic KZ 116/500
CSQA Native-Basic KZ 117/500
CSQA Native-Basic KZ 118/500
CSQA Native-Basic KZ 119/500
CSQA Native-Basic KZ 120/500
CSQA Native-Basic KZ 121/500
CSQA Native-Basic KZ 122/500
CSQA Native-Basic KZ 123/500
CSQA Native-Basic KZ 124/500
CSQA Native-Basic KZ 125/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 126/500
CSQA Native-Basic KZ 127/500
CSQA Native-Basic KZ 128/500
CSQA Native-Basic KZ 129/500
CSQA Native-Basic KZ 130/500
CSQA Native-Basic KZ 131/500
CSQA Native-Basic KZ 132/500
CSQA Native-Basic KZ 133/500
CSQA Native-Basic KZ 134/500
CSQA Native-Basic KZ 135/500
CSQA Native-Basic KZ 136/500
CSQA Native-Basic KZ 137/500
CSQA Native-Basic KZ 138/500
CSQA Native-Basic KZ 139/500
CSQA Native-Basic KZ 140/500
CSQA Native-Basic KZ 141/500
CSQA Native-Basic KZ 142/500
CSQA Native-Basic KZ 143/500
CSQA Native-Basic KZ 144/500
CSQA Native-Basic KZ 145/500
CSQA Native-Basic KZ 146/500
CSQA Native-Basic KZ 147/500
CSQA Native-Basic KZ 148/500
CSQA Native-Basic KZ 149/500
CSQA Native-Basic KZ 150/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 151/500
CSQA Native-Basic KZ 152/500
CSQA Native-Basic KZ 153/500
CSQA Native-Basic KZ 154/500
CSQA Native-Basic KZ 155/500
CSQA Native-Basic KZ 156/500
CSQA Native-Basic KZ 157/500
CSQA Native-Basic KZ 158/500
CSQA Native-Basic KZ 159/500
CSQA Native-Basic KZ 160/500
CSQA Native-Basic KZ 161/500
CSQA Native-Basic KZ 162/500
CSQA Native-Basic KZ 163/500
CSQA Native-Basic KZ 164/500
CSQA Native-Basic KZ 165/500
CSQA Native-Basic KZ 166/500
CSQA Native-Basic KZ 167/500
CSQA Native-Basic KZ 168/500
CSQA Native-Basic KZ 169/500
CSQA Native-Basic KZ 170/500
CSQA Native-Basic KZ 171/500
CSQA Native-Basic KZ 172/500
CSQA Native-Basic KZ 173/500
CSQA Native-Basic KZ 174/500
CSQA Native-Basic KZ 175/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 176/500
CSQA Native-Basic KZ 177/500
CSQA Native-Basic KZ 178/500
CSQA Native-Basic KZ 179/500
CSQA Native-Basic KZ 180/500
CSQA Native-Basic KZ 181/500
CSQA Native-Basic KZ 182/500
CSQA Native-Basic KZ 183/500
CSQA Native-Basic KZ 184/500
CSQA Native-Basic KZ 185/500
CSQA Native-Basic KZ 186/500
CSQA Native-Basic KZ 187/500
CSQA Native-Basic KZ 188/500
CSQA Native-Basic KZ 189/500
CSQA Native-Basic KZ 190/500
CSQA Native-Basic KZ 191/500
CSQA Native-Basic KZ 192/500
CSQA Native-Basic KZ 193/500
CSQA Native-Basic KZ 194/500
CSQA Native-Basic KZ 195/500
CSQA Native-Basic KZ 196/500
CSQA Native-Basic KZ 197/500
CSQA Native-Basic KZ 198/500
CSQA Native-Basic KZ 199/500
CSQA Native-Basic KZ 200/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 201/500
CSQA Native-Basic KZ 202/500
CSQA Native-Basic KZ 203/500
CSQA Native-Basic KZ 204/500
CSQA Native-Basic KZ 205/500
CSQA Native-Basic KZ 206/500
CSQA Native-Basic KZ 207/500
CSQA Native-Basic KZ 208/500
CSQA Native-Basic KZ 209/500
CSQA Native-Basic KZ 210/500
CSQA Native-Basic KZ 211/500
CSQA Native-Basic KZ 212/500
CSQA Native-Basic KZ 213/500
CSQA Native-Basic KZ 214/500
CSQA Native-Basic KZ 215/500
CSQA Native-Basic KZ 216/500
CSQA Native-Basic KZ 217/500
CSQA Native-Basic KZ 218/500
CSQA Native-Basic KZ 219/500
CSQA Native-Basic KZ 220/500
CSQA Native-Basic KZ 221/500
CSQA Native-Basic KZ 222/500
CSQA Native-Basic KZ 223/500
CSQA Native-Basic KZ 224/500
CSQA Native-Basic KZ 225/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 226/500
CSQA Native-Basic KZ 227/500
CSQA Native-Basic KZ 228/500
CSQA Native-Basic KZ 229/500
CSQA Native-Basic KZ 230/500
CSQA Native-Basic KZ 231/500
CSQA Native-Basic KZ 232/500
CSQA Native-Basic KZ 233/500
CSQA Native-Basic KZ 234/500
CSQA Native-Basic KZ 235/500
CSQA Native-Basic KZ 236/500
CSQA Native-Basic KZ 237/500
CSQA Native-Basic KZ 238/500
CSQA Native-Basic KZ 239/500
CSQA Native-Basic KZ 240/500
CSQA Native-Basic KZ 241/500
CSQA Native-Basic KZ 242/500
CSQA Native-Basic KZ 243/500
CSQA Native-Basic KZ 244/500
CSQA Native-Basic KZ 245/500
CSQA Native-Basic KZ 246/500
CSQA Native-Basic KZ 247/500
CSQA Native-Basic KZ 248/500
CSQA Native-Basic KZ 249/500
CSQA Native-Basic KZ 250/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 251/500
CSQA Native-Basic KZ 252/500
CSQA Native-Basic KZ 253/500
CSQA Native-Basic KZ 254/500
CSQA Native-Basic KZ 255/500
CSQA Native-Basic KZ 256/500
CSQA Native-Basic KZ 257/500
CSQA Native-Basic KZ 258/500
CSQA Native-Basic KZ 259/500
CSQA Native-Basic KZ 260/500
CSQA Native-Basic KZ 261/500
CSQA Native-Basic KZ 262/500
CSQA Native-Basic KZ 263/500
CSQA Native-Basic KZ 264/500
CSQA Native-Basic KZ 265/500
CSQA Native-Basic KZ 266/500
CSQA Native-Basic KZ 267/500
CSQA Native-Basic KZ 268/500
CSQA Native-Basic KZ 269/500
CSQA Native-Basic KZ 270/500
CSQA Native-Basic KZ 271/500
CSQA Native-Basic KZ 272/500
CSQA Native-Basic KZ 273/500

CSQA Native-Basic KZ 274/500
CSQA Native-Basic KZ 275/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 276/500
CSQA Native-Basic KZ 277/500
CSQA Native-Basic KZ 278/500
CSQA Native-Basic KZ 279/500
CSQA Native-Basic KZ 280/500
CSQA Native-Basic KZ 281/500
CSQA Native-Basic KZ 282/500
CSQA Native-Basic KZ 283/500
CSQA Native-Basic KZ 284/500
CSQA Native-Basic KZ 285/500
CSQA Native-Basic KZ 286/500
CSQA Native-Basic KZ 287/500
CSQA Native-Basic KZ 288/500
CSQA Native-Basic KZ 289/500
CSQA Native-Basic KZ 290/500
CSQA Native-Basic KZ 291/500
CSQA Native-Basic KZ 292/500
CSQA Native-Basic KZ 293/500
CSQA Native-Basic KZ 294/500
CSQA Native-Basic KZ 295/500
CSQA Native-Basic KZ 296/500
CSQA Native-Basic KZ 297/500
CSQA Native-Basic KZ 298/500
CSQA Native-Basic KZ 299/500
CSQA Native-Basic KZ 300/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 301/500
CSQA Native-Basic KZ 302/500
CSQA Native-Basic KZ 303/500
CSQA Native-Basic KZ 304/500
CSQA Native-Basic KZ 305/500
CSQA Native-Basic KZ 306/500
CSQA Native-Basic KZ 307/500
CSQA Native-Basic KZ 308/500
CSQA Native-Basic KZ 309/500
CSQA Native-Basic KZ 310/500
CSQA Native-Basic KZ 311/500
CSQA Native-Basic KZ 312/500
CSQA Native-Basic KZ 313/500
CSQA Native-Basic KZ 314/500
CSQA Native-Basic KZ 315/500
CSQA Native-Basic KZ 316/500
CSQA Native-Basic KZ 317/500
CSQA Native-Basic KZ 318/500
CSQA Native-Basic KZ 319/500
CSQA Native-Basic KZ 320/500
CSQA Native-Basic KZ 321/500
CSQA Native-Basic KZ 322/500
CSQA Native-Basic KZ 323/500
CSQA Native-Basic KZ 324/500
CSQA Native-Basic KZ 325/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 326/500
CSQA Native-Basic KZ 327/500
CSQA Native-Basic KZ 328/500
CSQA Native-Basic KZ 329/500
CSQA Native-Basic KZ 330/500
CSQA Native-Basic KZ 331/500
CSQA Native-Basic KZ 332/500
CSQA Native-Basic KZ 333/500
CSQA Native-Basic KZ 334/500
CSQA Native-Basic KZ 335/500
CSQA Native-Basic KZ 336/500
CSQA Native-Basic KZ 337/500
CSQA Native-Basic KZ 338/500
CSQA Native-Basic KZ 339/500
CSQA Native-Basic KZ 340/500
CSQA Native-Basic KZ 341/500
CSQA Native-Basic KZ 342/500
CSQA Native-Basic KZ 343/500
CSQA Native-Basic KZ 344/500
CSQA Native-Basic KZ 345/500
CSQA Native-Basic KZ 346/500
CSQA Native-Basic KZ 347/500
CSQA Native-Basic KZ 348/500
CSQA Native-Basic KZ 349/500
CSQA Native-Basic KZ 350/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 351/500
CSQA Native-Basic KZ 352/500
CSQA Native-Basic KZ 353/500
CSQA Native-Basic KZ 354/500
CSQA Native-Basic KZ 355/500
CSQA Native-Basic KZ 356/500
CSQA Native-Basic KZ 357/500
CSQA Native-Basic KZ 358/500
CSQA Native-Basic KZ 359/500
CSQA Native-Basic KZ 360/500
CSQA Native-Basic KZ 361/500
CSQA Native-Basic KZ 362/500
CSQA Native-Basic KZ 363/500
CSQA Native-Basic KZ 364/500
CSQA Native-Basic KZ 365/500
CSQA Native-Basic KZ 366/500
CSQA Native-Basic KZ 367/500
CSQA Native-Basic KZ 368/500
CSQA Native-Basic KZ 369/500
CSQA Native-Basic KZ 370/500
CSQA Native-Basic KZ 371/500
CSQA Native-Basic KZ 372/500
CSQA Native-Basic KZ 373/500
CSQA Native-Basic KZ 374/500
CSQA Native-Basic KZ 375/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 376/500
CSQA Native-Basic KZ 377/500
CSQA Native-Basic KZ 378/500
CSQA Native-Basic KZ 379/500
CSQA Native-Basic KZ 380/500
CSQA Native-Basic KZ 381/500
CSQA Native-Basic KZ 382/500
CSQA Native-Basic KZ 383/500
CSQA Native-Basic KZ 384/500
CSQA Native-Basic KZ 385/500
CSQA Native-Basic KZ 386/500
CSQA Native-Basic KZ 387/500
CSQA Native-Basic KZ 388/500
CSQA Native-Basic KZ 389/500
CSQA Native-Basic KZ 390/500
CSQA Native-Basic KZ 391/500
CSQA Native-Basic KZ 392/500
CSQA Native-Basic KZ 393/500
CSQA Native-Basic KZ 394/500
CSQA Native-Basic KZ 395/500
CSQA Native-Basic KZ 396/500
CSQA Native-Basic KZ 397/500
CSQA Native-Basic KZ 398/500
CSQA Native-Basic KZ 399/500
CSQA Native-Basic KZ 400/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 401/500
CSQA Native-Basic KZ 402/500
CSQA Native-Basic KZ 403/500
CSQA Native-Basic KZ 404/500
CSQA Native-Basic KZ 405/500
CSQA Native-Basic KZ 406/500
CSQA Native-Basic KZ 407/500
CSQA Native-Basic KZ 408/500
CSQA Native-Basic KZ 409/500
CSQA Native-Basic KZ 410/500
CSQA Native-Basic KZ 411/500
CSQA Native-Basic KZ 412/500
CSQA Native-Basic KZ 413/500
CSQA Native-Basic KZ 414/500
CSQA Native-Basic KZ 415/500
CSQA Native-Basic KZ 416/500
CSQA Native-Basic KZ 417/500
CSQA Native-Basic KZ 418/500
CSQA Native-Basic KZ 419/500
CSQA Native-Basic KZ 420/500
CSQA Native-Basic KZ 421/500
CSQA Native-Basic KZ 422/500
CSQA Native-Basic KZ 423/500
CSQA Native-Basic KZ 424/500
CSQA Native-Basic KZ 425/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 426/500
CSQA Native-Basic KZ 427/500
CSQA Native-Basic KZ 428/500
CSQA Native-Basic KZ 429/500
CSQA Native-Basic KZ 430/500
CSQA Native-Basic KZ 431/500
CSQA Native-Basic KZ 432/500
CSQA Native-Basic KZ 433/500
CSQA Native-Basic KZ 434/500
CSQA Native-Basic KZ 435/500
CSQA Native-Basic KZ 436/500
CSQA Native-Basic KZ 437/500
CSQA Native-Basic KZ 438/500
CSQA Native-Basic KZ 439/500
CSQA Native-Basic KZ 440/500
CSQA Native-Basic KZ 441/500
CSQA Native-Basic KZ 442/500
CSQA Native-Basic KZ 443/500
CSQA Native-Basic KZ 444/500
CSQA Native-Basic KZ 445/500
CSQA Native-Basic KZ 446/500
CSQA Native-Basic KZ 447/500
CSQA Native-Basic KZ 448/500
CSQA Native-Basic KZ 449/500
CSQA Native-Basic KZ 450/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 451/500
CSQA Native-Basic KZ 452/500
CSQA Native-Basic KZ 453/500
CSQA Native-Basic KZ 454/500
CSQA Native-Basic KZ 455/500
CSQA Native-Basic KZ 456/500
CSQA Native-Basic KZ 457/500
CSQA Native-Basic KZ 458/500
CSQA Native-Basic KZ 459/500
CSQA Native-Basic KZ 460/500
CSQA Native-Basic KZ 461/500
CSQA Native-Basic KZ 462/500
CSQA Native-Basic KZ 463/500
CSQA Native-Basic KZ 464/500
CSQA Native-Basic KZ 465/500
CSQA Native-Basic KZ 466/500
CSQA Native-Basic KZ 467/500
CSQA Native-Basic KZ 468/500
CSQA Native-Basic KZ 469/500
CSQA Native-Basic KZ 470/500
CSQA Native-Basic KZ 471/500
CSQA Native-Basic KZ 472/500
CSQA Native-Basic KZ 473/500
CSQA Native-Basic KZ 474/500
CSQA Native-Basic KZ 475/500
Saved: csqa_pred_native_kz_progress.csv
CSQA Native-Basic KZ 476/500
CSQA Native-Basic KZ 477/500
CSQA Native-Basic KZ 478/500
CSQA Native-Basic KZ 479/500
CSQA Native-Basic KZ 480/500
CSQA Native-Basic KZ 481/500
CSQA Native-Basic KZ 482/500
CSQA Native-Basic KZ 483/500
CSQA Native-Basic KZ 484/500
CSQA Native-Basic KZ 485/500
CSQA Native-Basic KZ 486/500
CSQA Native-Basic KZ 487/500
CSQA Native-Basic KZ 488/500
CSQA Native-Basic KZ 489/500
CSQA Native-Basic KZ 490/500
CSQA Native-Basic KZ 491/500
CSQA Native-Basic KZ 492/500
CSQA Native-Basic KZ 493/500
CSQA Native-Basic KZ 494/500
CSQA Native-Basic KZ 495/500
CSQA Native-Basic KZ 496/500
CSQA Native-Basic KZ 497/500
CSQA Native-Basic KZ 498/500
CSQA Native-Basic KZ 499/500
CSQA Native-Basic KZ 500/500
Saved: csqa_pred_native_kz_progress.csv
Saved: csqa_pred_native_kz_final.csv

In [12]:
df_eval = pd.read_csv(final_path)

y_true = df_eval["answer_key"].astype(str).str.strip().str.upper()
y_pred = df_eval["pred_native_kz"].astype(str).str.strip().str.upper()

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred, labels=list("ABCDE")))

Accuracy: 0.738
              precision    recall  f1-score   support

           A       0.74      0.80      0.77       100
           B       0.76      0.76      0.76       118
           C       0.67      0.64      0.66        87
           D       0.74      0.73      0.73       102
           E       0.76      0.74      0.75        93

    accuracy                           0.74       500
   macro avg       0.74      0.73      0.73       500
weighted avg       0.74      0.74      0.74       500

In [13]:
def csqa_en_prompt_kz_input(question_kz, options_kz):

    prompt = f"""You are a commonsense reasoning expert.

Answer the following multiple choice question.

Respond with ONLY one letter: A, B, C, D, or E.
Do not explain your answer.

Question:
{question_kz}

Choices:
{options_kz}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role":"user","content":prompt}]
    )

    output = response.choices[0].message.content.strip().upper()

    match = re.search(r"[ABCDE]", output)
    return match.group(0) if match else output

In [14]:
for i in range(5):

    pred = csqa_en_prompt_kz_input(
        df.loc[i,"question_kz"],
        df.loc[i,"options_kz"]
    )

    print(i, "pred:", pred, "gold:", df.loc[i,"answer_key"])

0 pred: B gold: B
1 pred: A gold: A
2 pred: E gold: E
3 pred: A gold: A
4 pred: E gold: E

In [15]:
import time

df["pred_en_kz"] = ""

for i in range(len(df)):

    print(f"EN prompt + KZ input {i+1}/500")

    df.loc[i,"pred_en_kz"] = csqa_en_prompt_kz_input(
        df.loc[i,"question_kz"],
        df.loc[i,"options_kz"]
    )

    if (i+1) % 25 == 0:
        df.to_csv("csqa_en_kz_progress.csv", index=False)

    time.sleep(0.25)

df.to_csv("csqa_en_kz_final.csv", index=False)

print("Finished EN prompt + KZ input experiment")

EN prompt + KZ input 1/500
EN prompt + KZ input 2/500
EN prompt + KZ input 3/500
EN prompt + KZ input 4/500
EN prompt + KZ input 5/500
EN prompt + KZ input 6/500
EN prompt + KZ input 7/500
EN prompt + KZ input 8/500
EN prompt + KZ input 9/500
EN prompt + KZ input 10/500
EN prompt + KZ input 11/500
EN prompt + KZ input 12/500
EN prompt + KZ input 13/500
EN prompt + KZ input 14/500
EN prompt + KZ input 15/500
EN prompt + KZ input 16/500
EN prompt + KZ input 17/500
EN prompt + KZ input 18/500
EN prompt + KZ input 19/500
EN prompt + KZ input 20/500
EN prompt + KZ input 21/500
EN prompt + KZ input 22/500
EN prompt + KZ input 23/500
EN prompt + KZ input 24/500
EN prompt + KZ input 25/500
EN prompt + KZ input 26/500
EN prompt + KZ input 27/500
EN prompt + KZ input 28/500
EN prompt + KZ input 29/500
EN prompt + KZ input 30/500
EN prompt + KZ input 31/500
EN prompt + KZ input 32/500
EN prompt + KZ input 33/500
EN prompt + KZ input 34/500
EN prompt + KZ input 35/500
EN prompt + KZ input 36/500
EN prompt + KZ input 37/500
EN prompt + KZ input 38/500
EN prompt + KZ input 39/500
EN prompt + KZ input 40/500
EN prompt + KZ input 41/500
EN prompt + KZ input 42/500
EN prompt + KZ input 43/500
EN prompt + KZ input 44/500
EN prompt + KZ input 45/500
EN prompt + KZ input 46/500
EN prompt + KZ input 47/500
EN prompt + KZ input 48/500
EN prompt + KZ input 49/500
EN prompt + KZ input 50/500
EN prompt + KZ input 51/500
EN prompt + KZ input 52/500
EN prompt + KZ input 53/500
EN prompt + KZ input 54/500
EN prompt + KZ input 55/500
EN prompt + KZ input 56/500
EN prompt + KZ input 57/500
EN prompt + KZ input 58/500
EN prompt + KZ input 59/500
EN prompt + KZ input 60/500
EN prompt + KZ input 61/500
EN prompt + KZ input 62/500
EN prompt + KZ input 63/500
EN prompt + KZ input 64/500
EN prompt + KZ input 65/500
EN prompt + KZ input 66/500
EN prompt + KZ input 67/500
EN prompt + KZ input 68/500
EN prompt + KZ input 69/500
EN prompt + KZ input 70/500
EN prompt + KZ input 71/500
EN prompt + KZ input 72/500
EN prompt + KZ input 73/500
EN prompt + KZ input 74/500
EN prompt + KZ input 75/500
EN prompt + KZ input 76/500
EN prompt + KZ input 77/500
EN prompt + KZ input 78/500
EN prompt + KZ input 79/500
EN prompt + KZ input 80/500
EN prompt + KZ input 81/500
EN prompt + KZ input 82/500
EN prompt + KZ input 83/500
EN prompt + KZ input 84/500
EN prompt + KZ input 85/500
EN prompt + KZ input 86/500
EN prompt + KZ input 87/500
EN prompt + KZ input 88/500
EN prompt + KZ input 89/500
EN prompt + KZ input 90/500
EN prompt + KZ input 91/500
EN prompt + KZ input 92/500
EN prompt + KZ input 93/500
EN prompt + KZ input 94/500
EN prompt + KZ input 95/500
EN prompt + KZ input 96/500
EN prompt + KZ input 97/500
EN prompt + KZ input 98/500
EN prompt + KZ input 99/500
EN prompt + KZ input 100/500
EN prompt + KZ input 101/500
EN prompt + KZ input 102/500
EN prompt + KZ input 103/500
EN prompt + KZ input 104/500
EN prompt + KZ input 105/500
EN prompt + KZ input 106/500
EN prompt + KZ input 107/500
EN prompt + KZ input 108/500
EN prompt + KZ input 109/500
EN prompt + KZ input 110/500
EN prompt + KZ input 111/500
EN prompt + KZ input 112/500
EN prompt + KZ input 113/500
EN prompt + KZ input 114/500
EN prompt + KZ input 115/500
EN prompt + KZ input 116/500
EN prompt + KZ input 117/500
EN prompt + KZ input 118/500
EN prompt + KZ input 119/500
EN prompt + KZ input 120/500
EN prompt + KZ input 121/500
EN prompt + KZ input 122/500
EN prompt + KZ input 123/500
EN prompt + KZ input 124/500
EN prompt + KZ input 125/500
EN prompt + KZ input 126/500
EN prompt + KZ input 127/500
EN prompt + KZ input 128/500
EN prompt + KZ input 129/500
EN prompt + KZ input 130/500
EN prompt + KZ input 131/500
EN prompt + KZ input 132/500
EN prompt + KZ input 133/500
EN prompt + KZ input 134/500
EN prompt + KZ input 135/500
EN prompt + KZ input 136/500
EN prompt + KZ input 137/500
EN prompt + KZ input 138/500
EN prompt + KZ input 139/500
EN prompt + KZ input 140/500
EN prompt + KZ input 141/500
EN prompt + KZ input 142/500
EN prompt + KZ input 143/500
EN prompt + KZ input 144/500
EN prompt + KZ input 145/500
EN prompt + KZ input 146/500
EN prompt + KZ input 147/500
EN prompt + KZ input 148/500
EN prompt + KZ input 149/500
EN prompt + KZ input 150/500
EN prompt + KZ input 151/500
EN prompt + KZ input 152/500
EN prompt + KZ input 153/500
EN prompt + KZ input 154/500
EN prompt + KZ input 155/500
EN prompt + KZ input 156/500
EN prompt + KZ input 157/500
EN prompt + KZ input 158/500
EN prompt + KZ input 159/500
EN prompt + KZ input 160/500
EN prompt + KZ input 161/500
EN prompt + KZ input 162/500
EN prompt + KZ input 163/500
EN prompt + KZ input 164/500
EN prompt + KZ input 165/500
EN prompt + KZ input 166/500
EN prompt + KZ input 167/500
EN prompt + KZ input 168/500
EN prompt + KZ input 169/500
EN prompt + KZ input 170/500
EN prompt + KZ input 171/500
EN prompt + KZ input 172/500
EN prompt + KZ input 173/500
EN prompt + KZ input 174/500
EN prompt + KZ input 175/500
EN prompt + KZ input 176/500
EN prompt + KZ input 177/500
EN prompt + KZ input 178/500
EN prompt + KZ input 179/500
EN prompt + KZ input 180/500
EN prompt + KZ input 181/500
EN prompt + KZ input 182/500
EN prompt + KZ input 183/500
EN prompt + KZ input 184/500
EN prompt + KZ input 185/500
EN prompt + KZ input 186/500
EN prompt + KZ input 187/500
EN prompt + KZ input 188/500
EN prompt + KZ input 189/500
EN prompt + KZ input 190/500
EN prompt + KZ input 191/500
EN prompt + KZ input 192/500
EN prompt + KZ input 193/500
EN prompt + KZ input 194/500
EN prompt + KZ input 195/500
EN prompt + KZ input 196/500
EN prompt + KZ input 197/500
EN prompt + KZ input 198/500
EN prompt + KZ input 199/500
EN prompt + KZ input 200/500
EN prompt + KZ input 201/500
EN prompt + KZ input 202/500
EN prompt + KZ input 203/500
EN prompt + KZ input 204/500
EN prompt + KZ input 205/500
EN prompt + KZ input 206/500
EN prompt + KZ input 207/500
EN prompt + KZ input 208/500
EN prompt + KZ input 209/500
EN prompt + KZ input 210/500
EN prompt + KZ input 211/500
EN prompt + KZ input 212/500
EN prompt + KZ input 213/500
EN prompt + KZ input 214/500
EN prompt + KZ input 215/500
EN prompt + KZ input 216/500
EN prompt + KZ input 217/500
EN prompt + KZ input 218/500
EN prompt + KZ input 219/500
EN prompt + KZ input 220/500
EN prompt + KZ input 221/500
EN prompt + KZ input 222/500
EN prompt + KZ input 223/500
EN prompt + KZ input 224/500
EN prompt + KZ input 225/500
EN prompt + KZ input 226/500
EN prompt + KZ input 227/500
EN prompt + KZ input 228/500
EN prompt + KZ input 229/500
EN prompt + KZ input 230/500
EN prompt + KZ input 231/500
EN prompt + KZ input 232/500
EN prompt + KZ input 233/500
EN prompt + KZ input 234/500
EN prompt + KZ input 235/500
EN prompt + KZ input 236/500
EN prompt + KZ input 237/500
EN prompt + KZ input 238/500
EN prompt + KZ input 239/500
EN prompt + KZ input 240/500
EN prompt + KZ input 241/500
EN prompt + KZ input 242/500
EN prompt + KZ input 243/500
EN prompt + KZ input 244/500
EN prompt + KZ input 245/500
EN prompt + KZ input 246/500
EN prompt + KZ input 247/500
EN prompt + KZ input 248/500
EN prompt + KZ input 249/500
EN prompt + KZ input 250/500
EN prompt + KZ input 251/500
EN prompt + KZ input 252/500
EN prompt + KZ input 253/500
EN prompt + KZ input 254/500
EN prompt + KZ input 255/500
EN prompt + KZ input 256/500
EN prompt + KZ input 257/500
EN prompt + KZ input 258/500
EN prompt + KZ input 259/500
EN prompt + KZ input 260/500
EN prompt + KZ input 261/500
EN prompt + KZ input 262/500
EN prompt + KZ input 263/500
EN prompt + KZ input 264/500
EN prompt + KZ input 265/500
EN prompt + KZ input 266/500
EN prompt + KZ input 267/500
EN prompt + KZ input 268/500
EN prompt + KZ input 269/500
EN prompt + KZ input 270/500
EN prompt + KZ input 271/500
EN prompt + KZ input 272/500
EN prompt + KZ input 273/500
EN prompt + KZ input 274/500
EN prompt + KZ input 275/500
EN prompt + KZ input 276/500
EN prompt + KZ input 277/500
EN prompt + KZ input 278/500
EN prompt + KZ input 279/500
EN prompt + KZ input 280/500
EN prompt + KZ input 281/500
EN prompt + KZ input 282/500
EN prompt + KZ input 283/500
EN prompt + KZ input 284/500
EN prompt + KZ input 285/500
EN prompt + KZ input 286/500
EN prompt + KZ input 287/500

EN prompt + KZ input 288/500
EN prompt + KZ input 289/500
EN prompt + KZ input 290/500
EN prompt + KZ input 291/500
EN prompt + KZ input 292/500
EN prompt + KZ input 293/500
EN prompt + KZ input 294/500
EN prompt + KZ input 295/500
EN prompt + KZ input 296/500
EN prompt + KZ input 297/500
EN prompt + KZ input 298/500
EN prompt + KZ input 299/500
EN prompt + KZ input 300/500
EN prompt + KZ input 301/500
EN prompt + KZ input 302/500
EN prompt + KZ input 303/500
EN prompt + KZ input 304/500
EN prompt + KZ input 305/500
EN prompt + KZ input 306/500
EN prompt + KZ input 307/500
EN prompt + KZ input 308/500
EN prompt + KZ input 309/500
EN prompt + KZ input 310/500
EN prompt + KZ input 311/500
EN prompt + KZ input 312/500
EN prompt + KZ input 313/500
EN prompt + KZ input 314/500
EN prompt + KZ input 315/500
EN prompt + KZ input 316/500
EN prompt + KZ input 317/500
EN prompt + KZ input 318/500
EN prompt + KZ input 319/500
EN prompt + KZ input 320/500
EN prompt + KZ input 321/500
EN prompt + KZ input 322/500
EN prompt + KZ input 323/500
EN prompt + KZ input 324/500
EN prompt + KZ input 325/500
EN prompt + KZ input 326/500
EN prompt + KZ input 327/500
EN prompt + KZ input 328/500
EN prompt + KZ input 329/500
EN prompt + KZ input 330/500
EN prompt + KZ input 331/500
EN prompt + KZ input 332/500
EN prompt + KZ input 333/500
EN prompt + KZ input 334/500
EN prompt + KZ input 335/500
EN prompt + KZ input 336/500
EN prompt + KZ input 337/500
EN prompt + KZ input 338/500
EN prompt + KZ input 339/500
EN prompt + KZ input 340/500
EN prompt + KZ input 341/500
EN prompt + KZ input 342/500
EN prompt + KZ input 343/500
EN prompt + KZ input 344/500
EN prompt + KZ input 345/500
EN prompt + KZ input 346/500
EN prompt + KZ input 347/500
EN prompt + KZ input 348/500
EN prompt + KZ input 349/500
EN prompt + KZ input 350/500
EN prompt + KZ input 351/500
EN prompt + KZ input 352/500
EN prompt + KZ input 353/500
EN prompt + KZ input 354/500
EN prompt + KZ input 355/500
EN prompt + KZ input 356/500
EN prompt + KZ input 357/500
EN prompt + KZ input 358/500
EN prompt + KZ input 359/500
EN prompt + KZ input 360/500
EN prompt + KZ input 361/500
EN prompt + KZ input 362/500
EN prompt + KZ input 363/500
EN prompt + KZ input 364/500
EN prompt + KZ input 365/500
EN prompt + KZ input 366/500
EN prompt + KZ input 367/500
EN prompt + KZ input 368/500
EN prompt + KZ input 369/500
EN prompt + KZ input 370/500
EN prompt + KZ input 371/500
EN prompt + KZ input 372/500
EN prompt + KZ input 373/500
EN prompt + KZ input 374/500
EN prompt + KZ input 375/500
EN prompt + KZ input 376/500
EN prompt + KZ input 377/500
EN prompt + KZ input 378/500
EN prompt + KZ input 379/500
EN prompt + KZ input 380/500
EN prompt + KZ input 381/500
EN prompt + KZ input 382/500
EN prompt + KZ input 383/500
EN prompt + KZ input 384/500
EN prompt + KZ input 385/500
EN prompt + KZ input 386/500
EN prompt + KZ input 387/500
EN prompt + KZ input 388/500
EN prompt + KZ input 389/500
EN prompt + KZ input 390/500
EN prompt + KZ input 391/500
EN prompt + KZ input 392/500
EN prompt + KZ input 393/500
EN prompt + KZ input 394/500
EN prompt + KZ input 395/500
EN prompt + KZ input 396/500
EN prompt + KZ input 397/500
EN prompt + KZ input 398/500
EN prompt + KZ input 399/500
EN prompt + KZ input 400/500
EN prompt + KZ input 401/500
EN prompt + KZ input 402/500
EN prompt + KZ input 403/500
EN prompt + KZ input 404/500
EN prompt + KZ input 405/500
EN prompt + KZ input 406/500
EN prompt + KZ input 407/500
EN prompt + KZ input 408/500
EN prompt + KZ input 409/500
EN prompt + KZ input 410/500
EN prompt + KZ input 411/500
EN prompt + KZ input 412/500
EN prompt + KZ input 413/500
EN prompt + KZ input 414/500
EN prompt + KZ input 415/500
EN prompt + KZ input 416/500
EN prompt + KZ input 417/500
EN prompt + KZ input 418/500
EN prompt + KZ input 419/500
EN prompt + KZ input 420/500
EN prompt + KZ input 421/500
EN prompt + KZ input 422/500
EN prompt + KZ input 423/500
EN prompt + KZ input 424/500
EN prompt + KZ input 425/500
EN prompt + KZ input 426/500
EN prompt + KZ input 427/500
EN prompt + KZ input 428/500
EN prompt + KZ input 429/500
EN prompt + KZ input 430/500
EN prompt + KZ input 431/500
EN prompt + KZ input 432/500
EN prompt + KZ input 433/500
EN prompt + KZ input 434/500
EN prompt + KZ input 435/500
EN prompt + KZ input 436/500
EN prompt + KZ input 437/500
EN prompt + KZ input 438/500
EN prompt + KZ input 439/500
EN prompt + KZ input 440/500
EN prompt + KZ input 441/500
EN prompt + KZ input 442/500
EN prompt + KZ input 443/500
EN prompt + KZ input 444/500
EN prompt + KZ input 445/500
EN prompt + KZ input 446/500
EN prompt + KZ input 447/500
EN prompt + KZ input 448/500
EN prompt + KZ input 449/500
EN prompt + KZ input 450/500
EN prompt + KZ input 451/500
EN prompt + KZ input 452/500
EN prompt + KZ input 453/500
EN prompt + KZ input 454/500
EN prompt + KZ input 455/500
EN prompt + KZ input 456/500
EN prompt + KZ input 457/500
EN prompt + KZ input 458/500
EN prompt + KZ input 459/500
EN prompt + KZ input 460/500
EN prompt + KZ input 461/500
EN prompt + KZ input 462/500
EN prompt + KZ input 463/500
EN prompt + KZ input 464/500
EN prompt + KZ input 465/500
EN prompt + KZ input 466/500
EN prompt + KZ input 467/500
EN prompt + KZ input 468/500
EN prompt + KZ input 469/500
EN prompt + KZ input 470/500
EN prompt + KZ input 471/500
EN prompt + KZ input 472/500
EN prompt + KZ input 473/500
EN prompt + KZ input 474/500
EN prompt + KZ input 475/500
EN prompt + KZ input 476/500
EN prompt + KZ input 477/500
EN prompt + KZ input 478/500
EN prompt + KZ input 479/500
EN prompt + KZ input 480/500
EN prompt + KZ input 481/500
EN prompt + KZ input 482/500
EN prompt + KZ input 483/500
EN prompt + KZ input 484/500
EN prompt + KZ input 485/500
EN prompt + KZ input 486/500
EN prompt + KZ input 487/500
EN prompt + KZ input 488/500
EN prompt + KZ input 489/500
EN prompt + KZ input 490/500
EN prompt + KZ input 491/500
EN prompt + KZ input 492/500
EN prompt + KZ input 493/500
EN prompt + KZ input 494/500
EN prompt + KZ input 495/500
EN prompt + KZ input 496/500
EN prompt + KZ input 497/500
EN prompt + KZ input 498/500
EN prompt + KZ input 499/500
EN prompt + KZ input 500/500
Finished EN prompt + KZ input experiment

In [16]:
y_true = df["answer_key"].str.strip().str.upper()
y_pred = df["pred_en_kz"].str.strip().str.upper()

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred))

Accuracy: 0.758
              precision    recall  f1-score   support

           A       0.79      0.84      0.81       100
           B       0.80      0.76      0.78       118
           C       0.71      0.69      0.70        87
           D       0.77      0.74      0.75       102
           E       0.71      0.75      0.73        93

    accuracy                           0.76       500
   macro avg       0.76      0.76      0.76       500
weighted avg       0.76      0.76      0.76       500

In [ ]:
def csqa_cot_kz_predict(question_kz: str, options_kz: str) -> str:
    prompt = f"""Сен commonsense логика бойынша сарапшысың.

Төмендегі көп таңдаулы сұраққа жауап бер.
Алдымен қысқаша (1–2 сөйлем) ойыңды жаз, содан кейін соңғы жауапты бер.

Формат (міндетті):
Ой: <қысқаша reasoning>
Жауап: <A/B/C/D/E>

СҰРАҚ:
{question_kz}

НҰСҚАЛАР:
{options_kz}
"""
    resp = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role": "user", "content": prompt}],
    )
    out = resp.choices[0].message.content.strip().upper()

    # Prefer "ЖАУАП: X" / "ANSWER: X"
    m = re.search(r"(ЖАУАП|ANSWER)\s*:\s*([ABCDE])", out)
    if m:
        return m.group(2)

    # fallback: first standalone letter
    m2 = re.search(r"\b([ABCDE])\b", out)
    return m2.group(1) if m2 else out

In [19]:
def csqa_cot_kz(question_kz, options_kz):

    prompt = f"""Сен күнделікті өмірдегі логикалық сұрақтарды жақсы түсінетін сарапшысың.

Төмендегі көп таңдаулы сұраққа жауап бер.

Алдымен қысқаша ойыңды жаз (1–2 сөйлем).
Содан кейін соңғы жауапты жаңа жолда дәл мына форматта жаз:

Жауап: <A/B/C/D/E>

Сұрақ:
{question_kz}

Жауап нұсқалары:
{options_kz}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role":"user","content":prompt}]
    )

    output = response.choices[0].message.content.strip().upper()

    match = re.search(r"ЖАУАП\s*:\s*([ABCDE])", output)

    if match:
        return match.group(1)

    # fallback
    match2 = re.search(r"[ABCDE]", output)
    return match2.group(0) if match2 else output

In [18]:
for i in range(5):

    pred = csqa_cot_kz(
        df.loc[i,"question_kz"],
        df.loc[i,"options_kz"]
    )

    print(i, "pred:", pred, "gold:", df.loc[i,"answer_key"])

0 pred: B gold: B
1 pred: A gold: A
2 pred: E gold: E
3 pred: A gold: A
4 pred: E gold: E

In [20]:
import time

df["pred_cot_kz"] = ""

for i in range(len(df)):

    print(f"Kazakh CoT {i+1}/500")

    df.loc[i,"pred_cot_kz"] = csqa_cot_kz(
        df.loc[i,"question_kz"],
        df.loc[i,"options_kz"]
    )

    if (i+1) % 25 == 0:
        df.to_csv("csqa_cot_kz_progress.csv", index=False)

    time.sleep(0.25)

df.to_csv("csqa_cot_kz_final.csv", index=False)

print("Kazakh CoT experiment finished")

Kazakh CoT 1/500
Kazakh CoT 2/500
Kazakh CoT 3/500
Kazakh CoT 4/500
Kazakh CoT 5/500
Kazakh CoT 6/500
Kazakh CoT 7/500
Kazakh CoT 8/500
Kazakh CoT 9/500
Kazakh CoT 10/500
Kazakh CoT 11/500
Kazakh CoT 12/500
Kazakh CoT 13/500
Kazakh CoT 14/500
Kazakh CoT 15/500
Kazakh CoT 16/500
Kazakh CoT 17/500
Kazakh CoT 18/500
Kazakh CoT 19/500
Kazakh CoT 20/500
Kazakh CoT 21/500
Kazakh CoT 22/500
Kazakh CoT 23/500
Kazakh CoT 24/500
Kazakh CoT 25/500
Kazakh CoT 26/500
Kazakh CoT 27/500
Kazakh CoT 28/500
Kazakh CoT 29/500
Kazakh CoT 30/500
Kazakh CoT 31/500
Kazakh CoT 32/500
Kazakh CoT 33/500
Kazakh CoT 34/500
Kazakh CoT 35/500
Kazakh CoT 36/500
Kazakh CoT 37/500
Kazakh CoT 38/500
Kazakh CoT 39/500
Kazakh CoT 40/500
Kazakh CoT 41/500
Kazakh CoT 42/500
Kazakh CoT 43/500
Kazakh CoT 44/500
Kazakh CoT 45/500
Kazakh CoT 46/500
Kazakh CoT 47/500
Kazakh CoT 48/500
Kazakh CoT 49/500
Kazakh CoT 50/500
Kazakh CoT 51/500
Kazakh CoT 52/500
Kazakh CoT 53/500
Kazakh CoT 54/500
Kazakh CoT 55/500
Kazakh CoT 56/500
Kazakh CoT 57/500
Kazakh CoT 58/500
Kazakh CoT 59/500
Kazakh CoT 60/500
Kazakh CoT 61/500
Kazakh CoT 62/500
Kazakh CoT 63/500
Kazakh CoT 64/500
Kazakh CoT 65/500
Kazakh CoT 66/500
Kazakh CoT 67/500
Kazakh CoT 68/500
Kazakh CoT 69/500
Kazakh CoT 70/500
Kazakh CoT 71/500
Kazakh CoT 72/500
Kazakh CoT 73/500
Kazakh CoT 74/500
Kazakh CoT 75/500
Kazakh CoT 76/500
Kazakh CoT 77/500
Kazakh CoT 78/500
Kazakh CoT 79/500
Kazakh CoT 80/500
Kazakh CoT 81/500
Kazakh CoT 82/500
Kazakh CoT 83/500
Kazakh CoT 84/500
Kazakh CoT 85/500
Kazakh CoT 86/500
Kazakh CoT 87/500
Kazakh CoT 88/500
Kazakh CoT 89/500
Kazakh CoT 90/500
Kazakh CoT 91/500
Kazakh CoT 92/500
Kazakh CoT 93/500
Kazakh CoT 94/500
Kazakh CoT 95/500
Kazakh CoT 96/500
Kazakh CoT 97/500
Kazakh CoT 98/500
Kazakh CoT 99/500
Kazakh CoT 100/500
Kazakh CoT 101/500
Kazakh CoT 102/500
Kazakh CoT 103/500
Kazakh CoT 104/500
Kazakh CoT 105/500
Kazakh CoT 106/500
Kazakh CoT 107/500
Kazakh CoT 108/500
Kazakh CoT 109/500
Kazakh CoT 110/500
Kazakh CoT 111/500
Kazakh CoT 112/500
Kazakh CoT 113/500
Kazakh CoT 114/500
Kazakh CoT 115/500
Kazakh CoT 116/500
Kazakh CoT 117/500
Kazakh CoT 118/500
Kazakh CoT 119/500
Kazakh CoT 120/500
Kazakh CoT 121/500
Kazakh CoT 122/500
Kazakh CoT 123/500
Kazakh CoT 124/500
Kazakh CoT 125/500
Kazakh CoT 126/500
Kazakh CoT 127/500
Kazakh CoT 128/500
Kazakh CoT 129/500
Kazakh CoT 130/500
Kazakh CoT 131/500
Kazakh CoT 132/500
Kazakh CoT 133/500
Kazakh CoT 134/500
Kazakh CoT 135/500
Kazakh CoT 136/500
Kazakh CoT 137/500
Kazakh CoT 138/500
Kazakh CoT 139/500
Kazakh CoT 140/500
Kazakh CoT 141/500
Kazakh CoT 142/500
Kazakh CoT 143/500
Kazakh CoT 144/500
Kazakh CoT 145/500
Kazakh CoT 146/500
Kazakh CoT 147/500
Kazakh CoT 148/500
Kazakh CoT 149/500
Kazakh CoT 150/500
Kazakh CoT 151/500
Kazakh CoT 152/500
Kazakh CoT 153/500
Kazakh CoT 154/500
Kazakh CoT 155/500
Kazakh CoT 156/500
Kazakh CoT 157/500
Kazakh CoT 158/500
Kazakh CoT 159/500
Kazakh CoT 160/500
Kazakh CoT 161/500
Kazakh CoT 162/500
Kazakh CoT 163/500
Kazakh CoT 164/500
Kazakh CoT 165/500
Kazakh CoT 166/500
Kazakh CoT 167/500
Kazakh CoT 168/500
Kazakh CoT 169/500
Kazakh CoT 170/500
Kazakh CoT 171/500
Kazakh CoT 172/500
Kazakh CoT 173/500
Kazakh CoT 174/500
Kazakh CoT 175/500
Kazakh CoT 176/500
Kazakh CoT 177/500
Kazakh CoT 178/500
Kazakh CoT 179/500
Kazakh CoT 180/500
Kazakh CoT 181/500
Kazakh CoT 182/500
Kazakh CoT 183/500
Kazakh CoT 184/500
Kazakh CoT 185/500
Kazakh CoT 186/500
Kazakh CoT 187/500
Kazakh CoT 188/500
Kazakh CoT 189/500
Kazakh CoT 190/500
Kazakh CoT 191/500
Kazakh CoT 192/500
Kazakh CoT 193/500
Kazakh CoT 194/500
Kazakh CoT 195/500
Kazakh CoT 196/500
Kazakh CoT 197/500
Kazakh CoT 198/500
Kazakh CoT 199/500
Kazakh CoT 200/500
Kazakh CoT 201/500
Kazakh CoT 202/500
Kazakh CoT 203/500
Kazakh CoT 204/500
Kazakh CoT 205/500
Kazakh CoT 206/500
Kazakh CoT 207/500
Kazakh CoT 208/500
Kazakh CoT 209/500
Kazakh CoT 210/500
Kazakh CoT 211/500
Kazakh CoT 212/500
Kazakh CoT 213/500
Kazakh CoT 214/500
Kazakh CoT 215/500
Kazakh CoT 216/500
Kazakh CoT 217/500
Kazakh CoT 218/500
Kazakh CoT 219/500
Kazakh CoT 220/500
Kazakh CoT 221/500
Kazakh CoT 222/500
Kazakh CoT 223/500
Kazakh CoT 224/500
Kazakh CoT 225/500
Kazakh CoT 226/500
Kazakh CoT 227/500
Kazakh CoT 228/500
Kazakh CoT 229/500
Kazakh CoT 230/500
Kazakh CoT 231/500
Kazakh CoT 232/500
Kazakh CoT 233/500
Kazakh CoT 234/500
Kazakh CoT 235/500
Kazakh CoT 236/500
Kazakh CoT 237/500
Kazakh CoT 238/500
Kazakh CoT 239/500
Kazakh CoT 240/500
Kazakh CoT 241/500
Kazakh CoT 242/500
Kazakh CoT 243/500
Kazakh CoT 244/500
Kazakh CoT 245/500
Kazakh CoT 246/500
Kazakh CoT 247/500
Kazakh CoT 248/500
Kazakh CoT 249/500
Kazakh CoT 250/500
Kazakh CoT 251/500
Kazakh CoT 252/500
Kazakh CoT 253/500
Kazakh CoT 254/500
Kazakh CoT 255/500
Kazakh CoT 256/500
Kazakh CoT 257/500
Kazakh CoT 258/500
Kazakh CoT 259/500
Kazakh CoT 260/500
Kazakh CoT 261/500
Kazakh CoT 262/500
Kazakh CoT 263/500
Kazakh CoT 264/500
Kazakh CoT 265/500
Kazakh CoT 266/500
Kazakh CoT 267/500
Kazakh CoT 268/500
Kazakh CoT 269/500
Kazakh CoT 270/500
Kazakh CoT 271/500
Kazakh CoT 272/500
Kazakh CoT 273/500
Kazakh CoT 274/500
Kazakh CoT 275/500
Kazakh CoT 276/500
Kazakh CoT 277/500
Kazakh CoT 278/500
Kazakh CoT 279/500
Kazakh CoT 280/500
Kazakh CoT 281/500
Kazakh CoT 282/500
Kazakh CoT 283/500
Kazakh CoT 284/500
Kazakh CoT 285/500
Kazakh CoT 286/500
Kazakh CoT 287/500
Kazakh CoT 288/500
Kazakh CoT 289/500
Kazakh CoT 290/500
Kazakh CoT 291/500
Kazakh CoT 292/500
Kazakh CoT 293/500
Kazakh CoT 294/500
Kazakh CoT 295/500
Kazakh CoT 296/500
Kazakh CoT 297/500
Kazakh CoT 298/500
Kazakh CoT 299/500
Kazakh CoT 300/500
Kazakh CoT 301/500
Kazakh CoT 302/500
Kazakh CoT 303/500
Kazakh CoT 304/500
Kazakh CoT 305/500
Kazakh CoT 306/500
Kazakh CoT 307/500
Kazakh CoT 308/500
Kazakh CoT 309/500
Kazakh CoT 310/500
Kazakh CoT 311/500
Kazakh CoT 312/500
Kazakh CoT 313/500
Kazakh CoT 314/500
Kazakh CoT 315/500
Kazakh CoT 316/500
Kazakh CoT 317/500
Kazakh CoT 318/500
Kazakh CoT 319/500
Kazakh CoT 320/500
Kazakh CoT 321/500
Kazakh CoT 322/500
Kazakh CoT 323/500
Kazakh CoT 324/500
Kazakh CoT 325/500
Kazakh CoT 326/500
Kazakh CoT 327/500
Kazakh CoT 328/500
Kazakh CoT 329/500
Kazakh CoT 330/500
Kazakh CoT 331/500
Kazakh CoT 332/500
Kazakh CoT 333/500
Kazakh CoT 334/500
Kazakh CoT 335/500
Kazakh CoT 336/500
Kazakh CoT 337/500
Kazakh CoT 338/500
Kazakh CoT 339/500
Kazakh CoT 340/500
Kazakh CoT 341/500
Kazakh CoT 342/500
Kazakh CoT 343/500
Kazakh CoT 344/500
Kazakh CoT 345/500
Kazakh CoT 346/500
Kazakh CoT 347/500
Kazakh CoT 348/500
Kazakh CoT 349/500
Kazakh CoT 350/500
Kazakh CoT 351/500
Kazakh CoT 352/500
Kazakh CoT 353/500
Kazakh CoT 354/500
Kazakh CoT 355/500
Kazakh CoT 356/500
Kazakh CoT 357/500
Kazakh CoT 358/500
Kazakh CoT 359/500
Kazakh CoT 360/500
Kazakh CoT 361/500
Kazakh CoT 362/500
Kazakh CoT 363/500
Kazakh CoT 364/500
Kazakh CoT 365/500
Kazakh CoT 366/500
Kazakh CoT 367/500
Kazakh CoT 368/500
Kazakh CoT 369/500
Kazakh CoT 370/500
Kazakh CoT 371/500
Kazakh CoT 372/500
Kazakh CoT 373/500
Kazakh CoT 374/500
Kazakh CoT 375/500
Kazakh CoT 376/500
Kazakh CoT 377/500
Kazakh CoT 378/500
Kazakh CoT 379/500
Kazakh CoT 380/500
Kazakh CoT 381/500
Kazakh CoT 382/500
Kazakh CoT 383/500
Kazakh CoT 384/500
Kazakh CoT 385/500
Kazakh CoT 386/500
Kazakh CoT 387/500
Kazakh CoT 388/500
Kazakh CoT 389/500
Kazakh CoT 390/500
Kazakh CoT 391/500
Kazakh CoT 392/500
Kazakh CoT 393/500
Kazakh CoT 394/500
Kazakh CoT 395/500
Kazakh CoT 396/500
Kazakh CoT 397/500
Kazakh CoT 398/500
Kazakh CoT 399/500
Kazakh CoT 400/500
Kazakh CoT 401/500
Kazakh CoT 402/500
Kazakh CoT 403/500
Kazakh CoT 404/500
Kazakh CoT 405/500
Kazakh CoT 406/500
Kazakh CoT 407/500
Kazakh CoT 408/500
Kazakh CoT 409/500
Kazakh CoT 410/500
Kazakh CoT 411/500
Kazakh CoT 412/500
Kazakh CoT 413/500
Kazakh CoT 414/500
Kazakh CoT 415/500
Kazakh CoT 416/500
Kazakh CoT 417/500
Kazakh CoT 418/500
Kazakh CoT 419/500
Kazakh CoT 420/500
Kazakh CoT 421/500
Kazakh CoT 422/500
Kazakh CoT 423/500
Kazakh CoT 424/500
Kazakh CoT 425/500
Kazakh CoT 426/500
Kazakh CoT 427/500
Kazakh CoT 428/500
Kazakh CoT 429/500
Kazakh CoT 430/500
Kazakh CoT 431/500
Kazakh CoT 432/500
Kazakh CoT 433/500
Kazakh CoT 434/500
Kazakh CoT 435/500
Kazakh CoT 436/500
Kazakh CoT 437/500

Kazakh CoT 438/500
Kazakh CoT 439/500
Kazakh CoT 440/500
Kazakh CoT 441/500
Kazakh CoT 442/500
Kazakh CoT 443/500
Kazakh CoT 444/500
Kazakh CoT 445/500
Kazakh CoT 446/500
Kazakh CoT 447/500
Kazakh CoT 448/500
Kazakh CoT 449/500
Kazakh CoT 450/500
Kazakh CoT 451/500
Kazakh CoT 452/500
Kazakh CoT 453/500
Kazakh CoT 454/500
Kazakh CoT 455/500
Kazakh CoT 456/500
Kazakh CoT 457/500
Kazakh CoT 458/500
Kazakh CoT 459/500
Kazakh CoT 460/500
Kazakh CoT 461/500
Kazakh CoT 462/500
Kazakh CoT 463/500
Kazakh CoT 464/500
Kazakh CoT 465/500
Kazakh CoT 466/500
Kazakh CoT 467/500
Kazakh CoT 468/500
Kazakh CoT 469/500
Kazakh CoT 470/500
Kazakh CoT 471/500
Kazakh CoT 472/500
Kazakh CoT 473/500
Kazakh CoT 474/500
Kazakh CoT 475/500
Kazakh CoT 476/500
Kazakh CoT 477/500
Kazakh CoT 478/500
Kazakh CoT 479/500
Kazakh CoT 480/500
Kazakh CoT 481/500
Kazakh CoT 482/500
Kazakh CoT 483/500
Kazakh CoT 484/500
Kazakh CoT 485/500
Kazakh CoT 486/500
Kazakh CoT 487/500
Kazakh CoT 488/500
Kazakh CoT 489/500
Kazakh CoT 490/500
Kazakh CoT 491/500
Kazakh CoT 492/500
Kazakh CoT 493/500
Kazakh CoT 494/500
Kazakh CoT 495/500
Kazakh CoT 496/500
Kazakh CoT 497/500
Kazakh CoT 498/500
Kazakh CoT 499/500
Kazakh CoT 500/500
Kazakh CoT experiment finished

In [21]:
y_true = df["answer_key"].str.strip().str.upper()
y_pred = df["pred_cot_kz"].str.strip().str.upper()

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred))

Accuracy: 0.722
              precision    recall  f1-score   support

           A       0.75      0.78      0.76       100
           B       0.75      0.73      0.74       118
           C       0.67      0.61      0.64        87
           D       0.71      0.77      0.74       102
           E       0.72      0.70      0.71        93

    accuracy                           0.72       500
   macro avg       0.72      0.72      0.72       500
weighted avg       0.72      0.72      0.72       500

In [22]:
def csqa_cot_en(question, options):

    prompt = f"""You are a commonsense reasoning expert.

Solve the multiple-choice question below.

First think step by step about the problem.
Then give the final answer on a new line in this exact format:

Answer: <A/B/C/D/E>

Question:
{question}

Choices:
{options}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role":"user","content":prompt}]
    )

    output = response.choices[0].message.content.strip().upper()

    match = re.search(r"ANSWER\s*:\s*([ABCDE])", output)

    if match:
        return match.group(1)

    # fallback
    match2 = re.search(r"[ABCDE]", output)
    return match2.group(0) if match2 else output

In [23]:
for i in range(5):

    pred = csqa_cot_en(
        df.loc[i,"question"],
        df.loc[i,"options"]
    )

    print(i, "pred:", pred, "gold:", df.loc[i,"answer_key"])

0 pred: B gold: B
1 pred: A gold: A
2 pred: E gold: E
3 pred: A gold: A
4 pred: E gold: E

In [24]:
df["pred_cot_en"] = ""

for i in range(len(df)):

    print(f"English CoT {i+1}/500")

    df.loc[i,"pred_cot_en"] = csqa_cot_en(
        df.loc[i,"question"],
        df.loc[i,"options"]
    )

    if (i+1) % 25 == 0:
        df.to_csv("csqa_cot_en_progress.csv", index=False)

    time.sleep(0.25)

df.to_csv("csqa_cot_en_final.csv", index=False)

print("English CoT experiment finished")

English CoT 1/500
English CoT 2/500
English CoT 3/500
English CoT 4/500
English CoT 5/500
English CoT 6/500
English CoT 7/500
English CoT 8/500
English CoT 9/500
English CoT 10/500
English CoT 11/500
English CoT 12/500
English CoT 13/500
English CoT 14/500
English CoT 15/500
English CoT 16/500
English CoT 17/500
English CoT 18/500
English CoT 19/500
English CoT 20/500
English CoT 21/500
English CoT 22/500
English CoT 23/500
English CoT 24/500
English CoT 25/500
English CoT 26/500
English CoT 27/500
English CoT 28/500
English CoT 29/500
English CoT 30/500
English CoT 31/500
English CoT 32/500
English CoT 33/500
English CoT 34/500
English CoT 35/500
English CoT 36/500
English CoT 37/500
English CoT 38/500
English CoT 39/500
English CoT 40/500
English CoT 41/500
English CoT 42/500
English CoT 43/500
English CoT 44/500
English CoT 45/500
English CoT 46/500
English CoT 47/500
English CoT 48/500
English CoT 49/500
English CoT 50/500
English CoT 51/500
English CoT 52/500
English CoT 53/500
English CoT 54/500
English CoT 55/500
English CoT 56/500
English CoT 57/500
English CoT 58/500
English CoT 59/500
English CoT 60/500
English CoT 61/500
English CoT 62/500
English CoT 63/500
English CoT 64/500
English CoT 65/500
English CoT 66/500
English CoT 67/500
English CoT 68/500
English CoT 69/500
English CoT 70/500
English CoT 71/500
English CoT 72/500
English CoT 73/500
English CoT 74/500
English CoT 75/500
English CoT 76/500
English CoT 77/500
English CoT 78/500
English CoT 79/500
English CoT 80/500
English CoT 81/500
English CoT 82/500
English CoT 83/500
English CoT 84/500
English CoT 85/500
English CoT 86/500
English CoT 87/500
English CoT 88/500
English CoT 89/500
English CoT 90/500
English CoT 91/500
English CoT 92/500
English CoT 93/500
English CoT 94/500
English CoT 95/500
English CoT 96/500
English CoT 97/500
English CoT 98/500
English CoT 99/500
English CoT 100/500
English CoT 101/500
English CoT 102/500
English CoT 103/500
English CoT 104/500
English CoT 105/500
English CoT 106/500
English CoT 107/500
English CoT 108/500
English CoT 109/500
English CoT 110/500
English CoT 111/500
English CoT 112/500
English CoT 113/500
English CoT 114/500
English CoT 115/500
English CoT 116/500
English CoT 117/500
English CoT 118/500
English CoT 119/500
English CoT 120/500
English CoT 121/500
English CoT 122/500
English CoT 123/500
English CoT 124/500
English CoT 125/500
English CoT 126/500
English CoT 127/500
English CoT 128/500
English CoT 129/500
English CoT 130/500
English CoT 131/500
English CoT 132/500
English CoT 133/500
English CoT 134/500
English CoT 135/500
English CoT 136/500
English CoT 137/500
English CoT 138/500
English CoT 139/500
English CoT 140/500
English CoT 141/500
English CoT 142/500
English CoT 143/500
English CoT 144/500
English CoT 145/500
English CoT 146/500
English CoT 147/500
English CoT 148/500
English CoT 149/500
English CoT 150/500
English CoT 151/500
English CoT 152/500
English CoT 153/500
English CoT 154/500
English CoT 155/500
English CoT 156/500
English CoT 157/500
English CoT 158/500
English CoT 159/500
English CoT 160/500
English CoT 161/500
English CoT 162/500
English CoT 163/500
English CoT 164/500
English CoT 165/500
English CoT 166/500
English CoT 167/500
English CoT 168/500
English CoT 169/500
English CoT 170/500
English CoT 171/500
English CoT 172/500
English CoT 173/500
English CoT 174/500
English CoT 175/500
English CoT 176/500
English CoT 177/500
English CoT 178/500
English CoT 179/500
English CoT 180/500
English CoT 181/500
English CoT 182/500
English CoT 183/500
English CoT 184/500
English CoT 185/500
English CoT 186/500
English CoT 187/500
English CoT 188/500
English CoT 189/500
English CoT 190/500
English CoT 191/500
English CoT 192/500
English CoT 193/500
English CoT 194/500
English CoT 195/500
English CoT 196/500
English CoT 197/500
English CoT 198/500
English CoT 199/500
English CoT 200/500
English CoT 201/500
English CoT 202/500
English CoT 203/500
English CoT 204/500
English CoT 205/500
English CoT 206/500
English CoT 207/500
English CoT 208/500
English CoT 209/500
English CoT 210/500
English CoT 211/500
English CoT 212/500
English CoT 213/500
English CoT 214/500
English CoT 215/500
English CoT 216/500
English CoT 217/500
English CoT 218/500
English CoT 219/500
English CoT 220/500
English CoT 221/500
English CoT 222/500
English CoT 223/500
English CoT 224/500
English CoT 225/500
English CoT 226/500
English CoT 227/500
English CoT 228/500
English CoT 229/500
English CoT 230/500
English CoT 231/500
English CoT 232/500
English CoT 233/500
English CoT 234/500
English CoT 235/500
English CoT 236/500
English CoT 237/500
English CoT 238/500
English CoT 239/500
English CoT 240/500
English CoT 241/500
English CoT 242/500
English CoT 243/500
English CoT 244/500
English CoT 245/500
English CoT 246/500
English CoT 247/500
English CoT 248/500
English CoT 249/500
English CoT 250/500
English CoT 251/500
English CoT 252/500
English CoT 253/500
English CoT 254/500
English CoT 255/500
English CoT 256/500
English CoT 257/500
English CoT 258/500
English CoT 259/500
English CoT 260/500
English CoT 261/500
English CoT 262/500
English CoT 263/500
English CoT 264/500
English CoT 265/500
English CoT 266/500
English CoT 267/500
English CoT 268/500
English CoT 269/500
English CoT 270/500
English CoT 271/500
English CoT 272/500
English CoT 273/500
English CoT 274/500
English CoT 275/500
English CoT 276/500
English CoT 277/500
English CoT 278/500
English CoT 279/500
English CoT 280/500
English CoT 281/500
English CoT 282/500
English CoT 283/500
English CoT 284/500
English CoT 285/500
English CoT 286/500
English CoT 287/500
English CoT 288/500
English CoT 289/500
English CoT 290/500
English CoT 291/500
English CoT 292/500
English CoT 293/500
English CoT 294/500
English CoT 295/500
English CoT 296/500
English CoT 297/500
English CoT 298/500
English CoT 299/500
English CoT 300/500
English CoT 301/500
English CoT 302/500
English CoT 303/500
English CoT 304/500
English CoT 305/500
English CoT 306/500
English CoT 307/500
English CoT 308/500
English CoT 309/500
English CoT 310/500
English CoT 311/500
English CoT 312/500
English CoT 313/500
English CoT 314/500
English CoT 315/500
English CoT 316/500
English CoT 317/500
English CoT 318/500
English CoT 319/500
English CoT 320/500
English CoT 321/500
English CoT 322/500
English CoT 323/500
English CoT 324/500
English CoT 325/500
English CoT 326/500
English CoT 327/500
English CoT 328/500
English CoT 329/500
English CoT 330/500
English CoT 331/500
English CoT 332/500
English CoT 333/500
English CoT 334/500
English CoT 335/500
English CoT 336/500
English CoT 337/500
English CoT 338/500
English CoT 339/500
English CoT 340/500
English CoT 341/500
English CoT 342/500
English CoT 343/500
English CoT 344/500
English CoT 345/500
English CoT 346/500
English CoT 347/500
English CoT 348/500
English CoT 349/500
English CoT 350/500
English CoT 351/500
English CoT 352/500
English CoT 353/500
English CoT 354/500
English CoT 355/500
English CoT 356/500
English CoT 357/500
English CoT 358/500
English CoT 359/500
English CoT 360/500
English CoT 361/500
English CoT 362/500
English CoT 363/500
English CoT 364/500
English CoT 365/500
English CoT 366/500
English CoT 367/500
English CoT 368/500
English CoT 369/500
English CoT 370/500
English CoT 371/500
English CoT 372/500
English CoT 373/500
English CoT 374/500
English CoT 375/500
English CoT 376/500
English CoT 377/500
English CoT 378/500
English CoT 379/500
English CoT 380/500
English CoT 381/500
English CoT 382/500
English CoT 383/500
English CoT 384/500
English CoT 385/500
English CoT 386/500
English CoT 387/500
English CoT 388/500
English CoT 389/500
English CoT 390/500
English CoT 391/500
English CoT 392/500
English CoT 393/500
English CoT 394/500
English CoT 395/500
English CoT 396/500
English CoT 397/500
English CoT 398/500
English CoT 399/500
English CoT 400/500
English CoT 401/500
English CoT 402/500
English CoT 403/500
English CoT 404/500
English CoT 405/500
English CoT 406/500
English CoT 407/500
English CoT 408/500
English CoT 409/500
English CoT 410/500
English CoT 411/500
English CoT 412/500
English CoT 413/500
English CoT 414/500
English CoT 415/500
English CoT 416/500

English CoT 417/500
English CoT 418/500
English CoT 419/500
English CoT 420/500
English CoT 421/500
English CoT 422/500
English CoT 423/500
English CoT 424/500
English CoT 425/500
English CoT 426/500
English CoT 427/500
English CoT 428/500
English CoT 429/500
English CoT 430/500
English CoT 431/500
English CoT 432/500
English CoT 433/500
English CoT 434/500
English CoT 435/500
English CoT 436/500
English CoT 437/500
English CoT 438/500
English CoT 439/500
English CoT 440/500
English CoT 441/500
English CoT 442/500
English CoT 443/500
English CoT 444/500
English CoT 445/500
English CoT 446/500
English CoT 447/500
English CoT 448/500
English CoT 449/500
English CoT 450/500
English CoT 451/500
English CoT 452/500
English CoT 453/500
English CoT 454/500
English CoT 455/500
English CoT 456/500
English CoT 457/500
English CoT 458/500
English CoT 459/500
English CoT 460/500
English CoT 461/500
English CoT 462/500
English CoT 463/500
English CoT 464/500
English CoT 465/500
English CoT 466/500
English CoT 467/500
English CoT 468/500
English CoT 469/500
English CoT 470/500
English CoT 471/500
English CoT 472/500
English CoT 473/500
English CoT 474/500
English CoT 475/500
English CoT 476/500
English CoT 477/500
English CoT 478/500
English CoT 479/500
English CoT 480/500
English CoT 481/500
English CoT 482/500
English CoT 483/500
English CoT 484/500
English CoT 485/500
English CoT 486/500
English CoT 487/500
English CoT 488/500
English CoT 489/500
English CoT 490/500
English CoT 491/500
English CoT 492/500
English CoT 493/500
English CoT 494/500
English CoT 495/500
English CoT 496/500
English CoT 497/500
English CoT 498/500
English CoT 499/500
English CoT 500/500
English CoT experiment finished

In [25]:
y_true = df["answer_key"].str.strip().str.upper()
y_pred = df["pred_cot_en"].str.strip().str.upper()

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred))

Accuracy: 0.876
              precision    recall  f1-score   support

           A       0.92      0.89      0.90       100
           B       0.93      0.87      0.90       118
           C       0.84      0.92      0.88        87
           D       0.85      0.84      0.85       102
           E       0.83      0.86      0.85        93

    accuracy                           0.88       500
   macro avg       0.87      0.88      0.88       500
weighted avg       0.88      0.88      0.88       500

In [26]:
def csqa_cot_en_kz(question_kz, options_kz):

    prompt = f"""You are a commonsense reasoning expert.

Think step by step before answering the question.

After reasoning, provide the final answer in the following format:

Answer: <A/B/C/D/E>

Question:
{question_kz}

Choices:
{options_kz}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role":"user","content":prompt}]
    )

    output = response.choices[0].message.content.strip().upper()

    match = re.search(r"ANSWER\s*:\s*([ABCDE])", output)

    if match:
        return match.group(1)

    match2 = re.search(r"[ABCDE]", output)
    return match2.group(0) if match2 else output

In [27]:
for i in range(5):

    pred = csqa_cot_en_kz(
        df.loc[i,"question_kz"],
        df.loc[i,"options_kz"]
    )

    print(i, "pred:", pred, "gold:", df.loc[i,"answer_key"])

0 pred: B gold: B
1 pred: A gold: A
2 pred: E gold: E
3 pred: A gold: A
4 pred: E gold: E

In [28]:
import time

df["pred_cot_en_kz"] = ""

for i in range(len(df)):

    print(f"EN CoT + KZ input {i+1}/500")

    df.loc[i,"pred_cot_en_kz"] = csqa_cot_en_kz(
        df.loc[i,"question_kz"],
        df.loc[i,"options_kz"]
    )

    if (i+1) % 25 == 0:
        df.to_csv("csqa_cot_en_kz_progress.csv", index=False)

    time.sleep(0.25)

df.to_csv("csqa_cot_en_kz_final.csv", index=False)

print("EN CoT + KZ experiment finished")

EN CoT + KZ input 1/500
EN CoT + KZ input 2/500
EN CoT + KZ input 3/500
EN CoT + KZ input 4/500
EN CoT + KZ input 5/500
EN CoT + KZ input 6/500
EN CoT + KZ input 7/500
EN CoT + KZ input 8/500
EN CoT + KZ input 9/500
EN CoT + KZ input 10/500
EN CoT + KZ input 11/500
EN CoT + KZ input 12/500
EN CoT + KZ input 13/500
EN CoT + KZ input 14/500
EN CoT + KZ input 15/500
EN CoT + KZ input 16/500
EN CoT + KZ input 17/500
EN CoT + KZ input 18/500
EN CoT + KZ input 19/500
EN CoT + KZ input 20/500
EN CoT + KZ input 21/500
EN CoT + KZ input 22/500
EN CoT + KZ input 23/500
EN CoT + KZ input 24/500
EN CoT + KZ input 25/500
EN CoT + KZ input 26/500
EN CoT + KZ input 27/500
EN CoT + KZ input 28/500
EN CoT + KZ input 29/500
EN CoT + KZ input 30/500
EN CoT + KZ input 31/500
EN CoT + KZ input 32/500
EN CoT + KZ input 33/500
EN CoT + KZ input 34/500
EN CoT + KZ input 35/500
EN CoT + KZ input 36/500
EN CoT + KZ input 37/500
EN CoT + KZ input 38/500
EN CoT + KZ input 39/500
EN CoT + KZ input 40/500
EN CoT + KZ input 41/500
EN CoT + KZ input 42/500
EN CoT + KZ input 43/500
EN CoT + KZ input 44/500
EN CoT + KZ input 45/500
EN CoT + KZ input 46/500
EN CoT + KZ input 47/500
EN CoT + KZ input 48/500
EN CoT + KZ input 49/500
EN CoT + KZ input 50/500
EN CoT + KZ input 51/500
EN CoT + KZ input 52/500
EN CoT + KZ input 53/500
EN CoT + KZ input 54/500
EN CoT + KZ input 55/500
EN CoT + KZ input 56/500
EN CoT + KZ input 57/500
EN CoT + KZ input 58/500
EN CoT + KZ input 59/500
EN CoT + KZ input 60/500
EN CoT + KZ input 61/500
EN CoT + KZ input 62/500
EN CoT + KZ input 63/500
EN CoT + KZ input 64/500
EN CoT + KZ input 65/500
EN CoT + KZ input 66/500
EN CoT + KZ input 67/500
EN CoT + KZ input 68/500
EN CoT + KZ input 69/500
EN CoT + KZ input 70/500
EN CoT + KZ input 71/500
EN CoT + KZ input 72/500
EN CoT + KZ input 73/500
EN CoT + KZ input 74/500
EN CoT + KZ input 75/500
EN CoT + KZ input 76/500
EN CoT + KZ input 77/500
EN CoT + KZ input 78/500
EN CoT + KZ input 79/500
EN CoT + KZ input 80/500
EN CoT + KZ input 81/500
EN CoT + KZ input 82/500
EN CoT + KZ input 83/500
EN CoT + KZ input 84/500
EN CoT + KZ input 85/500
EN CoT + KZ input 86/500
EN CoT + KZ input 87/500
EN CoT + KZ input 88/500
EN CoT + KZ input 89/500
EN CoT + KZ input 90/500
EN CoT + KZ input 91/500
EN CoT + KZ input 92/500
EN CoT + KZ input 93/500
EN CoT + KZ input 94/500
EN CoT + KZ input 95/500
EN CoT + KZ input 96/500
EN CoT + KZ input 97/500
EN CoT + KZ input 98/500
EN CoT + KZ input 99/500
EN CoT + KZ input 100/500
EN CoT + KZ input 101/500
EN CoT + KZ input 102/500
EN CoT + KZ input 103/500
EN CoT + KZ input 104/500
EN CoT + KZ input 105/500
EN CoT + KZ input 106/500
EN CoT + KZ input 107/500
EN CoT + KZ input 108/500
EN CoT + KZ input 109/500
EN CoT + KZ input 110/500
EN CoT + KZ input 111/500
EN CoT + KZ input 112/500
EN CoT + KZ input 113/500
EN CoT + KZ input 114/500
EN CoT + KZ input 115/500
EN CoT + KZ input 116/500
EN CoT + KZ input 117/500
EN CoT + KZ input 118/500
EN CoT + KZ input 119/500
EN CoT + KZ input 120/500
EN CoT + KZ input 121/500
EN CoT + KZ input 122/500
EN CoT + KZ input 123/500
EN CoT + KZ input 124/500
EN CoT + KZ input 125/500
EN CoT + KZ input 126/500
EN CoT + KZ input 127/500
EN CoT + KZ input 128/500
EN CoT + KZ input 129/500
EN CoT + KZ input 130/500
EN CoT + KZ input 131/500
EN CoT + KZ input 132/500
EN CoT + KZ input 133/500
EN CoT + KZ input 134/500
EN CoT + KZ input 135/500
EN CoT + KZ input 136/500
EN CoT + KZ input 137/500
EN CoT + KZ input 138/500
EN CoT + KZ input 139/500
EN CoT + KZ input 140/500
EN CoT + KZ input 141/500
EN CoT + KZ input 142/500
EN CoT + KZ input 143/500
EN CoT + KZ input 144/500
EN CoT + KZ input 145/500
EN CoT + KZ input 146/500
EN CoT + KZ input 147/500
EN CoT + KZ input 148/500
EN CoT + KZ input 149/500
EN CoT + KZ input 150/500
EN CoT + KZ input 151/500
EN CoT + KZ input 152/500
EN CoT + KZ input 153/500
EN CoT + KZ input 154/500
EN CoT + KZ input 155/500
EN CoT + KZ input 156/500
EN CoT + KZ input 157/500
EN CoT + KZ input 158/500
EN CoT + KZ input 159/500
EN CoT + KZ input 160/500
EN CoT + KZ input 161/500
EN CoT + KZ input 162/500
EN CoT + KZ input 163/500
EN CoT + KZ input 164/500
EN CoT + KZ input 165/500
EN CoT + KZ input 166/500
EN CoT + KZ input 167/500
EN CoT + KZ input 168/500
EN CoT + KZ input 169/500
EN CoT + KZ input 170/500
EN CoT + KZ input 171/500
EN CoT + KZ input 172/500
EN CoT + KZ input 173/500
EN CoT + KZ input 174/500
EN CoT + KZ input 175/500
EN CoT + KZ input 176/500
EN CoT + KZ input 177/500
EN CoT + KZ input 178/500
EN CoT + KZ input 179/500
EN CoT + KZ input 180/500
EN CoT + KZ input 181/500
EN CoT + KZ input 182/500
EN CoT + KZ input 183/500
EN CoT + KZ input 184/500
EN CoT + KZ input 185/500
EN CoT + KZ input 186/500
EN CoT + KZ input 187/500
EN CoT + KZ input 188/500
EN CoT + KZ input 189/500
EN CoT + KZ input 190/500
EN CoT + KZ input 191/500
EN CoT + KZ input 192/500
EN CoT + KZ input 193/500
EN CoT + KZ input 194/500
EN CoT + KZ input 195/500
EN CoT + KZ input 196/500
EN CoT + KZ input 197/500
EN CoT + KZ input 198/500
EN CoT + KZ input 199/500
EN CoT + KZ input 200/500
EN CoT + KZ input 201/500
EN CoT + KZ input 202/500
EN CoT + KZ input 203/500
EN CoT + KZ input 204/500
EN CoT + KZ input 205/500
EN CoT + KZ input 206/500
EN CoT + KZ input 207/500
EN CoT + KZ input 208/500
EN CoT + KZ input 209/500
EN CoT + KZ input 210/500
EN CoT + KZ input 211/500
EN CoT + KZ input 212/500
EN CoT + KZ input 213/500
EN CoT + KZ input 214/500
EN CoT + KZ input 215/500
EN CoT + KZ input 216/500
EN CoT + KZ input 217/500
EN CoT + KZ input 218/500
EN CoT + KZ input 219/500
EN CoT + KZ input 220/500
EN CoT + KZ input 221/500
EN CoT + KZ input 222/500
EN CoT + KZ input 223/500
EN CoT + KZ input 224/500
EN CoT + KZ input 225/500
EN CoT + KZ input 226/500
EN CoT + KZ input 227/500
EN CoT + KZ input 228/500
EN CoT + KZ input 229/500
EN CoT + KZ input 230/500
EN CoT + KZ input 231/500
EN CoT + KZ input 232/500
EN CoT + KZ input 233/500
EN CoT + KZ input 234/500
EN CoT + KZ input 235/500
EN CoT + KZ input 236/500
EN CoT + KZ input 237/500
EN CoT + KZ input 238/500
EN CoT + KZ input 239/500
EN CoT + KZ input 240/500
EN CoT + KZ input 241/500
EN CoT + KZ input 242/500
EN CoT + KZ input 243/500
EN CoT + KZ input 244/500
EN CoT + KZ input 245/500
EN CoT + KZ input 246/500
EN CoT + KZ input 247/500
EN CoT + KZ input 248/500
EN CoT + KZ input 249/500
EN CoT + KZ input 250/500
EN CoT + KZ input 251/500
EN CoT + KZ input 252/500
EN CoT + KZ input 253/500
EN CoT + KZ input 254/500
EN CoT + KZ input 255/500
EN CoT + KZ input 256/500
EN CoT + KZ input 257/500
EN CoT + KZ input 258/500
EN CoT + KZ input 259/500
EN CoT + KZ input 260/500
EN CoT + KZ input 261/500
EN CoT + KZ input 262/500
EN CoT + KZ input 263/500
EN CoT + KZ input 264/500
EN CoT + KZ input 265/500
EN CoT + KZ input 266/500
EN CoT + KZ input 267/500
EN CoT + KZ input 268/500
EN CoT + KZ input 269/500
EN CoT + KZ input 270/500
EN CoT + KZ input 271/500
EN CoT + KZ input 272/500
EN CoT + KZ input 273/500
EN CoT + KZ input 274/500
EN CoT + KZ input 275/500
EN CoT + KZ input 276/500
EN CoT + KZ input 277/500
EN CoT + KZ input 278/500
EN CoT + KZ input 279/500
EN CoT + KZ input 280/500
EN CoT + KZ input 281/500
EN CoT + KZ input 282/500
EN CoT + KZ input 283/500
EN CoT + KZ input 284/500
EN CoT + KZ input 285/500
EN CoT + KZ input 286/500
EN CoT + KZ input 287/500
EN CoT + KZ input 288/500
EN CoT + KZ input 289/500
EN CoT + KZ input 290/500
EN CoT + KZ input 291/500
EN CoT + KZ input 292/500
EN CoT + KZ input 293/500
EN CoT + KZ input 294/500
EN CoT + KZ input 295/500
EN CoT + KZ input 296/500
EN CoT + KZ input 297/500
EN CoT + KZ input 298/500
EN CoT + KZ input 299/500
EN CoT + KZ input 300/500
EN CoT + KZ input 301/500
EN CoT + KZ input 302/500
EN CoT + KZ input 303/500
EN CoT + KZ input 304/500
EN CoT + KZ input 305/500
EN CoT + KZ input 306/500
EN CoT + KZ input 307/500
EN CoT + KZ input 308/500
EN CoT + KZ input 309/500
EN CoT + KZ input 310/500
EN CoT + KZ input 311/500
EN CoT + KZ input 312/500
EN CoT + KZ input 313/500
EN CoT + KZ input 314/500
EN CoT + KZ input 315/500
EN CoT + KZ input 316/500
EN CoT + KZ input 317/500
EN CoT + KZ input 318/500
EN CoT + KZ input 319/500
EN CoT + KZ input 320/500

EN CoT + KZ input 321/500
EN CoT + KZ input 322/500
EN CoT + KZ input 323/500
EN CoT + KZ input 324/500
EN CoT + KZ input 325/500
EN CoT + KZ input 326/500
EN CoT + KZ input 327/500
EN CoT + KZ input 328/500
EN CoT + KZ input 329/500
EN CoT + KZ input 330/500
EN CoT + KZ input 331/500
EN CoT + KZ input 332/500
EN CoT + KZ input 333/500
EN CoT + KZ input 334/500
EN CoT + KZ input 335/500
EN CoT + KZ input 336/500
EN CoT + KZ input 337/500
EN CoT + KZ input 338/500
EN CoT + KZ input 339/500
EN CoT + KZ input 340/500
EN CoT + KZ input 341/500
EN CoT + KZ input 342/500
EN CoT + KZ input 343/500
EN CoT + KZ input 344/500
EN CoT + KZ input 345/500
EN CoT + KZ input 346/500
EN CoT + KZ input 347/500
EN CoT + KZ input 348/500
EN CoT + KZ input 349/500
EN CoT + KZ input 350/500
EN CoT + KZ input 351/500
EN CoT + KZ input 352/500
EN CoT + KZ input 353/500
EN CoT + KZ input 354/500
EN CoT + KZ input 355/500
EN CoT + KZ input 356/500
EN CoT + KZ input 357/500
EN CoT + KZ input 358/500
EN CoT + KZ input 359/500
EN CoT + KZ input 360/500
EN CoT + KZ input 361/500
EN CoT + KZ input 362/500
EN CoT + KZ input 363/500
EN CoT + KZ input 364/500
EN CoT + KZ input 365/500
EN CoT + KZ input 366/500
EN CoT + KZ input 367/500
EN CoT + KZ input 368/500
EN CoT + KZ input 369/500
EN CoT + KZ input 370/500
EN CoT + KZ input 371/500
EN CoT + KZ input 372/500
EN CoT + KZ input 373/500
EN CoT + KZ input 374/500
EN CoT + KZ input 375/500
EN CoT + KZ input 376/500
EN CoT + KZ input 377/500
EN CoT + KZ input 378/500
EN CoT + KZ input 379/500
EN CoT + KZ input 380/500
EN CoT + KZ input 381/500
EN CoT + KZ input 382/500
EN CoT + KZ input 383/500
EN CoT + KZ input 384/500
EN CoT + KZ input 385/500
EN CoT + KZ input 386/500
EN CoT + KZ input 387/500
EN CoT + KZ input 388/500
EN CoT + KZ input 389/500
EN CoT + KZ input 390/500
EN CoT + KZ input 391/500
EN CoT + KZ input 392/500
EN CoT + KZ input 393/500
EN CoT + KZ input 394/500
EN CoT + KZ input 395/500
EN CoT + KZ input 396/500
EN CoT + KZ input 397/500
EN CoT + KZ input 398/500
EN CoT + KZ input 399/500
EN CoT + KZ input 400/500
EN CoT + KZ input 401/500
EN CoT + KZ input 402/500
EN CoT + KZ input 403/500
EN CoT + KZ input 404/500
EN CoT + KZ input 405/500
EN CoT + KZ input 406/500
EN CoT + KZ input 407/500
EN CoT + KZ input 408/500
EN CoT + KZ input 409/500
EN CoT + KZ input 410/500
EN CoT + KZ input 411/500
EN CoT + KZ input 412/500
EN CoT + KZ input 413/500
EN CoT + KZ input 414/500
EN CoT + KZ input 415/500
EN CoT + KZ input 416/500
EN CoT + KZ input 417/500
EN CoT + KZ input 418/500
EN CoT + KZ input 419/500
EN CoT + KZ input 420/500
EN CoT + KZ input 421/500
EN CoT + KZ input 422/500
EN CoT + KZ input 423/500
EN CoT + KZ input 424/500
EN CoT + KZ input 425/500
EN CoT + KZ input 426/500
EN CoT + KZ input 427/500
EN CoT + KZ input 428/500
EN CoT + KZ input 429/500
EN CoT + KZ input 430/500
EN CoT + KZ input 431/500
EN CoT + KZ input 432/500
EN CoT + KZ input 433/500
EN CoT + KZ input 434/500
EN CoT + KZ input 435/500
EN CoT + KZ input 436/500
EN CoT + KZ input 437/500
EN CoT + KZ input 438/500
EN CoT + KZ input 439/500
EN CoT + KZ input 440/500
EN CoT + KZ input 441/500
EN CoT + KZ input 442/500
EN CoT + KZ input 443/500
EN CoT + KZ input 444/500
EN CoT + KZ input 445/500
EN CoT + KZ input 446/500
EN CoT + KZ input 447/500
EN CoT + KZ input 448/500
EN CoT + KZ input 449/500
EN CoT + KZ input 450/500
EN CoT + KZ input 451/500
EN CoT + KZ input 452/500
EN CoT + KZ input 453/500
EN CoT + KZ input 454/500
EN CoT + KZ input 455/500
EN CoT + KZ input 456/500
EN CoT + KZ input 457/500
EN CoT + KZ input 458/500
EN CoT + KZ input 459/500
EN CoT + KZ input 460/500
EN CoT + KZ input 461/500
EN CoT + KZ input 462/500
EN CoT + KZ input 463/500
EN CoT + KZ input 464/500
EN CoT + KZ input 465/500
EN CoT + KZ input 466/500
EN CoT + KZ input 467/500
EN CoT + KZ input 468/500
EN CoT + KZ input 469/500
EN CoT + KZ input 470/500
EN CoT + KZ input 471/500
EN CoT + KZ input 472/500
EN CoT + KZ input 473/500
EN CoT + KZ input 474/500
EN CoT + KZ input 475/500
EN CoT + KZ input 476/500
EN CoT + KZ input 477/500
EN CoT + KZ input 478/500
EN CoT + KZ input 479/500
EN CoT + KZ input 480/500
EN CoT + KZ input 481/500
EN CoT + KZ input 482/500
EN CoT + KZ input 483/500
EN CoT + KZ input 484/500
EN CoT + KZ input 485/500
EN CoT + KZ input 486/500
EN CoT + KZ input 487/500
EN CoT + KZ input 488/500
EN CoT + KZ input 489/500
EN CoT + KZ input 490/500
EN CoT + KZ input 491/500
EN CoT + KZ input 492/500
EN CoT + KZ input 493/500
EN CoT + KZ input 494/500
EN CoT + KZ input 495/500
EN CoT + KZ input 496/500
EN CoT + KZ input 497/500
EN CoT + KZ input 498/500
EN CoT + KZ input 499/500
EN CoT + KZ input 500/500
EN CoT + KZ experiment finished

In [29]:
y_true = df["answer_key"].str.strip().str.upper()
y_pred = df["pred_cot_en_kz"].str.strip().str.upper()

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred))

Accuracy: 0.744
              precision    recall  f1-score   support

           A       0.75      0.81      0.78       100
           B       0.79      0.75      0.77       118
           C       0.69      0.68      0.68        87
           D       0.74      0.76      0.75       102
           E       0.73      0.71      0.72        93

    accuracy                           0.74       500
   macro avg       0.74      0.74      0.74       500
weighted avg       0.74      0.74      0.74       500