In [1]:
import pandas as pd
import time
from openai import OpenAI

client = OpenAI(api_key=" ")

df = pd.read_csv("imdb_kz_final_1000.csv")
df.head()

,text,sentiment,review_kz
0,All these reviewers are spot on. I've seen man...,negative,Барлық шолушылар дәл айтқан. Мен жылдар бойы к...
1,I literally fell asleep 3 times watching this ...,negative,"Мен бұл фильмді көріп отырып, үш рет ұйықтап қ..."
2,The plot of Corpse Grinders 2 is very much sim...,negative,«Corpse Grinders 2» фильмінің сюжеті түпнұсқа ...
3,I first started watching this show probably ar...,negative,Мен бұл шоуды алғаш рет 2003 немесе 2004 жылда...
4,Tiempo de Valientes fits snugly into the buddy...,positive,«Tiempo de Valientes» достық экшн фильм жанрын...

In [ ]:
print(df.columns)

In [ ]:
def classify_en_zero_shot(review_text: str) -> str:
    prompt = f"""You are a sentiment classifier.
Classify the movie review as either positive or negative.
Respond with only one word: positive or negative.

Review:
{review_text}
"""
    resp = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role": "user", "content": prompt}],
    )
    out = resp.choices[0].message.content.strip().lower()
    # normalize just in case
    if "positive" in out and "negative" not in out:
        return "positive"
    if "negative" in out and "positive" not in out:
        return "negative"
    return out

In [ ]:
for i in range(2):
    pred = classify_en_zero_shot(df.loc[i, "text"])
    print(i, "pred:", pred, "gold:", df.loc[i, "sentiment"])
    time.sleep(0.4)

In [ ]:
df["pred_en"] = ""

save_path = "imdb_predictions_en_progress.csv"

for i in range(len(df)):
    if isinstance(df.loc[i, "pred_en"], str) and df.loc[i, "pred_en"] in ["positive", "negative"]:
        continue  

    print(f"EN {i+1}/{len(df)}")
    df.loc[i, "pred_en"] = classify_en_zero_shot(df.loc[i, "text"])

    # save every 25 rows
    if (i + 1) % 25 == 0:
        df.to_csv(save_path, index=False)
        print("Saved progress:", save_path)

    time.sleep(0.4)

df.to_csv("imdb_predictions_en_final.csv", index=False)
print("Done. Saved: imdb_predictions_en_final.csv")

In [2]:
df = pd.read_csv("imdb_predictions_en_final.csv")

print(len(df))
print(df["pred_en"].value_counts())
print(df["pred_en"].isna().sum())

1000
negative    523
positive    477
Name: pred_en, dtype: int64
0

In [3]:
from sklearn.metrics import classification_report, accuracy_score

df = pd.read_csv("imdb_predictions_en_final.csv")

print(classification_report(df["sentiment"], df["pred_en"]))
print("Accuracy:", accuracy_score(df["sentiment"], df["pred_en"]))

              precision    recall  f1-score   support

    negative       0.94      0.98      0.96       500
    positive       0.98      0.93      0.96       500

    accuracy                           0.96      1000
   macro avg       0.96      0.96      0.96      1000
weighted avg       0.96      0.96      0.96      1000

Accuracy: 0.957

In [4]:
df["sentiment_kz"] = df["sentiment"].map({
    "positive": "оң",
    "negative": "теріс"
})

In [5]:
df.head()

,text,sentiment,review_kz,pred_en,sentiment_kz
0,All these reviewers are spot on. I've seen man...,negative,Барлық шолушылар дәл айтқан. Мен жылдар бойы к...,negative,теріс
1,I literally fell asleep 3 times watching this ...,negative,"Мен бұл фильмді көріп отырып, үш рет ұйықтап қ...",negative,теріс
2,The plot of Corpse Grinders 2 is very much sim...,negative,«Corpse Grinders 2» фильмінің сюжеті түпнұсқа ...,negative,теріс
3,I first started watching this show probably ar...,negative,Мен бұл шоуды алғаш рет 2003 немесе 2004 жылда...,negative,теріс
4,Tiempo de Valientes fits snugly into the buddy...,positive,«Tiempo de Valientes» достық экшн фильм жанрын...,positive,оң

In [6]:
def classify_kz_native_basic(review_text):

    prompt = f"""
Сен мәтіндегі эмоцияны анықтайтын талдаушысың.
Төмендегі фильм туралы пікірдің көңіл күйін анықта.

Жауап тек бір сөз болсын: оң немесе теріс.

Пікір:
{review_text}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    output = response.choices[0].message.content.strip().lower()

    # normalize outputs
    if "оң" in output:
        return "оң"
    if "теріс" in output:
        return "теріс"

    return output

In [7]:
for i in range(2):
    pred = classify_kz_native_basic(df.loc[i,"review_kz"])
    print("Pred:", pred, "| True:", df.loc[i,"sentiment_kz"])

Pred: теріс | True: теріс
Pred: теріс | True: теріс

In [8]:
for i in range(len(df)):

    print(f"KZ {i+1}/1000")

    df.loc[i,"pred_kz"] = classify_kz_native_basic(df.loc[i,"review_kz"])

    if (i+1) % 25 == 0:
        df.to_csv("imdb_predictions_kz_progress.csv", index=False)

    time.sleep(0.4)

df.to_csv("imdb_predictions_final.csv", index=False)

print("Kazakh Native-Basic classification finished")

KZ 1/1000
KZ 2/1000
KZ 3/1000
KZ 4/1000
KZ 5/1000
KZ 6/1000
KZ 7/1000
KZ 8/1000
KZ 9/1000
KZ 10/1000
KZ 11/1000
KZ 12/1000
KZ 13/1000
KZ 14/1000
KZ 15/1000
KZ 16/1000
KZ 17/1000
KZ 18/1000
KZ 19/1000
KZ 20/1000
KZ 21/1000
KZ 22/1000
KZ 23/1000
KZ 24/1000
KZ 25/1000
KZ 26/1000
KZ 27/1000
KZ 28/1000
KZ 29/1000
KZ 30/1000
KZ 31/1000
KZ 32/1000
KZ 33/1000
KZ 34/1000
KZ 35/1000
KZ 36/1000
KZ 37/1000
KZ 38/1000
KZ 39/1000
KZ 40/1000
KZ 41/1000
KZ 42/1000
KZ 43/1000
KZ 44/1000
KZ 45/1000
KZ 46/1000
KZ 47/1000
KZ 48/1000
KZ 49/1000
KZ 50/1000
KZ 51/1000
KZ 52/1000
KZ 53/1000
KZ 54/1000
KZ 55/1000
KZ 56/1000
KZ 57/1000
KZ 58/1000
KZ 59/1000
KZ 60/1000
KZ 61/1000
KZ 62/1000
KZ 63/1000
KZ 64/1000
KZ 65/1000
KZ 66/1000
KZ 67/1000
KZ 68/1000
KZ 69/1000
KZ 70/1000
KZ 71/1000
KZ 72/1000
KZ 73/1000
KZ 74/1000
KZ 75/1000
KZ 76/1000
KZ 77/1000
KZ 78/1000
KZ 79/1000
KZ 80/1000
KZ 81/1000
KZ 82/1000
KZ 83/1000
KZ 84/1000
KZ 85/1000
KZ 86/1000
KZ 87/1000
KZ 88/1000
KZ 89/1000
KZ 90/1000
KZ 91/1000
KZ 92/1000
KZ 93/1000
KZ 94/1000
KZ 95/1000
KZ 96/1000
KZ 97/1000
KZ 98/1000
KZ 99/1000
KZ 100/1000
KZ 101/1000
KZ 102/1000
KZ 103/1000
KZ 104/1000
KZ 105/1000
KZ 106/1000
KZ 107/1000
KZ 108/1000
KZ 109/1000
KZ 110/1000
KZ 111/1000
KZ 112/1000
KZ 113/1000
KZ 114/1000
KZ 115/1000
KZ 116/1000
KZ 117/1000
KZ 118/1000
KZ 119/1000
KZ 120/1000
KZ 121/1000
KZ 122/1000
KZ 123/1000
KZ 124/1000
KZ 125/1000
KZ 126/1000
KZ 127/1000
KZ 128/1000
KZ 129/1000
KZ 130/1000
KZ 131/1000
KZ 132/1000
KZ 133/1000
KZ 134/1000
KZ 135/1000
KZ 136/1000
KZ 137/1000
KZ 138/1000
KZ 139/1000
KZ 140/1000
KZ 141/1000
KZ 142/1000
KZ 143/1000
KZ 144/1000
KZ 145/1000
KZ 146/1000
KZ 147/1000
KZ 148/1000
KZ 149/1000
KZ 150/1000
KZ 151/1000
KZ 152/1000
KZ 153/1000
KZ 154/1000
KZ 155/1000
KZ 156/1000
KZ 157/1000
KZ 158/1000
KZ 159/1000
KZ 160/1000
KZ 161/1000
KZ 162/1000
KZ 163/1000
KZ 164/1000
KZ 165/1000
KZ 166/1000
KZ 167/1000
KZ 168/1000
KZ 169/1000
KZ 170/1000
KZ 171/1000
KZ 172/1000
KZ 173/1000
KZ 174/1000
KZ 175/1000
KZ 176/1000
KZ 177/1000
KZ 178/1000
KZ 179/1000
KZ 180/1000
KZ 181/1000
KZ 182/1000
KZ 183/1000
KZ 184/1000
KZ 185/1000
KZ 186/1000
KZ 187/1000
KZ 188/1000
KZ 189/1000
KZ 190/1000
KZ 191/1000
KZ 192/1000
KZ 193/1000
KZ 194/1000
KZ 195/1000
KZ 196/1000
KZ 197/1000
KZ 198/1000
KZ 199/1000
KZ 200/1000
KZ 201/1000
KZ 202/1000
KZ 203/1000
KZ 204/1000
KZ 205/1000
KZ 206/1000
KZ 207/1000
KZ 208/1000
KZ 209/1000
KZ 210/1000
KZ 211/1000
KZ 212/1000
KZ 213/1000
KZ 214/1000
KZ 215/1000
KZ 216/1000
KZ 217/1000
KZ 218/1000
KZ 219/1000
KZ 220/1000
KZ 221/1000
KZ 222/1000
KZ 223/1000
KZ 224/1000
KZ 225/1000
KZ 226/1000
KZ 227/1000
KZ 228/1000
KZ 229/1000
KZ 230/1000
KZ 231/1000
KZ 232/1000
KZ 233/1000
KZ 234/1000
KZ 235/1000
KZ 236/1000
KZ 237/1000
KZ 238/1000
KZ 239/1000
KZ 240/1000
KZ 241/1000
KZ 242/1000
KZ 243/1000
KZ 244/1000
KZ 245/1000
KZ 246/1000
KZ 247/1000
KZ 248/1000
KZ 249/1000
KZ 250/1000
KZ 251/1000
KZ 252/1000
KZ 253/1000
KZ 254/1000
KZ 255/1000
KZ 256/1000
KZ 257/1000
KZ 258/1000
KZ 259/1000
KZ 260/1000
KZ 261/1000
KZ 262/1000
KZ 263/1000
KZ 264/1000
KZ 265/1000
KZ 266/1000
KZ 267/1000
KZ 268/1000
KZ 269/1000
KZ 270/1000
KZ 271/1000
KZ 272/1000
KZ 273/1000
KZ 274/1000
KZ 275/1000
KZ 276/1000
KZ 277/1000
KZ 278/1000
KZ 279/1000
KZ 280/1000
KZ 281/1000
KZ 282/1000
KZ 283/1000
KZ 284/1000
KZ 285/1000
KZ 286/1000
KZ 287/1000
KZ 288/1000
KZ 289/1000
KZ 290/1000
KZ 291/1000
KZ 292/1000
KZ 293/1000
KZ 294/1000
KZ 295/1000
KZ 296/1000
KZ 297/1000
KZ 298/1000
KZ 299/1000
KZ 300/1000
KZ 301/1000
KZ 302/1000
KZ 303/1000
KZ 304/1000
KZ 305/1000
KZ 306/1000
KZ 307/1000
KZ 308/1000
KZ 309/1000
KZ 310/1000
KZ 311/1000
KZ 312/1000
KZ 313/1000
KZ 314/1000
KZ 315/1000
KZ 316/1000
KZ 317/1000
KZ 318/1000
KZ 319/1000
KZ 320/1000
KZ 321/1000
KZ 322/1000
KZ 323/1000
KZ 324/1000
KZ 325/1000
KZ 326/1000
KZ 327/1000
KZ 328/1000
KZ 329/1000
KZ 330/1000
KZ 331/1000
KZ 332/1000
KZ 333/1000
KZ 334/1000
KZ 335/1000
KZ 336/1000
KZ 337/1000
KZ 338/1000
KZ 339/1000
KZ 340/1000
KZ 341/1000
KZ 342/1000
KZ 343/1000
KZ 344/1000
KZ 345/1000
KZ 346/1000
KZ 347/1000
KZ 348/1000
KZ 349/1000
KZ 350/1000
KZ 351/1000
KZ 352/1000
KZ 353/1000
KZ 354/1000
KZ 355/1000
KZ 356/1000
KZ 357/1000
KZ 358/1000
KZ 359/1000
KZ 360/1000
KZ 361/1000
KZ 362/1000
KZ 363/1000
KZ 364/1000
KZ 365/1000
KZ 366/1000
KZ 367/1000
KZ 368/1000
KZ 369/1000
KZ 370/1000
KZ 371/1000
KZ 372/1000
KZ 373/1000
KZ 374/1000
KZ 375/1000
KZ 376/1000
KZ 377/1000
KZ 378/1000
KZ 379/1000
KZ 380/1000
KZ 381/1000
KZ 382/1000
KZ 383/1000
KZ 384/1000
KZ 385/1000
KZ 386/1000
KZ 387/1000
KZ 388/1000
KZ 389/1000
KZ 390/1000
KZ 391/1000
KZ 392/1000
KZ 393/1000
KZ 394/1000
KZ 395/1000
KZ 396/1000
KZ 397/1000
KZ 398/1000
KZ 399/1000
KZ 400/1000
KZ 401/1000
KZ 402/1000
KZ 403/1000
KZ 404/1000
KZ 405/1000
KZ 406/1000
KZ 407/1000
KZ 408/1000
KZ 409/1000
KZ 410/1000
KZ 411/1000
KZ 412/1000
KZ 413/1000
KZ 414/1000
KZ 415/1000
KZ 416/1000
KZ 417/1000
KZ 418/1000
KZ 419/1000
KZ 420/1000
KZ 421/1000
KZ 422/1000
KZ 423/1000
KZ 424/1000
KZ 425/1000
KZ 426/1000
KZ 427/1000
KZ 428/1000
KZ 429/1000
KZ 430/1000
KZ 431/1000
KZ 432/1000
KZ 433/1000
KZ 434/1000
KZ 435/1000
KZ 436/1000
KZ 437/1000
KZ 438/1000
KZ 439/1000
KZ 440/1000
KZ 441/1000
KZ 442/1000
KZ 443/1000
KZ 444/1000
KZ 445/1000
KZ 446/1000
KZ 447/1000
KZ 448/1000
KZ 449/1000
KZ 450/1000
KZ 451/1000
KZ 452/1000
KZ 453/1000
KZ 454/1000
KZ 455/1000
KZ 456/1000
KZ 457/1000
KZ 458/1000
KZ 459/1000
KZ 460/1000
KZ 461/1000
KZ 462/1000
KZ 463/1000
KZ 464/1000
KZ 465/1000
KZ 466/1000
KZ 467/1000
KZ 468/1000
KZ 469/1000
KZ 470/1000
KZ 471/1000
KZ 472/1000
KZ 473/1000
KZ 474/1000
KZ 475/1000
KZ 476/1000
KZ 477/1000
KZ 478/1000
KZ 479/1000
KZ 480/1000
KZ 481/1000
KZ 482/1000
KZ 483/1000
KZ 484/1000
KZ 485/1000
KZ 486/1000
KZ 487/1000
KZ 488/1000
KZ 489/1000
KZ 490/1000
KZ 491/1000
KZ 492/1000
KZ 493/1000
KZ 494/1000
KZ 495/1000
KZ 496/1000
KZ 497/1000
KZ 498/1000
KZ 499/1000
KZ 500/1000
KZ 501/1000
KZ 502/1000
KZ 503/1000
KZ 504/1000
KZ 505/1000
KZ 506/1000
KZ 507/1000
KZ 508/1000
KZ 509/1000
KZ 510/1000
KZ 511/1000
KZ 512/1000
KZ 513/1000
KZ 514/1000
KZ 515/1000
KZ 516/1000
KZ 517/1000
KZ 518/1000
KZ 519/1000
KZ 520/1000
KZ 521/1000
KZ 522/1000
KZ 523/1000
KZ 524/1000
KZ 525/1000
KZ 526/1000
KZ 527/1000
KZ 528/1000
KZ 529/1000
KZ 530/1000
KZ 531/1000
KZ 532/1000
KZ 533/1000
KZ 534/1000
KZ 535/1000
KZ 536/1000
KZ 537/1000
KZ 538/1000
KZ 539/1000
KZ 540/1000
KZ 541/1000
KZ 542/1000
KZ 543/1000
KZ 544/1000
KZ 545/1000
KZ 546/1000
KZ 547/1000
KZ 548/1000
KZ 549/1000
KZ 550/1000
KZ 551/1000
KZ 552/1000
KZ 553/1000
KZ 554/1000
KZ 555/1000
KZ 556/1000
KZ 557/1000
KZ 558/1000
KZ 559/1000
KZ 560/1000
KZ 561/1000
KZ 562/1000
KZ 563/1000
KZ 564/1000
KZ 565/1000
KZ 566/1000
KZ 567/1000
KZ 568/1000
KZ 569/1000
KZ 570/1000
KZ 571/1000
KZ 572/1000
KZ 573/1000
KZ 574/1000
KZ 575/1000
KZ 576/1000
KZ 577/1000
KZ 578/1000
KZ 579/1000
KZ 580/1000
KZ 581/1000
KZ 582/1000
KZ 583/1000
KZ 584/1000
KZ 585/1000
KZ 586/1000
KZ 587/1000
KZ 588/1000
KZ 589/1000
KZ 590/1000
KZ 591/1000
KZ 592/1000
KZ 593/1000
KZ 594/1000
KZ 595/1000
KZ 596/1000
KZ 597/1000
KZ 598/1000
KZ 599/1000
KZ 600/1000
KZ 601/1000
KZ 602/1000
KZ 603/1000
KZ 604/1000
KZ 605/1000
KZ 606/1000
KZ 607/1000
KZ 608/1000
KZ 609/1000
KZ 610/1000
KZ 611/1000
KZ 612/1000
KZ 613/1000
KZ 614/1000
KZ 615/1000
KZ 616/1000
KZ 617/1000
KZ 618/1000
KZ 619/1000
KZ 620/1000
KZ 621/1000
KZ 622/1000
KZ 623/1000
KZ 624/1000
KZ 625/1000
KZ 626/1000
KZ 627/1000
KZ 628/1000
KZ 629/1000
KZ 630/1000
KZ 631/1000
KZ 632/1000
KZ 633/1000
KZ 634/1000
KZ 635/1000
KZ 636/1000
KZ 637/1000
KZ 638/1000
KZ 639/1000
KZ 640/1000
KZ 641/1000
KZ 642/1000
KZ 643/1000
KZ 644/1000
KZ 645/1000
KZ 646/1000
KZ 647/1000
KZ 648/1000
KZ 649/1000
KZ 650/1000
KZ 651/1000
KZ 652/1000
KZ 653/1000
KZ 654/1000
KZ 655/1000
KZ 656/1000
KZ 657/1000
KZ 658/1000
KZ 659/1000
KZ 660/1000
KZ 661/1000
KZ 662/1000
KZ 663/1000
KZ 664/1000
KZ 665/1000
KZ 666/1000
KZ 667/1000
KZ 668/1000
KZ 669/1000
KZ 670/1000
KZ 671/1000
KZ 672/1000
KZ 673/1000
KZ 674/1000
KZ 675/1000
KZ 676/1000
KZ 677/1000
KZ 678/1000
KZ 679/1000
KZ 680/1000
KZ 681/1000
KZ 682/1000
KZ 683/1000
KZ 684/1000
KZ 685/1000
KZ 686/1000
KZ 687/1000
KZ 688/1000
KZ 689/1000
KZ 690/1000
KZ 691/1000
KZ 692/1000

KZ 693/1000
KZ 694/1000
KZ 695/1000
KZ 696/1000
KZ 697/1000
KZ 698/1000
KZ 699/1000
KZ 700/1000
KZ 701/1000
KZ 702/1000
KZ 703/1000
KZ 704/1000
KZ 705/1000
KZ 706/1000
KZ 707/1000
KZ 708/1000
KZ 709/1000
KZ 710/1000
KZ 711/1000
KZ 712/1000
KZ 713/1000
KZ 714/1000
KZ 715/1000
KZ 716/1000
KZ 717/1000
KZ 718/1000
KZ 719/1000
KZ 720/1000
KZ 721/1000
KZ 722/1000
KZ 723/1000
KZ 724/1000
KZ 725/1000
KZ 726/1000
KZ 727/1000
KZ 728/1000
KZ 729/1000
KZ 730/1000
KZ 731/1000
KZ 732/1000
KZ 733/1000
KZ 734/1000
KZ 735/1000
KZ 736/1000
KZ 737/1000
KZ 738/1000
KZ 739/1000
KZ 740/1000
KZ 741/1000
KZ 742/1000
KZ 743/1000
KZ 744/1000
KZ 745/1000
KZ 746/1000
KZ 747/1000
KZ 748/1000
KZ 749/1000
KZ 750/1000
KZ 751/1000
KZ 752/1000
KZ 753/1000
KZ 754/1000
KZ 755/1000
KZ 756/1000
KZ 757/1000
KZ 758/1000
KZ 759/1000
KZ 760/1000
KZ 761/1000
KZ 762/1000
KZ 763/1000
KZ 764/1000
KZ 765/1000
KZ 766/1000
KZ 767/1000
KZ 768/1000
KZ 769/1000
KZ 770/1000
KZ 771/1000
KZ 772/1000
KZ 773/1000
KZ 774/1000
KZ 775/1000
KZ 776/1000
KZ 777/1000
KZ 778/1000
KZ 779/1000
KZ 780/1000
KZ 781/1000
KZ 782/1000
KZ 783/1000
KZ 784/1000
KZ 785/1000
KZ 786/1000
KZ 787/1000
KZ 788/1000
KZ 789/1000
KZ 790/1000
KZ 791/1000
KZ 792/1000
KZ 793/1000
KZ 794/1000
KZ 795/1000
KZ 796/1000
KZ 797/1000
KZ 798/1000
KZ 799/1000
KZ 800/1000
KZ 801/1000
KZ 802/1000
KZ 803/1000
KZ 804/1000
KZ 805/1000
KZ 806/1000
KZ 807/1000
KZ 808/1000
KZ 809/1000
KZ 810/1000
KZ 811/1000
KZ 812/1000
KZ 813/1000
KZ 814/1000
KZ 815/1000
KZ 816/1000
KZ 817/1000
KZ 818/1000
KZ 819/1000
KZ 820/1000
KZ 821/1000
KZ 822/1000
KZ 823/1000
KZ 824/1000
KZ 825/1000
KZ 826/1000
KZ 827/1000
KZ 828/1000
KZ 829/1000
KZ 830/1000
KZ 831/1000
KZ 832/1000
KZ 833/1000
KZ 834/1000
KZ 835/1000
KZ 836/1000
KZ 837/1000
KZ 838/1000
KZ 839/1000
KZ 840/1000
KZ 841/1000
KZ 842/1000
KZ 843/1000
KZ 844/1000
KZ 845/1000
KZ 846/1000
KZ 847/1000
KZ 848/1000
KZ 849/1000
KZ 850/1000
KZ 851/1000
KZ 852/1000
KZ 853/1000
KZ 854/1000
KZ 855/1000
KZ 856/1000
KZ 857/1000
KZ 858/1000
KZ 859/1000
KZ 860/1000
KZ 861/1000
KZ 862/1000
KZ 863/1000
KZ 864/1000
KZ 865/1000
KZ 866/1000
KZ 867/1000
KZ 868/1000
KZ 869/1000
KZ 870/1000
KZ 871/1000
KZ 872/1000
KZ 873/1000
KZ 874/1000
KZ 875/1000
KZ 876/1000
KZ 877/1000
KZ 878/1000
KZ 879/1000
KZ 880/1000
KZ 881/1000
KZ 882/1000
KZ 883/1000
KZ 884/1000
KZ 885/1000
KZ 886/1000
KZ 887/1000
KZ 888/1000
KZ 889/1000
KZ 890/1000
KZ 891/1000
KZ 892/1000
KZ 893/1000
KZ 894/1000
KZ 895/1000
KZ 896/1000
KZ 897/1000
KZ 898/1000
KZ 899/1000
KZ 900/1000
KZ 901/1000
KZ 902/1000
KZ 903/1000
KZ 904/1000
KZ 905/1000
KZ 906/1000
KZ 907/1000
KZ 908/1000
KZ 909/1000
KZ 910/1000
KZ 911/1000
KZ 912/1000
KZ 913/1000
KZ 914/1000
KZ 915/1000
KZ 916/1000
KZ 917/1000
KZ 918/1000
KZ 919/1000
KZ 920/1000
KZ 921/1000
KZ 922/1000
KZ 923/1000
KZ 924/1000
KZ 925/1000
KZ 926/1000
KZ 927/1000
KZ 928/1000
KZ 929/1000
KZ 930/1000
KZ 931/1000
KZ 932/1000
KZ 933/1000
KZ 934/1000
KZ 935/1000
KZ 936/1000
KZ 937/1000
KZ 938/1000
KZ 939/1000
KZ 940/1000
KZ 941/1000
KZ 942/1000
KZ 943/1000
KZ 944/1000
KZ 945/1000
KZ 946/1000
KZ 947/1000
KZ 948/1000
KZ 949/1000
KZ 950/1000
KZ 951/1000
KZ 952/1000
KZ 953/1000
KZ 954/1000
KZ 955/1000
KZ 956/1000
KZ 957/1000
KZ 958/1000
KZ 959/1000
KZ 960/1000
KZ 961/1000
KZ 962/1000
KZ 963/1000
KZ 964/1000
KZ 965/1000
KZ 966/1000
KZ 967/1000
KZ 968/1000
KZ 969/1000
KZ 970/1000
KZ 971/1000
KZ 972/1000
KZ 973/1000
KZ 974/1000
KZ 975/1000
KZ 976/1000
KZ 977/1000
KZ 978/1000
KZ 979/1000
KZ 980/1000
KZ 981/1000
KZ 982/1000
KZ 983/1000
KZ 984/1000
KZ 985/1000
KZ 986/1000
KZ 987/1000
KZ 988/1000
KZ 989/1000
KZ 990/1000
KZ 991/1000
KZ 992/1000
KZ 993/1000
KZ 994/1000
KZ 995/1000
KZ 996/1000
KZ 997/1000
KZ 998/1000
KZ 999/1000
KZ 1000/1000
Kazakh Native-Basic classification finished

In [13]:
df = pd.read_csv("imdb_predictions_final.csv")

print(len(df))
print(df["pred_kz"].value_counts())
print(df["pred_en"].value_counts())
print(df["pred_kz"].isna().sum())

1000
теріс    539
оң       461
Name: pred_kz, dtype: int64
negative    523
positive    477
Name: pred_en, dtype: int64
0

In [14]:
from sklearn.metrics import classification_report, accuracy_score

df = pd.read_csv("imdb_predictions_final.csv")

print(classification_report(df["sentiment_kz"], df["pred_kz"]))
print("Accuracy:", accuracy_score(df["sentiment_kz"], df["pred_kz"]))

              precision    recall  f1-score   support

          оң       0.97      0.90      0.93       500
       теріс       0.91      0.98      0.94       500

    accuracy                           0.94      1000
   macro avg       0.94      0.94      0.94      1000
weighted avg       0.94      0.94      0.94      1000

Accuracy: 0.937

In [15]:
def classify_en_prompt_kz_review(review_text):

    prompt = f"""
You are a sentiment classifier.
Classify the sentiment of the following movie review.

Respond with only one word: positive or negative.

Review:
{review_text}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[{"role":"user","content":prompt}]
    )

    output = response.choices[0].message.content.strip().lower()

    if "positive" in output:
        return "positive"
    if "negative" in output:
        return "negative"

    return output

In [16]:
df["pred_en_kz"] = None

for i in range(len(df)):

    print(f"EN-KZ {i+1}/1000")

    df.loc[i, "pred_en_kz"] = classify_en_prompt_kz_review(df.loc[i, "review_kz"])

    if (i + 1) % 25 == 0:
        df.to_csv("imdb_predictions_enkz_progress.csv", index=False)

    time.sleep(0.4)

df.to_csv("imdb_predictions_enkz_final.csv", index=False)

print("English prompt + Kazakh review classification finished")

EN-KZ 1/1000
EN-KZ 2/1000
EN-KZ 3/1000
EN-KZ 4/1000
EN-KZ 5/1000
EN-KZ 6/1000
EN-KZ 7/1000
EN-KZ 8/1000
EN-KZ 9/1000
EN-KZ 10/1000
EN-KZ 11/1000
EN-KZ 12/1000
EN-KZ 13/1000
EN-KZ 14/1000
EN-KZ 15/1000
EN-KZ 16/1000
EN-KZ 17/1000
EN-KZ 18/1000
EN-KZ 19/1000
EN-KZ 20/1000
EN-KZ 21/1000
EN-KZ 22/1000
EN-KZ 23/1000
EN-KZ 24/1000
EN-KZ 25/1000
EN-KZ 26/1000
EN-KZ 27/1000
EN-KZ 28/1000
EN-KZ 29/1000
EN-KZ 30/1000
EN-KZ 31/1000
EN-KZ 32/1000
EN-KZ 33/1000
EN-KZ 34/1000
EN-KZ 35/1000
EN-KZ 36/1000
EN-KZ 37/1000
EN-KZ 38/1000
EN-KZ 39/1000
EN-KZ 40/1000
EN-KZ 41/1000
EN-KZ 42/1000
EN-KZ 43/1000
EN-KZ 44/1000
EN-KZ 45/1000
EN-KZ 46/1000
EN-KZ 47/1000
EN-KZ 48/1000
EN-KZ 49/1000
EN-KZ 50/1000
EN-KZ 51/1000
EN-KZ 52/1000
EN-KZ 53/1000
EN-KZ 54/1000
EN-KZ 55/1000
EN-KZ 56/1000
EN-KZ 57/1000
EN-KZ 58/1000
EN-KZ 59/1000
EN-KZ 60/1000
EN-KZ 61/1000
EN-KZ 62/1000
EN-KZ 63/1000
EN-KZ 64/1000
EN-KZ 65/1000
EN-KZ 66/1000
EN-KZ 67/1000
EN-KZ 68/1000
EN-KZ 69/1000
EN-KZ 70/1000
EN-KZ 71/1000
EN-KZ 72/1000
EN-KZ 73/1000
EN-KZ 74/1000
EN-KZ 75/1000
EN-KZ 76/1000
EN-KZ 77/1000
EN-KZ 78/1000
EN-KZ 79/1000
EN-KZ 80/1000
EN-KZ 81/1000
EN-KZ 82/1000
EN-KZ 83/1000
EN-KZ 84/1000
EN-KZ 85/1000
EN-KZ 86/1000
EN-KZ 87/1000
EN-KZ 88/1000
EN-KZ 89/1000
EN-KZ 90/1000
EN-KZ 91/1000
EN-KZ 92/1000
EN-KZ 93/1000
EN-KZ 94/1000
EN-KZ 95/1000
EN-KZ 96/1000
EN-KZ 97/1000
EN-KZ 98/1000
EN-KZ 99/1000
EN-KZ 100/1000
EN-KZ 101/1000
EN-KZ 102/1000
EN-KZ 103/1000
EN-KZ 104/1000
EN-KZ 105/1000
EN-KZ 106/1000
EN-KZ 107/1000
EN-KZ 108/1000
EN-KZ 109/1000
EN-KZ 110/1000
EN-KZ 111/1000
EN-KZ 112/1000
EN-KZ 113/1000
EN-KZ 114/1000
EN-KZ 115/1000
EN-KZ 116/1000
EN-KZ 117/1000
EN-KZ 118/1000
EN-KZ 119/1000
EN-KZ 120/1000
EN-KZ 121/1000
EN-KZ 122/1000
EN-KZ 123/1000
EN-KZ 124/1000
EN-KZ 125/1000
EN-KZ 126/1000
EN-KZ 127/1000
EN-KZ 128/1000
EN-KZ 129/1000
EN-KZ 130/1000
EN-KZ 131/1000
EN-KZ 132/1000
EN-KZ 133/1000
EN-KZ 134/1000
EN-KZ 135/1000
EN-KZ 136/1000
EN-KZ 137/1000
EN-KZ 138/1000
EN-KZ 139/1000
EN-KZ 140/1000
EN-KZ 141/1000
EN-KZ 142/1000
EN-KZ 143/1000
EN-KZ 144/1000
EN-KZ 145/1000
EN-KZ 146/1000
EN-KZ 147/1000
EN-KZ 148/1000
EN-KZ 149/1000
EN-KZ 150/1000
EN-KZ 151/1000
EN-KZ 152/1000
EN-KZ 153/1000
EN-KZ 154/1000
EN-KZ 155/1000
EN-KZ 156/1000
EN-KZ 157/1000
EN-KZ 158/1000
EN-KZ 159/1000
EN-KZ 160/1000
EN-KZ 161/1000
EN-KZ 162/1000
EN-KZ 163/1000
EN-KZ 164/1000
EN-KZ 165/1000
EN-KZ 166/1000
EN-KZ 167/1000
EN-KZ 168/1000
EN-KZ 169/1000
EN-KZ 170/1000
EN-KZ 171/1000
EN-KZ 172/1000
EN-KZ 173/1000
EN-KZ 174/1000
EN-KZ 175/1000
EN-KZ 176/1000
EN-KZ 177/1000
EN-KZ 178/1000
EN-KZ 179/1000
EN-KZ 180/1000
EN-KZ 181/1000
EN-KZ 182/1000
EN-KZ 183/1000
EN-KZ 184/1000
EN-KZ 185/1000
EN-KZ 186/1000
EN-KZ 187/1000
EN-KZ 188/1000
EN-KZ 189/1000
EN-KZ 190/1000
EN-KZ 191/1000
EN-KZ 192/1000
EN-KZ 193/1000
EN-KZ 194/1000
EN-KZ 195/1000
EN-KZ 196/1000
EN-KZ 197/1000
EN-KZ 198/1000
EN-KZ 199/1000
EN-KZ 200/1000
EN-KZ 201/1000
EN-KZ 202/1000
EN-KZ 203/1000
EN-KZ 204/1000
EN-KZ 205/1000
EN-KZ 206/1000
EN-KZ 207/1000
EN-KZ 208/1000
EN-KZ 209/1000
EN-KZ 210/1000
EN-KZ 211/1000
EN-KZ 212/1000
EN-KZ 213/1000
EN-KZ 214/1000
EN-KZ 215/1000
EN-KZ 216/1000
EN-KZ 217/1000
EN-KZ 218/1000
EN-KZ 219/1000
EN-KZ 220/1000
EN-KZ 221/1000
EN-KZ 222/1000
EN-KZ 223/1000
EN-KZ 224/1000
EN-KZ 225/1000
EN-KZ 226/1000
EN-KZ 227/1000
EN-KZ 228/1000
EN-KZ 229/1000
EN-KZ 230/1000
EN-KZ 231/1000
EN-KZ 232/1000
EN-KZ 233/1000
EN-KZ 234/1000
EN-KZ 235/1000
EN-KZ 236/1000
EN-KZ 237/1000
EN-KZ 238/1000
EN-KZ 239/1000
EN-KZ 240/1000
EN-KZ 241/1000
EN-KZ 242/1000
EN-KZ 243/1000
EN-KZ 244/1000
EN-KZ 245/1000
EN-KZ 246/1000
EN-KZ 247/1000
EN-KZ 248/1000
EN-KZ 249/1000
EN-KZ 250/1000
EN-KZ 251/1000
EN-KZ 252/1000
EN-KZ 253/1000
EN-KZ 254/1000
EN-KZ 255/1000
EN-KZ 256/1000
EN-KZ 257/1000
EN-KZ 258/1000
EN-KZ 259/1000
EN-KZ 260/1000
EN-KZ 261/1000
EN-KZ 262/1000
EN-KZ 263/1000
EN-KZ 264/1000
EN-KZ 265/1000
EN-KZ 266/1000
EN-KZ 267/1000
EN-KZ 268/1000
EN-KZ 269/1000
EN-KZ 270/1000
EN-KZ 271/1000
EN-KZ 272/1000
EN-KZ 273/1000
EN-KZ 274/1000
EN-KZ 275/1000
EN-KZ 276/1000
EN-KZ 277/1000
EN-KZ 278/1000
EN-KZ 279/1000
EN-KZ 280/1000
EN-KZ 281/1000
EN-KZ 282/1000
EN-KZ 283/1000
EN-KZ 284/1000
EN-KZ 285/1000
EN-KZ 286/1000
EN-KZ 287/1000
EN-KZ 288/1000
EN-KZ 289/1000
EN-KZ 290/1000
EN-KZ 291/1000
EN-KZ 292/1000
EN-KZ 293/1000
EN-KZ 294/1000
EN-KZ 295/1000
EN-KZ 296/1000
EN-KZ 297/1000
EN-KZ 298/1000
EN-KZ 299/1000
EN-KZ 300/1000
EN-KZ 301/1000
EN-KZ 302/1000
EN-KZ 303/1000
EN-KZ 304/1000
EN-KZ 305/1000
EN-KZ 306/1000
EN-KZ 307/1000
EN-KZ 308/1000
EN-KZ 309/1000
EN-KZ 310/1000
EN-KZ 311/1000
EN-KZ 312/1000
EN-KZ 313/1000
EN-KZ 314/1000
EN-KZ 315/1000
EN-KZ 316/1000
EN-KZ 317/1000
EN-KZ 318/1000
EN-KZ 319/1000
EN-KZ 320/1000
EN-KZ 321/1000
EN-KZ 322/1000
EN-KZ 323/1000
EN-KZ 324/1000
EN-KZ 325/1000
EN-KZ 326/1000
EN-KZ 327/1000
EN-KZ 328/1000
EN-KZ 329/1000
EN-KZ 330/1000
EN-KZ 331/1000
EN-KZ 332/1000
EN-KZ 333/1000
EN-KZ 334/1000
EN-KZ 335/1000
EN-KZ 336/1000
EN-KZ 337/1000
EN-KZ 338/1000
EN-KZ 339/1000
EN-KZ 340/1000
EN-KZ 341/1000
EN-KZ 342/1000
EN-KZ 343/1000
EN-KZ 344/1000
EN-KZ 345/1000
EN-KZ 346/1000
EN-KZ 347/1000
EN-KZ 348/1000
EN-KZ 349/1000
EN-KZ 350/1000
EN-KZ 351/1000
EN-KZ 352/1000
EN-KZ 353/1000
EN-KZ 354/1000
EN-KZ 355/1000
EN-KZ 356/1000
EN-KZ 357/1000
EN-KZ 358/1000
EN-KZ 359/1000
EN-KZ 360/1000
EN-KZ 361/1000
EN-KZ 362/1000
EN-KZ 363/1000
EN-KZ 364/1000
EN-KZ 365/1000
EN-KZ 366/1000
EN-KZ 367/1000
EN-KZ 368/1000
EN-KZ 369/1000
EN-KZ 370/1000
EN-KZ 371/1000
EN-KZ 372/1000
EN-KZ 373/1000
EN-KZ 374/1000
EN-KZ 375/1000
EN-KZ 376/1000
EN-KZ 377/1000
EN-KZ 378/1000
EN-KZ 379/1000
EN-KZ 380/1000
EN-KZ 381/1000
EN-KZ 382/1000
EN-KZ 383/1000
EN-KZ 384/1000
EN-KZ 385/1000
EN-KZ 386/1000
EN-KZ 387/1000
EN-KZ 388/1000
EN-KZ 389/1000
EN-KZ 390/1000
EN-KZ 391/1000
EN-KZ 392/1000
EN-KZ 393/1000
EN-KZ 394/1000
EN-KZ 395/1000
EN-KZ 396/1000
EN-KZ 397/1000
EN-KZ 398/1000
EN-KZ 399/1000
EN-KZ 400/1000
EN-KZ 401/1000
EN-KZ 402/1000
EN-KZ 403/1000
EN-KZ 404/1000
EN-KZ 405/1000
EN-KZ 406/1000
EN-KZ 407/1000
EN-KZ 408/1000
EN-KZ 409/1000
EN-KZ 410/1000
EN-KZ 411/1000
EN-KZ 412/1000
EN-KZ 413/1000
EN-KZ 414/1000
EN-KZ 415/1000
EN-KZ 416/1000
EN-KZ 417/1000
EN-KZ 418/1000
EN-KZ 419/1000
EN-KZ 420/1000
EN-KZ 421/1000
EN-KZ 422/1000
EN-KZ 423/1000
EN-KZ 424/1000
EN-KZ 425/1000
EN-KZ 426/1000
EN-KZ 427/1000
EN-KZ 428/1000
EN-KZ 429/1000
EN-KZ 430/1000
EN-KZ 431/1000
EN-KZ 432/1000
EN-KZ 433/1000
EN-KZ 434/1000
EN-KZ 435/1000
EN-KZ 436/1000
EN-KZ 437/1000
EN-KZ 438/1000
EN-KZ 439/1000
EN-KZ 440/1000
EN-KZ 441/1000
EN-KZ 442/1000
EN-KZ 443/1000
EN-KZ 444/1000
EN-KZ 445/1000
EN-KZ 446/1000
EN-KZ 447/1000
EN-KZ 448/1000
EN-KZ 449/1000
EN-KZ 450/1000
EN-KZ 451/1000
EN-KZ 452/1000
EN-KZ 453/1000
EN-KZ 454/1000
EN-KZ 455/1000
EN-KZ 456/1000
EN-KZ 457/1000
EN-KZ 458/1000
EN-KZ 459/1000
EN-KZ 460/1000
EN-KZ 461/1000
EN-KZ 462/1000
EN-KZ 463/1000
EN-KZ 464/1000
EN-KZ 465/1000
EN-KZ 466/1000
EN-KZ 467/1000
EN-KZ 468/1000
EN-KZ 469/1000
EN-KZ 470/1000
EN-KZ 471/1000
EN-KZ 472/1000
EN-KZ 473/1000
EN-KZ 474/1000
EN-KZ 475/1000
EN-KZ 476/1000
EN-KZ 477/1000
EN-KZ 478/1000
EN-KZ 479/1000
EN-KZ 480/1000
EN-KZ 481/1000
EN-KZ 482/1000
EN-KZ 483/1000
EN-KZ 484/1000
EN-KZ 485/1000
EN-KZ 486/1000
EN-KZ 487/1000
EN-KZ 488/1000
EN-KZ 489/1000
EN-KZ 490/1000
EN-KZ 491/1000
EN-KZ 492/1000
EN-KZ 493/1000
EN-KZ 494/1000
EN-KZ 495/1000
EN-KZ 496/1000
EN-KZ 497/1000
EN-KZ 498/1000
EN-KZ 499/1000
EN-KZ 500/1000
EN-KZ 501/1000
EN-KZ 502/1000
EN-KZ 503/1000
EN-KZ 504/1000
EN-KZ 505/1000
EN-KZ 506/1000
EN-KZ 507/1000
EN-KZ 508/1000
EN-KZ 509/1000
EN-KZ 510/1000
EN-KZ 511/1000
EN-KZ 512/1000
EN-KZ 513/1000
EN-KZ 514/1000
EN-KZ 515/1000
EN-KZ 516/1000
EN-KZ 517/1000
EN-KZ 518/1000
EN-KZ 519/1000
EN-KZ 520/1000
EN-KZ 521/1000
EN-KZ 522/1000
EN-KZ 523/1000
EN-KZ 524/1000
EN-KZ 525/1000
EN-KZ 526/1000
EN-KZ 527/1000
EN-KZ 528/1000
EN-KZ 529/1000
EN-KZ 530/1000
EN-KZ 531/1000
EN-KZ 532/1000
EN-KZ 533/1000
EN-KZ 534/1000
EN-KZ 535/1000
EN-KZ 536/1000
EN-KZ 537/1000
EN-KZ 538/1000
EN-KZ 539/1000
EN-KZ 540/1000
EN-KZ 541/1000
EN-KZ 542/1000
EN-KZ 543/1000
EN-KZ 544/1000
EN-KZ 545/1000
EN-KZ 546/1000
EN-KZ 547/1000
EN-KZ 548/1000
EN-KZ 549/1000
EN-KZ 550/1000
EN-KZ 551/1000
EN-KZ 552/1000
EN-KZ 553/1000
EN-KZ 554/1000

EN-KZ 555/1000
EN-KZ 556/1000
EN-KZ 557/1000
EN-KZ 558/1000
EN-KZ 559/1000
EN-KZ 560/1000
EN-KZ 561/1000
EN-KZ 562/1000
EN-KZ 563/1000
EN-KZ 564/1000
EN-KZ 565/1000
EN-KZ 566/1000
EN-KZ 567/1000
EN-KZ 568/1000
EN-KZ 569/1000
EN-KZ 570/1000
EN-KZ 571/1000
EN-KZ 572/1000
EN-KZ 573/1000
EN-KZ 574/1000
EN-KZ 575/1000
EN-KZ 576/1000
EN-KZ 577/1000
EN-KZ 578/1000
EN-KZ 579/1000
EN-KZ 580/1000
EN-KZ 581/1000
EN-KZ 582/1000
EN-KZ 583/1000
EN-KZ 584/1000
EN-KZ 585/1000
EN-KZ 586/1000
EN-KZ 587/1000
EN-KZ 588/1000
EN-KZ 589/1000
EN-KZ 590/1000
EN-KZ 591/1000
EN-KZ 592/1000
EN-KZ 593/1000
EN-KZ 594/1000
EN-KZ 595/1000
EN-KZ 596/1000
EN-KZ 597/1000
EN-KZ 598/1000
EN-KZ 599/1000
EN-KZ 600/1000
EN-KZ 601/1000
EN-KZ 602/1000
EN-KZ 603/1000
EN-KZ 604/1000
EN-KZ 605/1000
EN-KZ 606/1000
EN-KZ 607/1000
EN-KZ 608/1000
EN-KZ 609/1000
EN-KZ 610/1000
EN-KZ 611/1000
EN-KZ 612/1000
EN-KZ 613/1000
EN-KZ 614/1000
EN-KZ 615/1000
EN-KZ 616/1000
EN-KZ 617/1000
EN-KZ 618/1000
EN-KZ 619/1000
EN-KZ 620/1000
EN-KZ 621/1000
EN-KZ 622/1000
EN-KZ 623/1000
EN-KZ 624/1000
EN-KZ 625/1000
EN-KZ 626/1000
EN-KZ 627/1000
EN-KZ 628/1000
EN-KZ 629/1000
EN-KZ 630/1000
EN-KZ 631/1000
EN-KZ 632/1000
EN-KZ 633/1000
EN-KZ 634/1000
EN-KZ 635/1000
EN-KZ 636/1000
EN-KZ 637/1000
EN-KZ 638/1000
EN-KZ 639/1000
EN-KZ 640/1000
EN-KZ 641/1000
EN-KZ 642/1000
EN-KZ 643/1000
EN-KZ 644/1000
EN-KZ 645/1000
EN-KZ 646/1000
EN-KZ 647/1000
EN-KZ 648/1000
EN-KZ 649/1000
EN-KZ 650/1000
EN-KZ 651/1000
EN-KZ 652/1000
EN-KZ 653/1000
EN-KZ 654/1000
EN-KZ 655/1000
EN-KZ 656/1000
EN-KZ 657/1000
EN-KZ 658/1000
EN-KZ 659/1000
EN-KZ 660/1000
EN-KZ 661/1000
EN-KZ 662/1000
EN-KZ 663/1000
EN-KZ 664/1000
EN-KZ 665/1000
EN-KZ 666/1000
EN-KZ 667/1000
EN-KZ 668/1000
EN-KZ 669/1000
EN-KZ 670/1000
EN-KZ 671/1000
EN-KZ 672/1000
EN-KZ 673/1000
EN-KZ 674/1000
EN-KZ 675/1000
EN-KZ 676/1000
EN-KZ 677/1000
EN-KZ 678/1000
EN-KZ 679/1000
EN-KZ 680/1000
EN-KZ 681/1000
EN-KZ 682/1000
EN-KZ 683/1000
EN-KZ 684/1000
EN-KZ 685/1000
EN-KZ 686/1000
EN-KZ 687/1000
EN-KZ 688/1000
EN-KZ 689/1000
EN-KZ 690/1000
EN-KZ 691/1000
EN-KZ 692/1000
EN-KZ 693/1000
EN-KZ 694/1000
EN-KZ 695/1000
EN-KZ 696/1000
EN-KZ 697/1000
EN-KZ 698/1000
EN-KZ 699/1000
EN-KZ 700/1000
EN-KZ 701/1000
EN-KZ 702/1000
EN-KZ 703/1000
EN-KZ 704/1000
EN-KZ 705/1000
EN-KZ 706/1000
EN-KZ 707/1000
EN-KZ 708/1000
EN-KZ 709/1000
EN-KZ 710/1000
EN-KZ 711/1000
EN-KZ 712/1000
EN-KZ 713/1000
EN-KZ 714/1000
EN-KZ 715/1000
EN-KZ 716/1000
EN-KZ 717/1000
EN-KZ 718/1000
EN-KZ 719/1000
EN-KZ 720/1000
EN-KZ 721/1000
EN-KZ 722/1000
EN-KZ 723/1000
EN-KZ 724/1000
EN-KZ 725/1000
EN-KZ 726/1000
EN-KZ 727/1000
EN-KZ 728/1000
EN-KZ 729/1000
EN-KZ 730/1000
EN-KZ 731/1000
EN-KZ 732/1000
EN-KZ 733/1000
EN-KZ 734/1000
EN-KZ 735/1000
EN-KZ 736/1000
EN-KZ 737/1000
EN-KZ 738/1000
EN-KZ 739/1000
EN-KZ 740/1000
EN-KZ 741/1000
EN-KZ 742/1000
EN-KZ 743/1000
EN-KZ 744/1000
EN-KZ 745/1000
EN-KZ 746/1000
EN-KZ 747/1000
EN-KZ 748/1000
EN-KZ 749/1000
EN-KZ 750/1000
EN-KZ 751/1000
EN-KZ 752/1000
EN-KZ 753/1000
EN-KZ 754/1000
EN-KZ 755/1000
EN-KZ 756/1000
EN-KZ 757/1000
EN-KZ 758/1000
EN-KZ 759/1000
EN-KZ 760/1000
EN-KZ 761/1000
EN-KZ 762/1000
EN-KZ 763/1000
EN-KZ 764/1000
EN-KZ 765/1000
EN-KZ 766/1000
EN-KZ 767/1000
EN-KZ 768/1000
EN-KZ 769/1000
EN-KZ 770/1000
EN-KZ 771/1000
EN-KZ 772/1000
EN-KZ 773/1000
EN-KZ 774/1000
EN-KZ 775/1000
EN-KZ 776/1000
EN-KZ 777/1000
EN-KZ 778/1000
EN-KZ 779/1000
EN-KZ 780/1000
EN-KZ 781/1000
EN-KZ 782/1000
EN-KZ 783/1000
EN-KZ 784/1000
EN-KZ 785/1000
EN-KZ 786/1000
EN-KZ 787/1000
EN-KZ 788/1000
EN-KZ 789/1000
EN-KZ 790/1000
EN-KZ 791/1000
EN-KZ 792/1000
EN-KZ 793/1000
EN-KZ 794/1000
EN-KZ 795/1000
EN-KZ 796/1000
EN-KZ 797/1000
EN-KZ 798/1000
EN-KZ 799/1000
EN-KZ 800/1000
EN-KZ 801/1000
EN-KZ 802/1000
EN-KZ 803/1000
EN-KZ 804/1000
EN-KZ 805/1000
EN-KZ 806/1000
EN-KZ 807/1000
EN-KZ 808/1000
EN-KZ 809/1000
EN-KZ 810/1000
EN-KZ 811/1000
EN-KZ 812/1000
EN-KZ 813/1000
EN-KZ 814/1000
EN-KZ 815/1000
EN-KZ 816/1000
EN-KZ 817/1000
EN-KZ 818/1000
EN-KZ 819/1000
EN-KZ 820/1000
EN-KZ 821/1000
EN-KZ 822/1000
EN-KZ 823/1000
EN-KZ 824/1000
EN-KZ 825/1000
EN-KZ 826/1000
EN-KZ 827/1000
EN-KZ 828/1000
EN-KZ 829/1000
EN-KZ 830/1000
EN-KZ 831/1000
EN-KZ 832/1000
EN-KZ 833/1000
EN-KZ 834/1000
EN-KZ 835/1000
EN-KZ 836/1000
EN-KZ 837/1000
EN-KZ 838/1000
EN-KZ 839/1000
EN-KZ 840/1000
EN-KZ 841/1000
EN-KZ 842/1000
EN-KZ 843/1000
EN-KZ 844/1000
EN-KZ 845/1000
EN-KZ 846/1000
EN-KZ 847/1000
EN-KZ 848/1000
EN-KZ 849/1000
EN-KZ 850/1000
EN-KZ 851/1000
EN-KZ 852/1000
EN-KZ 853/1000
EN-KZ 854/1000
EN-KZ 855/1000
EN-KZ 856/1000
EN-KZ 857/1000
EN-KZ 858/1000
EN-KZ 859/1000
EN-KZ 860/1000
EN-KZ 861/1000
EN-KZ 862/1000
EN-KZ 863/1000
EN-KZ 864/1000
EN-KZ 865/1000
EN-KZ 866/1000
EN-KZ 867/1000
EN-KZ 868/1000
EN-KZ 869/1000
EN-KZ 870/1000
EN-KZ 871/1000
EN-KZ 872/1000
EN-KZ 873/1000
EN-KZ 874/1000
EN-KZ 875/1000
EN-KZ 876/1000
EN-KZ 877/1000
EN-KZ 878/1000
EN-KZ 879/1000
EN-KZ 880/1000
EN-KZ 881/1000
EN-KZ 882/1000
EN-KZ 883/1000
EN-KZ 884/1000
EN-KZ 885/1000
EN-KZ 886/1000
EN-KZ 887/1000
EN-KZ 888/1000
EN-KZ 889/1000
EN-KZ 890/1000
EN-KZ 891/1000
EN-KZ 892/1000
EN-KZ 893/1000
EN-KZ 894/1000
EN-KZ 895/1000
EN-KZ 896/1000
EN-KZ 897/1000
EN-KZ 898/1000
EN-KZ 899/1000
EN-KZ 900/1000
EN-KZ 901/1000
EN-KZ 902/1000
EN-KZ 903/1000
EN-KZ 904/1000
EN-KZ 905/1000
EN-KZ 906/1000
EN-KZ 907/1000
EN-KZ 908/1000
EN-KZ 909/1000
EN-KZ 910/1000
EN-KZ 911/1000
EN-KZ 912/1000
EN-KZ 913/1000
EN-KZ 914/1000
EN-KZ 915/1000
EN-KZ 916/1000
EN-KZ 917/1000
EN-KZ 918/1000
EN-KZ 919/1000
EN-KZ 920/1000
EN-KZ 921/1000
EN-KZ 922/1000
EN-KZ 923/1000
EN-KZ 924/1000
EN-KZ 925/1000
EN-KZ 926/1000
EN-KZ 927/1000
EN-KZ 928/1000
EN-KZ 929/1000
EN-KZ 930/1000
EN-KZ 931/1000
EN-KZ 932/1000
EN-KZ 933/1000
EN-KZ 934/1000
EN-KZ 935/1000
EN-KZ 936/1000
EN-KZ 937/1000
EN-KZ 938/1000
EN-KZ 939/1000
EN-KZ 940/1000
EN-KZ 941/1000
EN-KZ 942/1000
EN-KZ 943/1000
EN-KZ 944/1000
EN-KZ 945/1000
EN-KZ 946/1000
EN-KZ 947/1000
EN-KZ 948/1000
EN-KZ 949/1000
EN-KZ 950/1000
EN-KZ 951/1000
EN-KZ 952/1000
EN-KZ 953/1000
EN-KZ 954/1000
EN-KZ 955/1000
EN-KZ 956/1000
EN-KZ 957/1000
EN-KZ 958/1000
EN-KZ 959/1000
EN-KZ 960/1000
EN-KZ 961/1000
EN-KZ 962/1000
EN-KZ 963/1000
EN-KZ 964/1000
EN-KZ 965/1000
EN-KZ 966/1000
EN-KZ 967/1000
EN-KZ 968/1000
EN-KZ 969/1000
EN-KZ 970/1000
EN-KZ 971/1000
EN-KZ 972/1000
EN-KZ 973/1000
EN-KZ 974/1000
EN-KZ 975/1000
EN-KZ 976/1000
EN-KZ 977/1000
EN-KZ 978/1000
EN-KZ 979/1000
EN-KZ 980/1000
EN-KZ 981/1000
EN-KZ 982/1000
EN-KZ 983/1000
EN-KZ 984/1000
EN-KZ 985/1000
EN-KZ 986/1000
EN-KZ 987/1000
EN-KZ 988/1000
EN-KZ 989/1000
EN-KZ 990/1000
EN-KZ 991/1000
EN-KZ 992/1000
EN-KZ 993/1000
EN-KZ 994/1000
EN-KZ 995/1000
EN-KZ 996/1000
EN-KZ 997/1000
EN-KZ 998/1000
EN-KZ 999/1000
EN-KZ 1000/1000
English prompt + Kazakh review classification finished

In [18]:
df = pd.read_csv("imdb_predictions_enkz_final.csv")

print(len(df))
print(df["pred_kz"].value_counts())
print(df["pred_en_kz"].value_counts())
print(df["pred_en_kz"].isna().sum())

1000
теріс    539
оң       461
Name: pred_kz, dtype: int64
negative    538
positive    462
Name: pred_en_kz, dtype: int64
0

In [19]:
from sklearn.metrics import classification_report, accuracy_score

df = pd.read_csv("imdb_predictions_enkz_final.csv")

print(classification_report(df["sentiment"], df["pred_en_kz"]))
print("Accuracy:", accuracy_score(df["sentiment"], df["pred_en_kz"]))

              precision    recall  f1-score   support

    negative       0.91      0.98      0.94       500
    positive       0.98      0.90      0.94       500

    accuracy                           0.94      1000
   macro avg       0.94      0.94      0.94      1000
weighted avg       0.94      0.94      0.94      1000

Accuracy: 0.94